package monster

type TemporaryStatType string

const (
	TemporaryStatTypeWeaponAttack       TemporaryStatType = "WEAPON_ATTACK"
	TemporaryStatTypeWeaponDefense      TemporaryStatType = "WEAPON_DEFENSE"
	TemporaryStatTypeMagicAttack        TemporaryStatType = "MAGIC_ATTACK"
	TemporaryStatTypeMagicDefense       TemporaryStatType = "MAGIC_DEFENSE"
	TemporaryStatTypeAccuracy           TemporaryStatType = "ACCURACY"
	TemporaryStatTypeAvoidability       TemporaryStatType = "AVOIDABILITY"
	TemporaryStatTypeSpeed              TemporaryStatType = "SPEED"
	TemporaryStatTypeStun               TemporaryStatType = "STUN"
	TemporaryStatTypeFrozen             TemporaryStatType = "FROZEN"
	TemporaryStatTypePoison             TemporaryStatType = "POISON"
	TemporaryStatTypeSeal               TemporaryStatType = "SEAL"
	TemporaryStatTypeDarkness           TemporaryStatType = "DARKNESS"
	TemporaryStatTypePowerUp            TemporaryStatType = "POWER_UP"
	TemporaryStatTypeMagicUp            TemporaryStatType = "MAGIC_UP"
	TemporaryStatTypePowerGuardUp       TemporaryStatType = "POWER_GUARD_UP"
	TemporaryStatTypeMagicGuardUp       TemporaryStatType = "MAGIC_GUARD_UP"
	TemporaryStatTypeDoom               TemporaryStatType = "DOOM"
	TemporaryStatTypeWeb                TemporaryStatType = "WEB"
	TemporaryStatTypeWeaponAttackImmune TemporaryStatType = "WEAPON_ATTACK_IMMUNE"
	TemporaryStatTypeMagicAttackImmune  TemporaryStatType = "MAGIC_ATTACK_IMMUNE"
	TemporaryStatTypeShowdown           TemporaryStatType = "SHOWDOWN"
	TemporaryStatTypeHardSkin           TemporaryStatType = "HARD_SKIN"
	TemporaryStatTypeAmbush             TemporaryStatType = "AMBUSH"
	TemporaryStatTypeDamagedElemAttr    TemporaryStatType = "DAMAGED_ELEM_ATTR"
	TemporaryStatTypeVenom              TemporaryStatType = "VENOM"
	TemporaryStatTypeBlind              TemporaryStatType = "BLIND"
	TemporaryStatTypeSealSkill          TemporaryStatType = "SEAL_SKILL"
	TemporaryStatTypeBurned             TemporaryStatType = "BURNED"
	TemporaryStatTypeDazzle             TemporaryStatType = "DAZZLE"
	TemporaryStatTypeWeaponCounter      TemporaryStatType = "WEAPON_COUNTER"
	TemporaryStatTypeMagicCounter       TemporaryStatType = "MAGIC_COUNTER"
	TemporaryStatTypeDisable            TemporaryStatType = "DISABLE"
	TemporaryStatTypeRiseByToss         TemporaryStatType = "RISE_BY_TOSS"
	TemporaryStatTypeBodyPressure       TemporaryStatType = "BODY_PRESSURE"
	TemporaryStatTypeWeakness           TemporaryStatType = "WEAKNESS"
	TemporaryStatTypeTimeBomb           TemporaryStatType = "TIME_BOMB"
	TemporaryStatTypeMagicCrash         TemporaryStatType = "MAGIC_CRASH"
	TemporaryStatTypeHealByDamage       TemporaryStatType = "HEAL_BY_DAMAGE"
)
