// Command gen-map-action-schema regenerates
// services/atlas-map-actions/docs/map_script_schema.json's condition-type,
// operator, and operation enums from their Go sources of truth, so the
// hand-maintained schema cannot silently drift from what
// atlas-map-actions/script actually accepts at runtime (task-290 design D4 /
// PRD FR-1.1, FR-1.2, FR-3.0).
//
// Run from tools/gen-map-action-schema (deliberately outside go.work; invoke
// with GOWORK=off, same posture as libs/atlas-kafka/gen and tools/catalog-lint):
//
//	go run .           # rewrite the schema in place
//	go run . --check   # drift check: exit 1 with a diff if the schema is stale
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const (
	sagaValidationPath = "libs/atlas-saga/validation.go"
	executorPath       = "services/atlas-map-actions/atlas.com/map-actions/script/executor.go"
	schemaPath         = "services/atlas-map-actions/docs/map_script_schema.json"

	executeOperationFunc = "ExecuteOperation"
	localMapIDType       = "map_id"
)

// syntheticOperators are accepted by evaluateMapId (script/evaluator.go) for
// the locally-evaluated map_id condition but are not part of the
// aggregator's operator const block (libs/atlas-saga/validation.go), so they
// cannot be discovered by parsing that block. They are appended explicitly.
var syntheticOperators = []string{"==", "!="}

func main() {
	check := len(os.Args) > 1 && os.Args[1] == "--check"

	repoRoot, err := repoRootFromGit()
	if err != nil {
		fmt.Fprintln(os.Stderr, "resolving repo root failed:", err)
		os.Exit(1)
	}

	sagaSrc, err := os.ReadFile(filepath.Join(repoRoot, sagaValidationPath))
	if err != nil {
		fmt.Fprintln(os.Stderr, "reading", sagaValidationPath, "failed:", err)
		os.Exit(1)
	}
	executorSrc, err := os.ReadFile(filepath.Join(repoRoot, executorPath))
	if err != nil {
		fmt.Fprintln(os.Stderr, "reading", executorPath, "failed:", err)
		os.Exit(1)
	}
	existingSchema, err := os.ReadFile(filepath.Join(repoRoot, schemaPath))
	if err != nil {
		fmt.Fprintln(os.Stderr, "reading", schemaPath, "failed:", err)
		os.Exit(1)
	}

	sagaConditionTypes, err := parseStringConsts(string(sagaSrc), 0)
	if err != nil {
		fmt.Fprintln(os.Stderr, "parsing condition-type consts failed:", err)
		os.Exit(1)
	}
	sagaOperators, err := parseStringConsts(string(sagaSrc), 1)
	if err != nil {
		fmt.Fprintln(os.Stderr, "parsing operator consts failed:", err)
		os.Exit(1)
	}
	operations, err := parseSwitchCases(string(executorSrc), executeOperationFunc)
	if err != nil {
		fmt.Fprintln(os.Stderr, "parsing", executeOperationFunc, "switch failed:", err)
		os.Exit(1)
	}

	sortedConditionTypes := append([]string{}, sagaConditionTypes...)
	sort.Strings(sortedConditionTypes)
	conditionTypes := append([]string{localMapIDType}, sortedConditionTypes...)

	operators := append(append([]string{}, sagaOperators...), syntheticOperators...)

	allOf, err := existingAllOf(existingSchema)
	if err != nil {
		fmt.Fprintln(os.Stderr, "reading existing allOf block failed:", err)
		os.Exit(1)
	}

	generated, err := render(conditionTypes, operators, operations, allOf)
	if err != nil {
		fmt.Fprintln(os.Stderr, "render failed:", err)
		os.Exit(1)
	}

	outPath := filepath.Join(repoRoot, schemaPath)

	if check {
		if !bytes.Equal(existingSchema, generated) {
			printDiff(outPath, generated)
			fmt.Fprintf(os.Stderr, "gen-map-action-schema: %s is stale; run tools/gen-map-action-schema.sh and commit\n", schemaPath)
			os.Exit(1)
		}
		fmt.Println("gen-map-action-schema:", schemaPath, "is up to date")
		return
	}

	if err := os.WriteFile(outPath, generated, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "writing", schemaPath, "failed:", err)
		os.Exit(1)
	}
	fmt.Println("gen-map-action-schema: wrote", schemaPath)
}

// repoRootFromGit resolves the repository root so this generator can be run
// from tools/gen-map-action-schema -- a module deliberately not listed in
// go.work -- while still finding its inputs relative to the repo root.
func repoRootFromGit() (string, error) {
	out, err := exec.Command("git", "rev-parse", "--show-toplevel").Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}

// printDiff shells out to `diff -u` to render a unified diff between the
// checked-in file at path and the freshly generated bytes, writing the
// result to stderr. Mirrors tools/gen-tenant-tables.sh's --check tail.
func printDiff(path string, generated []byte) {
	tmp, err := os.CreateTemp("", "gen-map-action-schema-*.json")
	if err != nil {
		fmt.Fprintln(os.Stderr, "creating temp file for diff failed:", err)
		return
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.Write(generated); err != nil {
		fmt.Fprintln(os.Stderr, "writing temp file for diff failed:", err)
		tmp.Close()
		return
	}
	tmp.Close()

	cmd := exec.Command("diff", "-u", path, tmp.Name())
	out, _ := cmd.CombinedOutput()
	fmt.Fprint(os.Stderr, string(out))
}

// parseStringConsts returns the string literal values of the nth top-level
// const block in src, in declaration order. Comments and blank lines
// contribute nothing.
func parseStringConsts(src string, blockIndex int) ([]string, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "", src, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parsing source failed: %w", err)
	}

	var values []string
	seen := 0
	for _, decl := range f.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.CONST {
			continue
		}
		if seen != blockIndex {
			seen++
			continue
		}
		seen++

		for _, spec := range gen.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok || len(vs.Values) == 0 {
				continue
			}
			lit, ok := vs.Values[0].(*ast.BasicLit)
			if !ok || lit.Kind != token.STRING {
				continue
			}
			unquoted, err := strconv.Unquote(lit.Value)
			if err != nil {
				return nil, fmt.Errorf("unquoting const literal %s failed: %w", lit.Value, err)
			}
			values = append(values, unquoted)
		}
		return values, nil
	}

	return nil, fmt.Errorf("const block %d not found", blockIndex)
}

// parseSwitchCases returns the string literal case values of the first
// type-less switch statement found in the named function's body, in
// declaration order. The default arm contributes nothing.
func parseSwitchCases(src, funcName string) ([]string, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "", src, 0)
	if err != nil {
		return nil, fmt.Errorf("parsing source failed: %w", err)
	}

	var fn *ast.FuncDecl
	for _, decl := range f.Decls {
		fd, ok := decl.(*ast.FuncDecl)
		if !ok || fd.Name == nil || fd.Name.Name != funcName {
			continue
		}
		fn = fd
		break
	}
	if fn == nil {
		return nil, fmt.Errorf("function %s not found", funcName)
	}

	var sw *ast.SwitchStmt
	ast.Inspect(fn.Body, func(n ast.Node) bool {
		if sw != nil {
			return false
		}
		if s, ok := n.(*ast.SwitchStmt); ok {
			sw = s
			return false
		}
		return true
	})
	if sw == nil {
		return nil, fmt.Errorf("no switch statement found in function %s", funcName)
	}

	var cases []string
	for _, stmt := range sw.Body.List {
		cc, ok := stmt.(*ast.CaseClause)
		if !ok || cc.List == nil {
			// cc.List == nil is the default arm; it contributes nothing.
			continue
		}
		for _, expr := range cc.List {
			lit, ok := expr.(*ast.BasicLit)
			if !ok || lit.Kind != token.STRING {
				continue
			}
			unquoted, err := strconv.Unquote(lit.Value)
			if err != nil {
				return nil, fmt.Errorf("unquoting case literal %s failed: %w", lit.Value, err)
			}
			cases = append(cases, unquoted)
		}
	}

	return cases, nil
}

// schemaFile mirrors the subset of map_script_schema.json's shape needed to
// read back the hand-written definitions.operation.allOf array verbatim.
type schemaFile struct {
	Definitions struct {
		Operation struct {
			AllOf json.RawMessage `json:"allOf"`
		} `json:"operation"`
	} `json:"definitions"`
}

// existingAllOf extracts the hand-written definitions.operation.allOf array
// from the checked-in schema so it can be re-emitted verbatim -- it is the
// only region this generator does not derive from Go source.
func existingAllOf(existingSchema []byte) (json.RawMessage, error) {
	var sf schemaFile
	if err := json.Unmarshal(existingSchema, &sf); err != nil {
		return nil, fmt.Errorf("unmarshaling existing schema failed: %w", err)
	}
	if len(sf.Definitions.Operation.AllOf) == 0 {
		return nil, fmt.Errorf("existing schema has no definitions.operation.allOf block")
	}
	return sf.Definitions.Operation.AllOf, nil
}

// allOfEntry is the subset of one definitions.operation.allOf array element
// needed to discover which operation type it documents.
type allOfEntry struct {
	If struct {
		Properties struct {
			Type struct {
				Const string `json:"const"`
			} `json:"type"`
		} `json:"properties"`
	} `json:"if"`
}

// --- schema document shape ---
//
// Every field below except allOf is fully generated; only the enums vary
// with the Go sources of truth this generator parses. allOf is spliced in
// verbatim from the checked-in schema (see existingAllOf).

type schemaDoc struct {
	Schema      string           `json:"$schema"`
	Title       string           `json:"title"`
	Description string           `json:"description"`
	Type        string           `json:"type"`
	Required    []string         `json:"required"`
	Properties  topProperties    `json:"properties"`
	Definitions definitionsBlock `json:"definitions"`
}

type simpleProp struct {
	Type        string `json:"type"`
	Description string `json:"description"`
}

type refProp struct {
	Ref string `json:"$ref"`
}

type arrayRefProp struct {
	Type        string  `json:"type"`
	Description string  `json:"description"`
	Items       refProp `json:"items"`
}

type enumProp struct {
	Type        string   `json:"type"`
	Description string   `json:"description"`
	Enum        []string `json:"enum"`
}

type topProperties struct {
	ScriptName  simpleProp   `json:"scriptName"`
	Description simpleProp   `json:"description"`
	Rules       arrayRefProp `json:"rules"`
}

type definitionsBlock struct {
	Rule      ruleDef      `json:"rule"`
	Condition conditionDef `json:"condition"`
	Operation operationDef `json:"operation"`
}

type ruleDef struct {
	Type        string         `json:"type"`
	Description string         `json:"description"`
	Required    []string       `json:"required"`
	Properties  ruleProperties `json:"properties"`
}

type ruleProperties struct {
	Id         simpleProp   `json:"id"`
	Conditions arrayRefProp `json:"conditions"`
	Operations arrayRefProp `json:"operations"`
}

type conditionDef struct {
	Type        string              `json:"type"`
	Description string              `json:"description"`
	Required    []string            `json:"required"`
	Properties  conditionProperties `json:"properties"`
}

type conditionProperties struct {
	Type        enumProp   `json:"type"`
	Operator    enumProp   `json:"operator"`
	Value       simpleProp `json:"value"`
	ReferenceId simpleProp `json:"referenceId"`
	ValueString simpleProp `json:"valueString"`
}

type operationDef struct {
	Type        string              `json:"type"`
	Description string              `json:"description"`
	Required    []string            `json:"required"`
	Properties  operationProperties `json:"properties"`
	AllOf       json.RawMessage     `json:"allOf"`
}

type operationProperties struct {
	Type   enumProp   `json:"type"`
	Params paramsProp `json:"params"`
}

type paramsProp struct {
	Type                 string          `json:"type"`
	Description          string          `json:"description"`
	AdditionalProperties additionalProps `json:"additionalProperties"`
}

type additionalProps struct {
	Type string `json:"type"`
}

// render produces the complete schema JSON from the parsed inputs and the
// hand-written allOf template. It errors when an operation has no allOf
// block, so a new executor arm without documented params fails the
// generator instead of shipping a silent hole.
func render(conditionTypes, operators, operations []string, allOf json.RawMessage) ([]byte, error) {
	var entries []allOfEntry
	if err := json.Unmarshal(allOf, &entries); err != nil {
		return nil, fmt.Errorf("unmarshaling allOf block failed: %w", err)
	}
	documented := make(map[string]bool, len(entries))
	for _, e := range entries {
		if e.If.Properties.Type.Const != "" {
			documented[e.If.Properties.Type.Const] = true
		}
	}
	for _, op := range operations {
		if !documented[op] {
			return nil, fmt.Errorf("operation %q has no allOf param block in the schema template", op)
		}
	}

	doc := schemaDoc{
		Schema:      "http://json-schema.org/draft-07/schema#",
		Title:       "Map Script",
		Description: "JSON schema for map scripts - defines rules for map entry behavior (onFirstUserEnter, onUserEnter)",
		Type:        "object",
		Required:    []string{"scriptName", "rules"},
		Properties: topProperties{
			ScriptName: simpleProp{
				Type:        "string",
				Description: "The script name identifier (e.g., 'goSwordman', '1020100'). For onUserEnter scripts, matches the script name in WZ data. For onFirstUserEnter scripts, typically the map ID.",
			},
			Description: simpleProp{
				Type:        "string",
				Description: "Human-readable description of the script's purpose",
			},
			Rules: arrayRefProp{
				Type:        "array",
				Description: "Rules evaluated when the map entry event fires - first matching rule wins",
				Items:       refProp{Ref: "#/definitions/rule"},
			},
		},
		Definitions: definitionsBlock{
			Rule: ruleDef{
				Type:        "object",
				Description: "A single rule with conditions and operations",
				Required:    []string{"id", "conditions", "operations"},
				Properties: ruleProperties{
					Id: simpleProp{
						Type:        "string",
						Description: "Unique identifier for the rule within this script",
					},
					Conditions: arrayRefProp{
						Type:        "array",
						Description: "Conditions that must ALL be true for this rule to match (AND logic). Empty array = always matches.",
						Items:       refProp{Ref: "#/definitions/condition"},
					},
					Operations: arrayRefProp{
						Type:        "array",
						Description: "Operations to execute when this rule matches",
						Items:       refProp{Ref: "#/definitions/operation"},
					},
				},
			},
			Condition: conditionDef{
				Type:        "object",
				Description: "A condition to evaluate",
				Required:    []string{"type", "operator", "value"},
				Properties: conditionProperties{
					Type: enumProp{
						Type:        "string",
						Description: "Type of condition",
						Enum:        conditionTypes,
					},
					Operator: enumProp{
						Type:        "string",
						Description: "Comparison operator",
						Enum:        operators,
					},
					Value: simpleProp{
						Type:        "string",
						Description: "Value to compare against",
					},
					ReferenceId: simpleProp{
						Type:        "string",
						Description: "Reference identifier (e.g., quest ID for quest_status conditions)",
					},
					ValueString: simpleProp{
						Type:        "string",
						Description: "Substring to test for in the stored areaInfo string (areaInfo conditions only)",
					},
				},
			},
			Operation: operationDef{
				Type:        "object",
				Description: "An operation to execute",
				Required:    []string{"type"},
				Properties: operationProperties{
					Type: enumProp{
						Type:        "string",
						Description: "Type of operation",
						Enum:        operations,
					},
					Params: paramsProp{
						Type:                 "object",
						Description:          "Parameters for the operation",
						AdditionalProperties: additionalProps{Type: "string"},
					},
				},
				AllOf: allOf,
			},
		},
	}

	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(doc); err != nil {
		return nil, fmt.Errorf("marshaling schema failed: %w", err)
	}
	// json.Encoder.Encode always appends its own trailing newline; the
	// checked-in file wants exactly one.
	return buf.Bytes(), nil
}
