apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-tenants
  namespace: atlas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: atlas-tenants
  template:
    metadata:
      labels:
        app: atlas-tenants
    spec:
      containers:
        - name: atlas-tenants
          image: ghcr.io/chronicle20/atlas-tenants/atlas-tenants:latest
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: atlas-env
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: DB_NAME
              value: "atlas-tenants"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: atlas-tenants
  namespace: atlas
spec:
  selector:
    app: atlas-tenants
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
