package character

import (
	"net/url"
	"strconv"
	"testing"

	"github.com/Chronicle20/atlas/libs/atlas-wz/manifest"
)

// TestLoadoutHashDeterministic verifies the same canonical inputs produce
// the same hash regardless of items-list ordering. The donor's existing URLs
// depend on this: a render link generated by the UI uses the sorted item set.
func TestLoadoutHashDeterministic(t *testing.T) {
	cases := []struct {
		name string
		a, b []int
	}{
		{"same-order", []int{1040002, 1060002}, []int{1040002, 1060002}},
		{"reversed", []int{1040002, 1060002}, []int{1060002, 1040002}},
		{"empty", nil, []int{}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			h1 := LoadoutHash(CanonicalLoadoutString("T", "GMS", 83, 1, 0, 30000, 20000, "stand1", 0, 2, tc.a))
			h2 := LoadoutHash(CanonicalLoadoutString("T", "GMS", 83, 1, 0, 30000, 20000, "stand1", 0, 2, tc.b))
			if h1 != h2 {
				t.Fatalf("hashes differ: %s vs %s", h1, h2)
			}
		})
	}
}

func TestLoadoutHashLength(t *testing.T) {
	h := LoadoutHash(CanonicalLoadoutString("T", "GMS", 83, 1, 0, 30000, 20000, "stand1", 0, 2, nil))
	if len(h) != 16 {
		t.Fatalf("hash length = %d; want 16", len(h))
	}
}

func TestParseRenderQueryDefaults(t *testing.T) {
	q := url.Values{}
	q.Set("skin", "0")
	q.Set("hair", "30000")
	q.Set("face", "20000")
	rq, err := ParseRenderQuery(q)
	if err != nil {
		t.Fatalf("ParseRenderQuery: %v", err)
	}
	if rq.Stance != "stand1" {
		t.Errorf("default stance = %q; want stand1", rq.Stance)
	}
	if rq.Frame != 0 {
		t.Errorf("default frame = %d; want 0", rq.Frame)
	}
	if rq.Resize != 2 {
		t.Errorf("default resize = %d; want 2", rq.Resize)
	}
}

func TestParseRenderQueryRejectsMalformed(t *testing.T) {
	tests := []struct {
		name string
		q    url.Values
	}{
		{"missing-skin", url.Values{"hair": {"1"}, "face": {"1"}}},
		{"missing-hair", url.Values{"skin": {"0"}, "face": {"1"}}},
		{"missing-face", url.Values{"skin": {"0"}, "hair": {"1"}}},
		{"bad-frame", url.Values{"skin": {"0"}, "hair": {"1"}, "face": {"1"}, "frame": {"-1"}}},
		{"bad-resize", url.Values{"skin": {"0"}, "hair": {"1"}, "face": {"1"}, "resize": {"5"}}},
		{"bad-items", url.Values{"skin": {"0"}, "hair": {"1"}, "face": {"1"}, "items": {"abc"}}},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := ParseRenderQuery(tc.q); err == nil {
				t.Fatalf("expected error for %s", tc.name)
			}
		})
	}
}

func TestParseRenderQueryItemsCSV(t *testing.T) {
	q := url.Values{}
	q.Set("skin", "0")
	q.Set("hair", "30000")
	q.Set("face", "20000")
	q.Set("items", "1040002, 1060002 ,  ,1302000")
	rq, err := ParseRenderQuery(q)
	if err != nil {
		t.Fatalf("ParseRenderQuery: %v", err)
	}
	want := []int{1040002, 1060002, 1302000}
	if len(rq.Items) != len(want) {
		t.Fatalf("items len = %d; want %d", len(rq.Items), len(want))
	}
	for i := range want {
		if rq.Items[i] != want[i] {
			t.Errorf("items[%d] = %d; want %d", i, rq.Items[i], want[i])
		}
	}
}

func TestPartClassFor(t *testing.T) {
	cases := []struct {
		id       int
		expectPC string
		expectOk bool
	}{
		{1002000, "Cap", true},
		{1012000, "FaceAccessory", true},
		{1022000, "EyeAccessory", true},
		{1032000, "Earrings", true},
		{1042000, "Coat", true},
		{1052000, "Longcoat", true},
		{1062000, "Pants", true},
		{1072000, "Shoes", true},
		{1082000, "Glove", true},
		{1092000, "Shield", true},
		{1102000, "Cape", true},
		{1142000, "Cape", true},
		{1302000, "Weapon", true},
		{1492000, "Weapon", true},
		{0, "", false},
		{2000000, "", false}, // hair/face go through the dedicated query slots
	}
	for _, tc := range cases {
		t.Run(strconv.Itoa(tc.id), func(t *testing.T) {
			pc, ok := partClassFor(tc.id)
			if ok != tc.expectOk || pc != tc.expectPC {
				t.Fatalf("partClassFor(%d) = (%q, %v); want (%q, %v)", tc.id, pc, ok, tc.expectPC, tc.expectOk)
			}
		})
	}
}

func TestItemsToSlotMapDropsUnknown(t *testing.T) {
	got := ItemsToSlotMap([]int{1040002, 1060002, 9999999})
	if _, ok := got[-5]; !ok {
		t.Errorf("expected coat slot -5")
	}
	if _, ok := got[-6]; !ok {
		t.Errorf("expected pants slot -6")
	}
	if len(got) != 2 {
		t.Errorf("unknown id should be dropped; got %d entries", len(got))
	}
}

func TestFilterEquipmentDropsPetAndMount(t *testing.T) {
	in := map[int]int{-5: 1040002, -14: 5000000, -18: 1902000, -101: 1042001}
	out := FilterEquipment(in)
	if _, ok := out[-14]; ok {
		t.Error("pet slot -14 should be filtered")
	}
	if _, ok := out[-18]; ok {
		t.Error("mount slot -18 should be filtered")
	}
	if _, ok := out[-101]; ok {
		t.Error("cash slot -101 should be filtered")
	}
	if out[-5] != 1040002 {
		t.Error("equipment slot -5 should survive")
	}
}

func TestValidateStance(t *testing.T) {
	for _, ok := range []string{"stand1", "stand2", "walk1", "alert", "jump"} {
		if err := ValidateStance(ok); err != nil {
			t.Errorf("ValidateStance(%q) returned %v; want nil", ok, err)
		}
	}
	if err := ValidateStance("not-a-stance"); err == nil {
		t.Error("ValidateStance accepted invalid input")
	}
}

func TestMapInternalSkin(t *testing.T) {
	skin, err := MapInternalSkin(0)
	if err != nil || skin != 2000 {
		t.Errorf("MapInternalSkin(0) = (%d, %v); want (2000, nil)", skin, err)
	}
	if _, err := MapInternalSkin(99); err == nil {
		t.Error("MapInternalSkin(99) accepted out-of-range input")
	}
}

func TestPickSprite(t *testing.T) {
	m := manifest.Manifest{
		Sprites: []manifest.Sprite{
			{Stance: "stand1", Frame: 0, Part: "body"},
			{Stance: "stand1", Frame: 0, Part: "arm"},
			{Stance: "stand2", Frame: 0, Part: "body"},
		},
	}
	got := pickSprite(m, "stand1", 0, "arm")
	if got == nil || got.Part != "arm" || got.Stance != "stand1" {
		t.Fatalf("pickSprite returned %+v", got)
	}
	if got := pickSprite(m, "walk1", 0, "body"); got != nil {
		t.Fatalf("pickSprite expected nil for missing stance, got %+v", got)
	}
}

func TestAtlasHasFrame(t *testing.T) {
	m := manifest.Manifest{Sprites: []manifest.Sprite{{Stance: "stand1", Frame: 0}}}
	if !atlasHasFrame(m, "stand1", 0) {
		t.Error("atlasHasFrame should match (stand1, 0)")
	}
	if atlasHasFrame(m, "stand2", 0) {
		t.Error("atlasHasFrame should not match (stand2, 0)")
	}
}

func TestResolveTemplateStanceFallback(t *testing.T) {
	m := manifest.Manifest{Sprites: []manifest.Sprite{{Stance: "default", Frame: 0}}}
	rs, rf := resolveTemplateStance(m, "stand1", 3)
	if rs != "default" || rf != 0 {
		t.Errorf("resolveTemplateStance fell back to %s/%d; want default/0", rs, rf)
	}
}

func TestResolveTemplateStanceExact(t *testing.T) {
	m := manifest.Manifest{Sprites: []manifest.Sprite{{Stance: "stand1", Frame: 3}}}
	rs, rf := resolveTemplateStance(m, "stand1", 3)
	if rs != "stand1" || rf != 3 {
		t.Errorf("resolveTemplateStance changed exact match to %s/%d", rs, rf)
	}
}

func TestSolveViaSharedJointMatch(t *testing.T) {
	parent := placement{
		sprite: manifest.Sprite{
			Anchors: map[string]manifest.Point{"neck": {X: 4, Y: 2}},
		},
		anchor: anchorPoint{X: 48, Y: 100},
	}
	child := manifest.Sprite{
		Anchors: map[string]manifest.Point{"neck": {X: 1, Y: 9}},
	}
	got, ok := solveViaSharedJoint([]placement{parent}, child)
	if !ok {
		t.Fatal("expected match")
	}
	// 48 + 4 - 1 = 51 ; 100 + 2 - 9 = 93
	if got.X != 51 || got.Y != 93 {
		t.Errorf("anchor = (%d, %d); want (51, 93)", got.X, got.Y)
	}
}

func TestSolveViaSharedJointNoMatch(t *testing.T) {
	parent := placement{
		sprite: manifest.Sprite{Anchors: map[string]manifest.Point{"hand": {X: 0, Y: 0}}},
	}
	child := manifest.Sprite{
		Anchors: map[string]manifest.Point{"neck": {X: 0, Y: 0}},
	}
	if _, ok := solveViaSharedJoint([]placement{parent}, child); ok {
		t.Error("expected no match for disjoint joint names")
	}
}

func TestIsTwoHandedItem(t *testing.T) {
	for _, id := range []int{1402000, 1442000, 1452000, 1492000} {
		if !isTwoHandedItem(id) {
			t.Errorf("expected %d two-handed", id)
		}
	}
	for _, id := range []int{1302000, 1322000, 1100000} {
		if isTwoHandedItem(id) {
			t.Errorf("expected %d not two-handed", id)
		}
	}
}
