---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-saga-orchestrator
  namespace: atlas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlas-saga-orchestrator
  template:
    metadata:
      labels:
        app: atlas-saga-orchestrator
    spec:
      containers:
      - name: guilds
        image: ghcr.io/chronicle20/atlas-saga-orchestrator/atlas-saga-orchestrator
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: atlas-env
        env:
        - name: LOG_LEVEL
          value: "debug"
---
apiVersion: v1
kind: Service
metadata:
  name: atlas-saga-orchestrator
  namespace: atlas
spec:
  selector:
    app: atlas-saga-orchestrator
  ports:
  - protocol: TCP
    port: 8080