---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-fame
  namespace: atlas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlas-fame
  template:
    metadata:
      labels:
        app: atlas-fame
    spec:
      containers:
      - name: fame
        image: ghcr.io/chronicle20/atlas-fame/atlas-fame:latest
        envFrom:
        - configMapRef:
            name: atlas-env
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: DB_NAME
          value: "atlas-fame"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD