// Code generated by gen; DO NOT EDIT.

package constants

import (
	"github.com/Chronicle20/atlas/libs/atlas-constants/job"
	"github.com/Chronicle20/atlas/libs/atlas-constants/skill"
)

// versionKey identifies one provisioned (region, major, minor) tenant
// version column in registry below (task-187 Task 6). region is always
// upper-cased -- For upper-cases its input region before lookup, so the
// registry's keys are upper-cased too.
type versionKey struct {
	region       string
	major, minor uint16
}

// registry is every provisioned tenant version's SkillJobSet, built from
// the skill/job packages' per-version generated NewSet<PascalVersion>
// constructors (task-187 Tasks 2-5). constants.For looks a requested
// (region,major,minor) tuple up here, falling back to baseline on a miss.
var registry = map[versionKey]SkillJobSet{
	{"GMS", 12, 1}:  {Skill: skill.NewSetGMS121(), Job: job.NewSetGMS121()},
	{"GMS", 48, 1}:  {Skill: skill.NewSetGMS481(), Job: job.NewSetGMS481()},
	{"GMS", 61, 1}:  {Skill: skill.NewSetGMS611(), Job: job.NewSetGMS611()},
	{"GMS", 72, 1}:  {Skill: skill.NewSetGMS721(), Job: job.NewSetGMS721()},
	{"GMS", 79, 1}:  {Skill: skill.NewSetGMS791(), Job: job.NewSetGMS791()},
	{"GMS", 83, 1}:  {Skill: skill.NewSetGMS831(), Job: job.NewSetGMS831()},
	{"GMS", 84, 1}:  {Skill: skill.NewSetGMS841(), Job: job.NewSetGMS841()},
	{"GMS", 87, 1}:  {Skill: skill.NewSetGMS871(), Job: job.NewSetGMS871()},
	{"GMS", 92, 1}:  {Skill: skill.NewSetGMS921(), Job: job.NewSetGMS921()},
	{"GMS", 95, 1}:  {Skill: skill.NewSetGMS951(), Job: job.NewSetGMS951()},
	{"JMS", 185, 1}: {Skill: skill.NewSetJMS1851(), Job: job.NewSetJMS1851()},
}

// baseline is the canonical fallback SkillJobSet (GMS 83.1) constants.For
// returns for an unprovisioned (region,major,minor) tuple.
var baseline = SkillJobSet{Skill: skill.Baseline(), Job: job.Baseline()}
