// Code generated by gen; DO NOT EDIT.

package job

// Baseline returns the canonical fallback identity Set (GMS 83.1),
// generated by newSet_gms_83_1 (task-187 Tasks 2-5). constants.For
// (task-187 Task 6) returns this when the requested (region,major,minor)
// tuple is not a provisioned registry key.
func Baseline() Set {
	return newSet_gms_83_1()
}
