// Code generated by gen; DO NOT EDIT.

package job

const (
	Beginner                 Identity = 0
	Warrior                  Identity = 100
	Fighter                  Identity = 110
	Crusader                 Identity = 111
	Hero                     Identity = 112
	Page                     Identity = 120
	WhiteKnight              Identity = 121
	Paladin                  Identity = 122
	Spearman                 Identity = 130
	DragonKnight             Identity = 131
	DarkKnight               Identity = 132
	Magician                 Identity = 200
	FirePoisonWizard         Identity = 210
	FirePoisonMagician       Identity = 211
	FirePoisonArchMagician   Identity = 212
	IceLightningWizard       Identity = 220
	IceLightningMagician     Identity = 221
	IceLightningArchMagician Identity = 222
	Cleric                   Identity = 230
	Priest                   Identity = 231
	Bishop                   Identity = 232
	Bowman                   Identity = 300
	Hunter                   Identity = 310
	Ranger                   Identity = 311
	Bowmaster                Identity = 312
	Crossbowman              Identity = 320
	Sniper                   Identity = 321
	Marksman                 Identity = 322
	Rogue                    Identity = 400
	Assassin                 Identity = 410
	Hermit                   Identity = 411
	NightLord                Identity = 412
	Bandit                   Identity = 420
	ChiefBandit              Identity = 421
	Shadower                 Identity = 422
	BladeRecruit             Identity = 430
	BladeAcolyte             Identity = 431
	BladeSpecialist          Identity = 432
	BladeLord                Identity = 433
	BladeMaster              Identity = 434
	Pirate                   Identity = 500
	Brawler                  Identity = 510
	Marauder                 Identity = 511
	Buccaneer                Identity = 512
	Gunslinger               Identity = 520
	Outlaw                   Identity = 521
	Corsair                  Identity = 522
	MapleLeafBrigadier       Identity = 800
	Gm                       Identity = 900
	SuperGm                  Identity = 910
	Noblesse                 Identity = 1000
	DawnWarriorStage1        Identity = 1100
	DawnWarriorStage2        Identity = 1110
	DawnWarriorStage3        Identity = 1111
	DawnWarriorStage4        Identity = 1112
	BlazeWizardStage1        Identity = 1200
	BlazeWizardStage2        Identity = 1210
	BlazeWizardStage3        Identity = 1211
	BlazeWizardStage4        Identity = 1212
	WindArcherStage1         Identity = 1300
	WindArcherStage2         Identity = 1310
	WindArcherStage3         Identity = 1311
	WindArcherStage4         Identity = 1312
	NightWalkerStage1        Identity = 1400
	NightWalkerStage2        Identity = 1410
	NightWalkerStage3        Identity = 1411
	NightWalkerStage4        Identity = 1412
	ThunderBreakerStage1     Identity = 1500
	ThunderBreakerStage2     Identity = 1510
	ThunderBreakerStage3     Identity = 1511
	ThunderBreakerStage4     Identity = 1512
	Legend                   Identity = 2000
	Evan                     Identity = 2001
	AranStage1               Identity = 2100
	AranStage2               Identity = 2110
	AranStage3               Identity = 2111
	AranStage4               Identity = 2112
	EvanStage1               Identity = 2200
	EvanStage2               Identity = 2210
	EvanStage3               Identity = 2211
	EvanStage4               Identity = 2212
	EvanStage5               Identity = 2213
	EvanStage6               Identity = 2214
	EvanStage7               Identity = 2215
	EvanStage8               Identity = 2216
	EvanStage9               Identity = 2217
	EvanStage10              Identity = 2218
)

var identityNames = map[Identity]string{
	Beginner:                 "Beginner",
	Warrior:                  "Warrior",
	Fighter:                  "Fighter",
	Crusader:                 "Crusader",
	Hero:                     "Hero",
	Page:                     "Page",
	WhiteKnight:              "White Knight",
	Paladin:                  "Paladin",
	Spearman:                 "Spearman",
	DragonKnight:             "Dragon Knight",
	DarkKnight:               "Dark Knight",
	Magician:                 "Magician",
	FirePoisonWizard:         "Fire Poison Wizard",
	FirePoisonMagician:       "Fire Poison Magician",
	FirePoisonArchMagician:   "Fire Poison Arch Magician",
	IceLightningWizard:       "Ice Lightning Wizard",
	IceLightningMagician:     "Ice Lightning Magician",
	IceLightningArchMagician: "Ice Lightning Arch Magician",
	Cleric:                   "Cleric",
	Priest:                   "Priest",
	Bishop:                   "Bishop",
	Bowman:                   "Bowman",
	Hunter:                   "Hunter",
	Ranger:                   "Ranger",
	Bowmaster:                "Bowmaster",
	Crossbowman:              "Crossbowman",
	Sniper:                   "Sniper",
	Marksman:                 "Marksman",
	Rogue:                    "Rogue",
	Assassin:                 "Assassin",
	Hermit:                   "Hermit",
	NightLord:                "Night Lord",
	Bandit:                   "Bandit",
	ChiefBandit:              "Chief Bandit",
	Shadower:                 "Shadower",
	BladeRecruit:             "Blade Recruit",
	BladeAcolyte:             "Blade Acolyte",
	BladeSpecialist:          "Blade Specialist",
	BladeLord:                "Blade Lord",
	BladeMaster:              "Blade Master",
	Pirate:                   "Pirate",
	Brawler:                  "Brawler",
	Marauder:                 "Marauder",
	Buccaneer:                "Buccaneer",
	Gunslinger:               "Gunslinger",
	Outlaw:                   "Outlaw",
	Corsair:                  "Corsair",
	MapleLeafBrigadier:       "Maple Leaf Brigadier",
	Gm:                       "Gm",
	SuperGm:                  "Super Gm",
	Noblesse:                 "Noblesse",
	DawnWarriorStage1:        "Dawn Warrior Stage1",
	DawnWarriorStage2:        "Dawn Warrior Stage2",
	DawnWarriorStage3:        "Dawn Warrior Stage3",
	DawnWarriorStage4:        "Dawn Warrior Stage4",
	BlazeWizardStage1:        "Blaze Wizard Stage1",
	BlazeWizardStage2:        "Blaze Wizard Stage2",
	BlazeWizardStage3:        "Blaze Wizard Stage3",
	BlazeWizardStage4:        "Blaze Wizard Stage4",
	WindArcherStage1:         "Wind Archer Stage1",
	WindArcherStage2:         "Wind Archer Stage2",
	WindArcherStage3:         "Wind Archer Stage3",
	WindArcherStage4:         "Wind Archer Stage4",
	NightWalkerStage1:        "Night Walker Stage1",
	NightWalkerStage2:        "Night Walker Stage2",
	NightWalkerStage3:        "Night Walker Stage3",
	NightWalkerStage4:        "Night Walker Stage4",
	ThunderBreakerStage1:     "Thunder Breaker Stage1",
	ThunderBreakerStage2:     "Thunder Breaker Stage2",
	ThunderBreakerStage3:     "Thunder Breaker Stage3",
	ThunderBreakerStage4:     "Thunder Breaker Stage4",
	Legend:                   "Legend",
	Evan:                     "Evan",
	AranStage1:               "Aran Stage1",
	AranStage2:               "Aran Stage2",
	AranStage3:               "Aran Stage3",
	AranStage4:               "Aran Stage4",
	EvanStage1:               "Evan Stage1",
	EvanStage2:               "Evan Stage2",
	EvanStage3:               "Evan Stage3",
	EvanStage4:               "Evan Stage4",
	EvanStage5:               "Evan Stage5",
	EvanStage6:               "Evan Stage6",
	EvanStage7:               "Evan Stage7",
	EvanStage8:               "Evan Stage8",
	EvanStage9:               "Evan Stage9",
	EvanStage10:              "Evan Stage10",
}
