package tenants

import (
	"atlas-configurations/data"
	"atlas-configurations/data/mock"
	"atlas-configurations/tenants/characters"
	"atlas-configurations/tenants/characters/preset"
	"context"
	"encoding/json"
	"errors"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/sirupsen/logrus"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

// testEntity is a SQLite-compatible version of Entity for testing
type testEntity struct {
	Id           uuid.UUID       `gorm:"type:text;primaryKey"`
	Region       string          `gorm:"not null"`
	MajorVersion uint16          `gorm:"not null"`
	MinorVersion uint16          `gorm:"not null"`
	Data         json.RawMessage `gorm:"type:text;not null"`
}

func (testEntity) TableName() string {
	return "tenants"
}

// testHistoryEntity is a SQLite-compatible version of HistoryEntity for testing
type testHistoryEntity struct {
	Id        uuid.UUID       `gorm:"type:text;primaryKey"`
	TenantId  uuid.UUID       `gorm:"type:text"`
	Data      json.RawMessage `gorm:"type:text;not null"`
	CreatedAt time.Time       `gorm:"not null"`
}

func (testHistoryEntity) TableName() string {
	return "tenant_history"
}

func setupTestDB(t *testing.T) *gorm.DB {
	db, err := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{
		Logger: logger.Default.LogMode(logger.Silent),
	})
	if err != nil {
		t.Fatalf("failed to connect database: %v", err)
	}

	// Use SQLite-compatible schema
	err = db.AutoMigrate(&testEntity{}, &testHistoryEntity{})
	if err != nil {
		t.Fatalf("failed to migrate: %v", err)
	}

	return db
}

func testLogger() logrus.FieldLogger {
	l := logrus.New()
	l.SetLevel(logrus.ErrorLevel)
	return l
}

func createTestRestModel(region string, majorVersion, minorVersion uint16) RestModel {
	return RestModel{
		Region:       region,
		MajorVersion: majorVersion,
		MinorVersion: minorVersion,
		UsesPin:      true,
	}
}

func TestProcessor_GetAll_Empty(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	results, err := p.GetAll()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(results) != 0 {
		t.Errorf("expected 0 results, got %d", len(results))
	}
}

func TestProcessor_GetAll_WithData(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	// Create test data
	input1 := createTestRestModel("GMS", 83, 1)
	input2 := createTestRestModel("SEA", 83, 2)

	_, err := p.Create(input1)
	if err != nil {
		t.Fatalf("failed to create first tenant: %v", err)
	}

	_, err = p.Create(input2)
	if err != nil {
		t.Fatalf("failed to create second tenant: %v", err)
	}

	results, err := p.GetAll()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(results) != 2 {
		t.Errorf("expected 2 results, got %d", len(results))
	}
}

func TestProcessor_Create_AutoGeneratedID(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	input := createTestRestModel("GMS", 83, 1)

	id, err := p.Create(input)
	if err != nil {
		t.Fatalf("failed to create tenant: %v", err)
	}

	if id == uuid.Nil {
		t.Error("expected non-nil UUID")
	}

	// Verify it was created
	result, err := p.GetById(id)
	if err != nil {
		t.Fatalf("failed to get created tenant: %v", err)
	}

	if result.Region != input.Region {
		t.Errorf("expected region '%s', got '%s'", input.Region, result.Region)
	}
	if result.MajorVersion != input.MajorVersion {
		t.Errorf("expected majorVersion %d, got %d", input.MajorVersion, result.MajorVersion)
	}
	if result.MinorVersion != input.MinorVersion {
		t.Errorf("expected minorVersion %d, got %d", input.MinorVersion, result.MinorVersion)
	}
}

func TestProcessor_Create_ProvidedID(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	providedID := uuid.New()
	input := createTestRestModel("GMS", 83, 1)
	input.Id = providedID.String()

	id, err := p.Create(input)
	if err != nil {
		t.Fatalf("failed to create tenant: %v", err)
	}

	if id != providedID {
		t.Errorf("expected ID '%s', got '%s'", providedID.String(), id.String())
	}

	// Verify it was created with provided ID
	result, err := p.GetById(providedID)
	if err != nil {
		t.Fatalf("failed to get created tenant: %v", err)
	}

	if result.Id != providedID.String() {
		t.Errorf("expected id '%s', got '%s'", providedID.String(), result.Id)
	}
}

func TestProcessor_Create_InvalidID(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	input := createTestRestModel("GMS", 83, 1)
	input.Id = "not-a-valid-uuid"

	_, err := p.Create(input)
	if err == nil {
		t.Error("expected error for invalid UUID")
	}
}

func TestProcessor_GetById(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	input := createTestRestModel("GMS", 83, 1)
	id, err := p.Create(input)
	if err != nil {
		t.Fatalf("failed to create tenant: %v", err)
	}

	result, err := p.GetById(id)
	if err != nil {
		t.Fatalf("failed to get tenant: %v", err)
	}

	if result.Id != id.String() {
		t.Errorf("expected id '%s', got '%s'", id.String(), result.Id)
	}
	if result.Region != input.Region {
		t.Errorf("expected region '%s', got '%s'", input.Region, result.Region)
	}
}

func TestProcessor_GetById_NotFound(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	nonExistentId := uuid.New()
	_, err := p.GetById(nonExistentId)
	if err == nil {
		t.Error("expected error for non-existent tenant")
	}
}

func TestProcessor_GetByRegionAndVersion(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	input := createTestRestModel("GMS", 83, 1)
	_, err := p.Create(input)
	if err != nil {
		t.Fatalf("failed to create tenant: %v", err)
	}

	result, err := p.GetByRegionAndVersion("GMS", 83, 1)
	if err != nil {
		t.Fatalf("failed to get tenant by region/version: %v", err)
	}

	if result.Region != "GMS" {
		t.Errorf("expected region 'GMS', got '%s'", result.Region)
	}
	if result.MajorVersion != 83 {
		t.Errorf("expected majorVersion 83, got %d", result.MajorVersion)
	}
	if result.MinorVersion != 1 {
		t.Errorf("expected minorVersion 1, got %d", result.MinorVersion)
	}
}

func TestProcessor_GetByRegionAndVersion_NotFound(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	_, err := p.GetByRegionAndVersion("NONEXISTENT", 99, 99)
	if err == nil {
		t.Error("expected error for non-existent region/version")
	}
}

func TestProcessor_UpdateById(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	// Create initial tenant
	input := createTestRestModel("GMS", 83, 1)
	id, err := p.Create(input)
	if err != nil {
		t.Fatalf("failed to create tenant: %v", err)
	}

	// Update the tenant
	updated := createTestRestModel("SEA", 84, 2)
	updated.UsesPin = false
	err = p.UpdateById(id, updated)
	if err != nil {
		t.Fatalf("failed to update tenant: %v", err)
	}

	// Verify the update
	result, err := p.GetById(id)
	if err != nil {
		t.Fatalf("failed to get updated tenant: %v", err)
	}

	if result.Region != updated.Region {
		t.Errorf("expected region '%s', got '%s'", updated.Region, result.Region)
	}
	if result.MajorVersion != updated.MajorVersion {
		t.Errorf("expected majorVersion %d, got %d", updated.MajorVersion, result.MajorVersion)
	}
	if result.UsesPin != updated.UsesPin {
		t.Errorf("expected usesPin %v, got %v", updated.UsesPin, result.UsesPin)
	}
}

func TestProcessor_UpdateById_CreatesHistory(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	// Create initial tenant
	input := createTestRestModel("GMS", 83, 1)
	id, err := p.Create(input)
	if err != nil {
		t.Fatalf("failed to create tenant: %v", err)
	}

	// Update the tenant
	updated := createTestRestModel("SEA", 84, 2)
	err = p.UpdateById(id, updated)
	if err != nil {
		t.Fatalf("failed to update tenant: %v", err)
	}

	// Verify history was created
	var historyCount int64
	err = db.Model(&HistoryEntity{}).Where("tenant_id = ?", id).Count(&historyCount).Error
	if err != nil {
		t.Fatalf("failed to count history: %v", err)
	}

	if historyCount != 1 {
		t.Errorf("expected 1 history record, got %d", historyCount)
	}
}

func TestProcessor_UpdateById_NotFound(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	nonExistentId := uuid.New()
	input := createTestRestModel("GMS", 83, 1)
	err := p.UpdateById(nonExistentId, input)
	if err == nil {
		t.Error("expected error for non-existent tenant")
	}
}

func TestProcessor_DeleteById(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	// Create a tenant
	input := createTestRestModel("GMS", 83, 1)
	id, err := p.Create(input)
	if err != nil {
		t.Fatalf("failed to create tenant: %v", err)
	}

	// Verify it exists
	_, err = p.GetById(id)
	if err != nil {
		t.Fatalf("tenant should exist before delete: %v", err)
	}

	// Delete it
	err = p.DeleteById(id)
	if err != nil {
		t.Fatalf("failed to delete tenant: %v", err)
	}

	// Verify it's gone
	_, err = p.GetById(id)
	if err == nil {
		t.Error("expected error for deleted tenant")
	}
}

func TestProcessor_DeleteById_CreatesHistory(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	// Create a tenant
	input := createTestRestModel("GMS", 83, 1)
	id, err := p.Create(input)
	if err != nil {
		t.Fatalf("failed to create tenant: %v", err)
	}

	// Delete it
	err = p.DeleteById(id)
	if err != nil {
		t.Fatalf("failed to delete tenant: %v", err)
	}

	// Verify history was created
	var historyCount int64
	err = db.Model(&HistoryEntity{}).Where("tenant_id = ?", id).Count(&historyCount).Error
	if err != nil {
		t.Fatalf("failed to count history: %v", err)
	}

	if historyCount != 1 {
		t.Errorf("expected 1 history record from delete, got %d", historyCount)
	}
}

func TestProcessor_DeleteById_NotFound(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	nonExistentId := uuid.New()
	err := p.DeleteById(nonExistentId)
	if err == nil {
		t.Error("expected error for non-existent tenant")
	}
}

func TestMake(t *testing.T) {
	testId := uuid.New()
	testData := RestModel{
		Region:       "GMS",
		MajorVersion: 83,
		MinorVersion: 1,
		UsesPin:      true,
	}
	jsonData, err := json.Marshal(testData)
	if err != nil {
		t.Fatalf("failed to marshal test data: %v", err)
	}

	entity := Entity{
		Id:           testId,
		Region:       "GMS",
		MajorVersion: 83,
		MinorVersion: 1,
		Data:         jsonData,
	}

	result, err := Make(entity)
	if err != nil {
		t.Fatalf("Make failed: %v", err)
	}

	if result.Id != testId.String() {
		t.Errorf("expected id '%s', got '%s'", testId.String(), result.Id)
	}
	if result.Region != testData.Region {
		t.Errorf("expected region '%s', got '%s'", testData.Region, result.Region)
	}
	if result.MajorVersion != testData.MajorVersion {
		t.Errorf("expected majorVersion %d, got %d", testData.MajorVersion, result.MajorVersion)
	}
	if result.UsesPin != testData.UsesPin {
		t.Errorf("expected usesPin %v, got %v", testData.UsesPin, result.UsesPin)
	}
}

func TestMake_InvalidJSON(t *testing.T) {
	entity := Entity{
		Id:           uuid.New(),
		Region:       "GMS",
		MajorVersion: 83,
		MinorVersion: 1,
		Data:         json.RawMessage(`{invalid json`),
	}

	_, err := Make(entity)
	if err == nil {
		t.Error("expected error for invalid JSON")
	}
}

func TestUpdateById_AssignsMissingPresetId(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()

	// Create a tenant first so the update can find a row to update
	base := createTestRestModel("GMS", 83, 1)
	id, err := NewProcessor(l, ctx, db).Create(base)
	if err != nil {
		t.Fatalf("failed to create tenant: %v", err)
	}

	fake := &mock.FakeClient{Items: map[uint32]data.ItemInfo{}, Skills: map[uint32]data.SkillInfo{}}
	p := NewProcessor(l, ctx, db).WithValidator(preset.NewValidator(fake))

	input := RestModel{
		Region:       "GMS",
		MajorVersion: 83,
		MinorVersion: 1,
		Characters: characters.RestModel{
			Presets: []preset.RestModel{{
				Id: "",
				Attributes: preset.Attributes{
					Name:  "Hero",
					Level: 1,
					JobId: 0,
				},
			}},
		},
	}

	err = p.UpdateById(id, input)
	// May fail on DB level (row mismatch) but the validator should have assigned the ID
	// and returned no errors — so the failure (if any) is from the DB layer.
	// The important assertion: preset ID was assigned before returning.
	if input.Characters.Presets[0].Id == "" {
		t.Fatal("expected validator to assign UUID to preset with empty id")
	}
	_ = err
}

func TestUpdateById_ReturnsValidationErrorForInvalidPreset(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()

	fake := &mock.FakeClient{Items: map[uint32]data.ItemInfo{}, Skills: map[uint32]data.SkillInfo{}}
	p := NewProcessor(l, ctx, db).WithValidator(preset.NewValidator(fake))

	input := RestModel{
		Characters: characters.RestModel{
			Presets: []preset.RestModel{{
				Id: "abc",
				Attributes: preset.Attributes{
					Name:  "",    // R-1 violation
					JobId: 99999, // R-3 violation
					Level: 0,     // R-5 violation
				},
			}},
		},
	}

	err := p.UpdateById(uuid.New(), input)
	var ve *validationFailureError
	if !errors.As(err, &ve) {
		t.Fatalf("expected validationFailureError, got %v", err)
	}

	apiErrs := ve.AsJSONAPIErrors()
	if len(apiErrs) == 0 {
		t.Fatal("expected at least one JSON:API error")
	}

	// Verify structure of the first error
	if apiErrs[0].Status != "400" {
		t.Errorf("expected status '400', got '%s'", apiErrs[0].Status)
	}
	if apiErrs[0].Title != "validation failed" {
		t.Errorf("expected title 'validation failed', got '%s'", apiErrs[0].Title)
	}
	if apiErrs[0].Meta == nil {
		t.Error("expected non-nil meta")
	}
}
