package tenants

import (
	"atlas-configurations/data"
	"atlas-configurations/data/mock"
	"atlas-configurations/tenants/characters"
	"atlas-configurations/tenants/characters/preset"
	"context"
	"encoding/json"
	"errors"
	"os"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/sirupsen/logrus"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"

	env "github.com/Chronicle20/atlas/libs/atlas-env"
	outboxlib "github.com/Chronicle20/atlas/libs/atlas-outbox"

	"github.com/Chronicle20/atlas/libs/atlas-model/model"
)

// testEntity is a SQLite-compatible version of Entity for testing
type testEntity struct {
	Id           uuid.UUID       `gorm:"type:text;primaryKey"`
	Region       string          `gorm:"not null"`
	MajorVersion uint16          `gorm:"not null"`
	MinorVersion uint16          `gorm:"not null"`
	Data         json.RawMessage `gorm:"type:text;not null"`
	Environment  string          `gorm:"not null;default:''"`
}

func (testEntity) TableName() string {
	return "tenants"
}

// testHistoryEntity is a SQLite-compatible version of HistoryEntity for testing
type testHistoryEntity struct {
	Id          uuid.UUID       `gorm:"type:text;primaryKey"`
	TenantId    uuid.UUID       `gorm:"type:text"`
	Data        json.RawMessage `gorm:"type:text;not null"`
	CreatedAt   time.Time       `gorm:"not null"`
	Environment string          `gorm:"not null;default:''"`
}

func (testHistoryEntity) TableName() string {
	return "tenant_history"
}

func setupTestDB(t *testing.T) *gorm.DB {
	db, err := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{
		Logger: logger.Default.LogMode(logger.Silent),
	})
	if err != nil {
		t.Fatalf("failed to connect database: %v", err)
	}

	// Use SQLite-compatible schema
	err = db.AutoMigrate(&testEntity{}, &testHistoryEntity{})
	if err != nil {
		t.Fatalf("failed to migrate: %v", err)
	}
	if err := outboxlib.Migration(db); err != nil {
		t.Fatalf("failed to migrate outbox: %v", err)
	}

	return db
}

func testLogger() logrus.FieldLogger {
	l := logrus.New()
	l.SetLevel(logrus.ErrorLevel)
	return l
}

func createTestRestModel(region string, majorVersion, minorVersion uint16) RestModel {
	return RestModel{
		Region:       region,
		MajorVersion: majorVersion,
		MinorVersion: minorVersion,
		UsesPin:      true,
	}
}

func TestProcessor_GetAll_Empty(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	paged, err := p.AllProvider(model.Page{Number: 1, Size: 250})()
	results := paged.Items
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(results) != 0 {
		t.Errorf("expected 0 results, got %d", len(results))
	}
}

func TestProcessor_GetAll_WithData(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	// Create test data
	input1 := createTestRestModel("GMS", 83, 1)
	input2 := createTestRestModel("SEA", 83, 2)

	_, err := p.Create(input1)
	if err != nil {
		t.Fatalf("failed to create first tenant: %v", err)
	}

	_, err = p.Create(input2)
	if err != nil {
		t.Fatalf("failed to create second tenant: %v", err)
	}

	paged, err := p.AllProvider(model.Page{Number: 1, Size: 250})()
	results := paged.Items
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(results) != 2 {
		t.Errorf("expected 2 results, got %d", len(results))
	}
}

func TestProcessor_Create_AutoGeneratedID(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	input := createTestRestModel("GMS", 83, 1)

	id, err := p.Create(input)
	if err != nil {
		t.Fatalf("failed to create tenant: %v", err)
	}

	if id == uuid.Nil {
		t.Error("expected non-nil UUID")
	}

	// Verify it was created
	result, err := p.GetById(id)
	if err != nil {
		t.Fatalf("failed to get created tenant: %v", err)
	}

	if result.Region != input.Region {
		t.Errorf("expected region '%s', got '%s'", input.Region, result.Region)
	}
	if result.MajorVersion != input.MajorVersion {
		t.Errorf("expected majorVersion %d, got %d", input.MajorVersion, result.MajorVersion)
	}
	if result.MinorVersion != input.MinorVersion {
		t.Errorf("expected minorVersion %d, got %d", input.MinorVersion, result.MinorVersion)
	}
}

func TestProcessor_Create_ProvidedID(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	providedID := uuid.New()
	input := createTestRestModel("GMS", 83, 1)
	input.Id = providedID.String()

	id, err := p.Create(input)
	if err != nil {
		t.Fatalf("failed to create tenant: %v", err)
	}

	if id != providedID {
		t.Errorf("expected ID '%s', got '%s'", providedID.String(), id.String())
	}

	// Verify it was created with provided ID
	result, err := p.GetById(providedID)
	if err != nil {
		t.Fatalf("failed to get created tenant: %v", err)
	}

	if result.Id != providedID.String() {
		t.Errorf("expected id '%s', got '%s'", providedID.String(), result.Id)
	}
}

func TestProcessor_Create_InvalidID(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	input := createTestRestModel("GMS", 83, 1)
	input.Id = "not-a-valid-uuid"

	_, err := p.Create(input)
	if err == nil {
		t.Error("expected error for invalid UUID")
	}
}

func TestProcessor_GetById(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	input := createTestRestModel("GMS", 83, 1)
	id, err := p.Create(input)
	if err != nil {
		t.Fatalf("failed to create tenant: %v", err)
	}

	result, err := p.GetById(id)
	if err != nil {
		t.Fatalf("failed to get tenant: %v", err)
	}

	if result.Id != id.String() {
		t.Errorf("expected id '%s', got '%s'", id.String(), result.Id)
	}
	if result.Region != input.Region {
		t.Errorf("expected region '%s', got '%s'", input.Region, result.Region)
	}
}

func TestProcessor_GetById_NotFound(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	nonExistentId := uuid.New()
	_, err := p.GetById(nonExistentId)
	if err == nil {
		t.Error("expected error for non-existent tenant")
	}
}

func TestProcessor_GetByRegionAndVersion(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	input := createTestRestModel("GMS", 83, 1)
	_, err := p.Create(input)
	if err != nil {
		t.Fatalf("failed to create tenant: %v", err)
	}

	result, err := p.GetByRegionAndVersion("GMS", 83, 1)
	if err != nil {
		t.Fatalf("failed to get tenant by region/version: %v", err)
	}

	if result.Region != "GMS" {
		t.Errorf("expected region 'GMS', got '%s'", result.Region)
	}
	if result.MajorVersion != 83 {
		t.Errorf("expected majorVersion 83, got %d", result.MajorVersion)
	}
	if result.MinorVersion != 1 {
		t.Errorf("expected minorVersion 1, got %d", result.MinorVersion)
	}
}

func TestProcessor_GetByRegionAndVersion_NotFound(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	_, err := p.GetByRegionAndVersion("NONEXISTENT", 99, 99)
	if err == nil {
		t.Error("expected error for non-existent region/version")
	}
}

func TestProcessor_UpdateById(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	// Create initial tenant
	input := createTestRestModel("GMS", 83, 1)
	id, err := p.Create(input)
	if err != nil {
		t.Fatalf("failed to create tenant: %v", err)
	}

	// Update the tenant
	updated := createTestRestModel("SEA", 84, 2)
	updated.UsesPin = false
	err = p.UpdateById(id, updated)
	if err != nil {
		t.Fatalf("failed to update tenant: %v", err)
	}

	// Verify the update
	result, err := p.GetById(id)
	if err != nil {
		t.Fatalf("failed to get updated tenant: %v", err)
	}

	if result.Region != updated.Region {
		t.Errorf("expected region '%s', got '%s'", updated.Region, result.Region)
	}
	if result.MajorVersion != updated.MajorVersion {
		t.Errorf("expected majorVersion %d, got %d", updated.MajorVersion, result.MajorVersion)
	}
	if result.UsesPin != updated.UsesPin {
		t.Errorf("expected usesPin %v, got %v", updated.UsesPin, result.UsesPin)
	}
}

func TestProcessor_UpdateById_CreatesHistory(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	// Create initial tenant
	input := createTestRestModel("GMS", 83, 1)
	id, err := p.Create(input)
	if err != nil {
		t.Fatalf("failed to create tenant: %v", err)
	}

	// Update the tenant
	updated := createTestRestModel("SEA", 84, 2)
	err = p.UpdateById(id, updated)
	if err != nil {
		t.Fatalf("failed to update tenant: %v", err)
	}

	// Verify history was created
	var historyCount int64
	err = db.Model(&HistoryEntity{}).Where("tenant_id = ?", id).Count(&historyCount).Error
	if err != nil {
		t.Fatalf("failed to count history: %v", err)
	}

	if historyCount != 1 {
		t.Errorf("expected 1 history record, got %d", historyCount)
	}
}

func TestProcessor_UpdateById_NotFound(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	nonExistentId := uuid.New()
	input := createTestRestModel("GMS", 83, 1)
	err := p.UpdateById(nonExistentId, input)
	if err == nil {
		t.Error("expected error for non-existent tenant")
	}
}

func TestProcessor_DeleteById(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	// Create a tenant
	input := createTestRestModel("GMS", 83, 1)
	id, err := p.Create(input)
	if err != nil {
		t.Fatalf("failed to create tenant: %v", err)
	}

	// Verify it exists
	_, err = p.GetById(id)
	if err != nil {
		t.Fatalf("tenant should exist before delete: %v", err)
	}

	// Delete it
	err = p.DeleteById(id)
	if err != nil {
		t.Fatalf("failed to delete tenant: %v", err)
	}

	// Verify it's gone
	_, err = p.GetById(id)
	if err == nil {
		t.Error("expected error for deleted tenant")
	}
}

func TestProcessor_DeleteById_CreatesHistory(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	// Create a tenant
	input := createTestRestModel("GMS", 83, 1)
	id, err := p.Create(input)
	if err != nil {
		t.Fatalf("failed to create tenant: %v", err)
	}

	// Delete it
	err = p.DeleteById(id)
	if err != nil {
		t.Fatalf("failed to delete tenant: %v", err)
	}

	// Verify history was created
	var historyCount int64
	err = db.Model(&HistoryEntity{}).Where("tenant_id = ?", id).Count(&historyCount).Error
	if err != nil {
		t.Fatalf("failed to count history: %v", err)
	}

	if historyCount != 1 {
		t.Errorf("expected 1 history record from delete, got %d", historyCount)
	}
}

func TestProcessor_DeleteById_NotFound(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	nonExistentId := uuid.New()
	err := p.DeleteById(nonExistentId)
	if err == nil {
		t.Error("expected error for non-existent tenant")
	}
}

func TestMake(t *testing.T) {
	testId := uuid.New()
	testData := RestModel{
		Region:       "GMS",
		MajorVersion: 83,
		MinorVersion: 1,
		UsesPin:      true,
	}
	jsonData, err := json.Marshal(testData)
	if err != nil {
		t.Fatalf("failed to marshal test data: %v", err)
	}

	entity := Entity{
		Id:           testId,
		Region:       "GMS",
		MajorVersion: 83,
		MinorVersion: 1,
		Data:         jsonData,
	}

	result, err := Make(entity)
	if err != nil {
		t.Fatalf("Make failed: %v", err)
	}

	if result.Id != testId.String() {
		t.Errorf("expected id '%s', got '%s'", testId.String(), result.Id)
	}
	if result.Region != testData.Region {
		t.Errorf("expected region '%s', got '%s'", testData.Region, result.Region)
	}
	if result.MajorVersion != testData.MajorVersion {
		t.Errorf("expected majorVersion %d, got %d", testData.MajorVersion, result.MajorVersion)
	}
	if result.UsesPin != testData.UsesPin {
		t.Errorf("expected usesPin %v, got %v", testData.UsesPin, result.UsesPin)
	}
}

func TestMake_InvalidJSON(t *testing.T) {
	entity := Entity{
		Id:           uuid.New(),
		Region:       "GMS",
		MajorVersion: 83,
		MinorVersion: 1,
		Data:         json.RawMessage(`{invalid json`),
	}

	_, err := Make(entity)
	if err == nil {
		t.Error("expected error for invalid JSON")
	}
}

func TestUpdateById_AssignsMissingPresetId(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()

	// Create a tenant first so the update can find a row to update
	base := createTestRestModel("GMS", 83, 1)
	id, err := NewProcessor(l, ctx, db).Create(base)
	if err != nil {
		t.Fatalf("failed to create tenant: %v", err)
	}

	fake := &mock.ProcessorMock{Items: map[uint32]data.ItemInfo{}, Skills: map[uint32]data.SkillInfo{}}
	p := NewProcessor(l, ctx, db).WithValidator(preset.NewValidator(fake))

	input := RestModel{
		Region:       "GMS",
		MajorVersion: 83,
		MinorVersion: 1,
		Characters: characters.RestModel{
			Presets: []preset.RestModel{{
				Id: "",
				Attributes: preset.Attributes{
					Name:  "Hero",
					Level: 1,
					JobId: 0,
				},
			}},
		},
	}

	err = p.UpdateById(id, input)
	// May fail on DB level (row mismatch) but the validator should have assigned the ID
	// and returned no errors — so the failure (if any) is from the DB layer.
	// The important assertion: preset ID was assigned before returning.
	if input.Characters.Presets[0].Id == "" {
		t.Fatal("expected validator to assign UUID to preset with empty id")
	}
	_ = err
}

func TestUpdateById_ReturnsValidationErrorForInvalidPreset(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()

	fake := &mock.ProcessorMock{Items: map[uint32]data.ItemInfo{}, Skills: map[uint32]data.SkillInfo{}}
	p := NewProcessor(l, ctx, db).WithValidator(preset.NewValidator(fake))

	input := RestModel{
		Characters: characters.RestModel{
			Presets: []preset.RestModel{{
				Id: "abc",
				Attributes: preset.Attributes{
					Name:  "",    // R-1 violation
					JobId: 99999, // R-3 violation
					Level: 0,     // R-5 violation
				},
			}},
		},
	}

	err := p.UpdateById(uuid.New(), input)
	var ve *validationFailureError
	if !errors.As(err, &ve) {
		t.Fatalf("expected validationFailureError, got %v", err)
	}

	apiErrs := ve.AsJSONAPIErrors()
	if len(apiErrs) == 0 {
		t.Fatal("expected at least one JSON:API error")
	}

	// Verify structure of the first error
	if apiErrs[0].Status != "400" {
		t.Errorf("expected status '400', got '%s'", apiErrs[0].Status)
	}
	if apiErrs[0].Title != "validation failed" {
		t.Errorf("expected title 'validation failed', got '%s'", apiErrs[0].Title)
	}
	if apiErrs[0].Meta == nil {
		t.Error("expected non-nil meta")
	}
}

// TestProcessor_Create_IgnoresClientSuppliedEnvironment pins task-232 R21-1:
// Environment is server-owned. A client that supplies "environment" in a
// create body must not move the row's Entity.Environment column — the
// column stays at the GORM default (”) until a future task wires actual
// scoping onto the write path.
func TestProcessor_Create_IgnoresClientSuppliedEnvironment(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	input := createTestRestModel("GMS", 83, 1)
	input.Environment = "evil"

	id, err := p.Create(input)
	if err != nil {
		t.Fatalf("failed to create tenant: %v", err)
	}

	var stored testEntity
	if err := db.Where("id = ?", id).First(&stored).Error; err != nil {
		t.Fatalf("failed to load stored entity: %v", err)
	}
	if stored.Environment != "" {
		t.Errorf("expected Entity.Environment to stay at the default '', got %q", stored.Environment)
	}
}

// TestProcessor_UpdateById_IgnoresClientSuppliedEnvironment pins task-232
// R21-1: an update body's "environment" must never move an existing row
// between environments. The row is seeded directly at the Entity level with
// owner "pr-100", the caller is "pr-100" too (task-13 strict scoping now
// rejects a mismatched caller before R21-1's sanitization is even reached),
// then UpdateById is called with a different environment in the payload;
// the column must be untouched.
func TestProcessor_UpdateById_IgnoresClientSuppliedEnvironment(t *testing.T) {
	db := setupTestDB(t)
	l := testLogger()
	ctx := env.WithContext(context.Background(), env.Id("pr-100"))
	p := NewProcessor(l, ctx, db)

	id := uuid.New()
	seed := testEntity{
		Id:           id,
		Region:       "GMS",
		MajorVersion: 83,
		MinorVersion: 1,
		Data:         json.RawMessage(`{}`),
		Environment:  "pr-100",
	}
	if err := db.Create(&seed).Error; err != nil {
		t.Fatalf("failed to seed entity: %v", err)
	}

	updated := createTestRestModel("SEA", 84, 2)
	updated.Environment = "evil"
	if err := p.UpdateById(id, updated); err != nil {
		t.Fatalf("failed to update tenant: %v", err)
	}

	var stored testEntity
	if err := db.Where("id = ?", id).First(&stored).Error; err != nil {
		t.Fatalf("failed to load stored entity: %v", err)
	}
	if stored.Environment != "pr-100" {
		t.Errorf("expected Entity.Environment to stay 'pr-100', got %q", stored.Environment)
	}
}

// TestMake_SetsEnvironmentFromEntityColumn pins the read side of R21-1:
// Make() must source RestModel.Environment from the Entity column, not from
// whatever the JSON blob happens to contain.
func TestMake_SetsEnvironmentFromEntityColumn(t *testing.T) {
	entity := Entity{
		Id:           uuid.New(),
		Region:       "GMS",
		MajorVersion: 83,
		MinorVersion: 1,
		Data:         json.RawMessage(`{"environment":"evil"}`),
		Environment:  "pr-100",
	}

	result, err := Make(entity)
	if err != nil {
		t.Fatalf("Make failed: %v", err)
	}
	if result.Environment != "pr-100" {
		t.Errorf("expected Environment 'pr-100' from the Entity column, got %q", result.Environment)
	}
}

// outboxTenantEnvelope decodes the wire shape outbox.NewTenantEnvelope
// produces — the same shape libs/atlas-service's envSubscriber.handleTenant
// decodes off EVENT_TOPIC_CONFIGURATION_TENANT_STATUS. Config is read only
// far enough to inspect "environment", matching what the projection reads.
type outboxTenantEnvelope struct {
	SchemaVersion int    `json:"schema_version"`
	Id            string `json:"id"`
	Config        struct {
		Environment string `json:"environment"`
	} `json:"config"`
	EmittedAt string `json:"emitted_at"`
}

// latestOutboxTenantEnvelope loads the most recently enqueued outbox row
// for the given topic and decodes it as a tenant envelope.
func latestOutboxTenantEnvelope(t *testing.T, db *gorm.DB, topic string) outboxTenantEnvelope {
	t.Helper()
	var row outboxlib.Entity
	if err := db.Where("topic = ?", topic).Order("id DESC").First(&row).Error; err != nil {
		t.Fatalf("failed to load outbox row for topic %q: %v", topic, err)
	}
	var env outboxTenantEnvelope
	if err := json.Unmarshal(row.MessageValue, &env); err != nil {
		t.Fatalf("failed to decode outbox message value: %v", err)
	}
	return env
}

// TestProcessor_Create_OutboxMessageNeverCarriesClientSuppliedEnvironment
// pins task-232 R21-1's Critical fix: a client-supplied "environment" in a
// create body must not surface in the message published to
// EVENT_TOPIC_CONFIGURATION_TENANT_STATUS. Unlike
// TestProcessor_Create_IgnoresClientSuppliedEnvironment (which only checks
// the DB row), this decodes the actual enqueued outbox payload — the input
// libs/atlas-service's tenant->environment projection (and therefore
// Reconcile/FR-7.7) consumes.
func TestProcessor_Create_OutboxMessageNeverCarriesClientSuppliedEnvironment(t *testing.T) {
	t.Setenv("EVENT_TOPIC_CONFIGURATION_TENANT_STATUS", "tenant-status")
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	input := createTestRestModel("GMS", 83, 1)
	input.Environment = "pr-999"

	id, err := p.Create(input)
	if err != nil {
		t.Fatalf("failed to create tenant: %v", err)
	}

	env := latestOutboxTenantEnvelope(t, db, "tenant-status")
	if env.Id != id.String() {
		t.Fatalf("expected outbox envelope id %q, got %q", id.String(), env.Id)
	}
	if env.Config.Environment != "" {
		t.Errorf("expected outbox message environment to stay the server-owned default '', got %q (client-supplied value leaked onto the wire)", env.Config.Environment)
	}
}

// TestProcessor_UpdateById_OutboxMessageNeverCarriesClientSuppliedEnvironment
// is the update-path equivalent: the row is seeded with a real environment
// directly at the Entity level, then updated with a different
// client-supplied environment; the outbox message must carry the seeded
// (persisted) value, never the client's.
func TestProcessor_UpdateById_OutboxMessageNeverCarriesClientSuppliedEnvironment(t *testing.T) {
	t.Setenv("EVENT_TOPIC_CONFIGURATION_TENANT_STATUS", "tenant-status")
	db := setupTestDB(t)
	l := testLogger()
	ctx := env.WithContext(context.Background(), env.Id("pr-100"))
	p := NewProcessor(l, ctx, db)

	id := uuid.New()
	seed := testEntity{
		Id:           id,
		Region:       "GMS",
		MajorVersion: 83,
		MinorVersion: 1,
		Data:         json.RawMessage(`{}`),
		Environment:  "pr-100",
	}
	if err := db.Create(&seed).Error; err != nil {
		t.Fatalf("failed to seed entity: %v", err)
	}

	updated := createTestRestModel("SEA", 84, 2)
	updated.Environment = "pr-999"
	if err := p.UpdateById(id, updated); err != nil {
		t.Fatalf("failed to update tenant: %v", err)
	}

	env := latestOutboxTenantEnvelope(t, db, "tenant-status")
	if env.Config.Environment != "pr-100" {
		t.Errorf("expected outbox message environment to stay the persisted 'pr-100', got %q (client-supplied value leaked onto the wire)", env.Config.Environment)
	}
}

// TestEnqueueTenantStatus_SkippedWhenTopicUnset guards the sanitize-then-
// enqueue tests above: with EVENT_TOPIC_CONFIGURATION_TENANT_STATUS unset
// (the default in every other test in this file), no outbox row is written
// at all, matching pre-existing behaviour.
func TestEnqueueTenantStatus_SkippedWhenTopicUnset(t *testing.T) {
	if topic := os.Getenv("EVENT_TOPIC_CONFIGURATION_TENANT_STATUS"); topic != "" {
		t.Fatalf("test environment leaked EVENT_TOPIC_CONFIGURATION_TENANT_STATUS=%q", topic)
	}
	db := setupTestDB(t)
	l := testLogger()
	ctx := context.Background()
	p := NewProcessor(l, ctx, db)

	if _, err := p.Create(createTestRestModel("GMS", 83, 1)); err != nil {
		t.Fatalf("failed to create tenant: %v", err)
	}

	var count int64
	if err := db.Model(&outboxlib.Entity{}).Count(&count).Error; err != nil {
		t.Fatalf("failed to count outbox rows: %v", err)
	}
	if count != 0 {
		t.Errorf("expected no outbox rows enqueued with the topic unset, got %d", count)
	}
}
