// Code generated by gen; DO NOT EDIT.

package skill

const (
	BeginnerThreeSnails                       Identity = 1000
	BeginnerRecovery                          Identity = 1001
	BeginnerNimbleFeet                        Identity = 1002
	BeginnerSoulOfCraftsman                   Identity = 1003
	BeginnerMonsterRiding                     Identity = 1004
	BeginnerEchoOfHero                        Identity = 1005
	BeginnerJumpDown                          Identity = 1006
	BeginnerMaker                             Identity = 1007
	BeginnerMultiPet                          Identity = 1008
	BeginnerBamboo                            Identity = 1009
	BeginnerInvincible                        Identity = 1010
	BeginnerBerserk                           Identity = 1011
	BeginnerBlessOfNymph                      Identity = 1012
	BeginnerSpaceShip                         Identity = 1013
	BeginnerYetiMount1                        Identity = 1017
	BeginnerYetiMount2                        Identity = 1018
	BeginnerBroomstick                        Identity = 1019
	BeginnerBalrogMount                       Identity = 1031
	WarriorImprovedHpRecovery                 Identity = 1000000
	WarriorImprovedMaxHpIncrease              Identity = 1000001
	WarriorEndure                             Identity = 1000002
	WarriorHpBoost                            Identity = 1000006
	WarriorIronBody                           Identity = 1001003
	WarriorPowerStrike                        Identity = 1001004
	WarriorSlashBlast                         Identity = 1001005
	NoblesseSpaceShip                         Identity = 1001014
	FighterSwordMastery                       Identity = 1100000
	FighterAxeMastery                         Identity = 1100001
	FighterFinalAttackSword                   Identity = 1100002
	FighterFinalAttackAxe                     Identity = 1100003
	FighterEnhancedBasics                     Identity = 1100009
	FighterSwordBooster                       Identity = 1101004
	FighterAxeBooster                         Identity = 1101005
	FighterRage                               Identity = 1101006
	FighterPowerGuard                         Identity = 1101007
	FighterGroundSmash                        Identity = 1101008
	CrusaderImprovingMpRecovery               Identity = 1110000
	CrusaderShieldMastery                     Identity = 1110001
	CrusaderComboAttack                       Identity = 1111002
	CrusaderPanicSword                        Identity = 1111003
	CrusaderPanicAxe                          Identity = 1111004
	CrusaderComaSword                         Identity = 1111005
	CrusaderComaAxe                           Identity = 1111006
	CrusaderArmorCrash                        Identity = 1111007
	CrusaderShout                             Identity = 1111008
	HeroAdvancedComboAttack                   Identity = 1120003
	HeroAchilles                              Identity = 1120004
	HeroGuardian                              Identity = 1120005
	HeroCombatMastery                         Identity = 1120012
	HeroMapleWarrior                          Identity = 1121000
	HeroMonsterMagnet                         Identity = 1121001
	HeroPowerStance                           Identity = 1121002
	HeroRush                                  Identity = 1121006
	HeroBrandish                              Identity = 1121008
	HeroEnrage                                Identity = 1121010
	HeroHerosWill                             Identity = 1121011
	PageSwordMastery                          Identity = 1200000
	PageBluntWeaponMastery                    Identity = 1200001
	PageSwordFinalAttack                      Identity = 1200002
	PageBluntFinalAttack                      Identity = 1200003
	PageSwordBooster                          Identity = 1201004
	PageBluntWeaponBooster                    Identity = 1201005
	PageThreaten                              Identity = 1201006
	PagePowerGuard                            Identity = 1201007
	WhiteKnightImprovingMpRecovery            Identity = 1210000
	WhiteKnightShieldMastery                  Identity = 1210001
	WhiteKnightChargedBlow                    Identity = 1211002
	WhiteKnightFireChargeSword                Identity = 1211003
	WhiteKnightFlameChargeBluntWeapon         Identity = 1211004
	WhiteKnightIceChargeSword                 Identity = 1211005
	WhiteKnightBlizzardChargeBluntWeapon      Identity = 1211006
	WhiteKnightThunderChargeSword             Identity = 1211007
	WhiteKnightLightningChargeBluntWeapon     Identity = 1211008
	WhiteKnightMagicCrash                     Identity = 1211009
	PaladinAchilles                           Identity = 1220005
	PaladinGuardian                           Identity = 1220006
	PaladinAdvancedCharge                     Identity = 1220010
	PaladinMapleWarrior                       Identity = 1221000
	PaladinMonsterMagnet                      Identity = 1221001
	PaladinPowerStance                        Identity = 1221002
	PaladinHolyChargeSword                    Identity = 1221003
	PaladinDivineChargeBluntWeapon            Identity = 1221004
	PaladinRush                               Identity = 1221007
	PaladinBlast                              Identity = 1221009
	PaladinHeavensHammer                      Identity = 1221011
	PaladinHerosWill                          Identity = 1221012
	SpearmanSpearMastery                      Identity = 1300000
	SpearmanPolearmMastery                    Identity = 1300001
	SpearmanFinalAttackSpear                  Identity = 1300002
	SpearmanFinalAttackPolearm                Identity = 1300003
	SpearmanSpearBooster                      Identity = 1301004
	SpearmanPolearmBooster                    Identity = 1301005
	SpearmanIronWill                          Identity = 1301006
	SpearmanHyperBody                         Identity = 1301007
	DragonKnightElementalResistance           Identity = 1310000
	DragonKnightSpearCrusher                  Identity = 1311001
	DragonKnightPolearmCrusher                Identity = 1311002
	DragonKnightDragonFurySpear               Identity = 1311003
	DragonKnightDragonFuryPolearm             Identity = 1311004
	DragonKnightSacrifice                     Identity = 1311005
	DragonKnightDragonRoar                    Identity = 1311006
	DragonKnightPowerCrash                    Identity = 1311007
	DragonKnightDragonBlood                   Identity = 1311008
	DarkKnightAchilles                        Identity = 1320005
	DarkKnightBerserk                         Identity = 1320006
	DarkKnightAuraOfTheBeholder               Identity = 1320008
	DarkKnightHexOfTheBeholder                Identity = 1320009
	DarkKnightMapleWarrior                    Identity = 1321000
	DarkKnightMonsterMagnet                   Identity = 1321001
	DarkKnightPowerStance                     Identity = 1321002
	DarkKnightRush                            Identity = 1321003
	DarkKnightBeholder                        Identity = 1321007
	DarkKnightHerosWill                       Identity = 1321010
	MagicianImprovedMpRecovery                Identity = 2000000
	MagicianImprovedMaxMpIncrease             Identity = 2000001
	MagicianMpBoost                           Identity = 2000006
	MagicianMagicGuard                        Identity = 2001002
	MagicianMagicArmor                        Identity = 2001003
	MagicianEnergyBolt                        Identity = 2001004
	MagicianMagicClaw                         Identity = 2001005
	FirePoisonWizardMpEater                   Identity = 2100000
	FirePoisonWizardMeditation                Identity = 2101001
	FirePoisonWizardTeleport                  Identity = 2101002
	FirePoisonWizardSlow                      Identity = 2101003
	FirePoisonWizardFireArrow                 Identity = 2101004
	FirePoisonWizardPoisonBreath              Identity = 2101005
	FirePoisonMagicianPartialResistance       Identity = 2110000
	FirePoisonMagicianElementAmplification    Identity = 2110001
	FirePoisonMagicianExplosion               Identity = 2111002
	FirePoisonMagicianPoisonMist              Identity = 2111003
	FirePoisonMagicianSeal                    Identity = 2111004
	FirePoisonMagicianSpellBooster            Identity = 2111005
	FirePoisonMagicianElementComposition      Identity = 2111006
	FirePoisonArchMagicianMapleWarrior        Identity = 2121000
	FirePoisonArchMagicianBigBang             Identity = 2121001
	FirePoisonArchMagicianManaReflection      Identity = 2121002
	FirePoisonArchMagicianFireDemon           Identity = 2121003
	FirePoisonArchMagicianInfinity            Identity = 2121004
	FirePoisonArchMagicianElquines            Identity = 2121005
	FirePoisonArchMagicianParalyze            Identity = 2121006
	FirePoisonArchMagicianMeteorShower        Identity = 2121007
	FirePoisonArchMagicianHerosWill           Identity = 2121008
	IceLightningWizardMpEater                 Identity = 2200000
	IceLightningWizardMeditation              Identity = 2201001
	IceLightningWizardTeleport                Identity = 2201002
	IceLightningWizardSlow                    Identity = 2201003
	IceLightningWizardColdBeam                Identity = 2201004
	IceLightningWizardThunderBolt             Identity = 2201005
	IceLightningMagicianPartialResistance     Identity = 2210000
	IceLightningMagicianElementAmplification  Identity = 2210001
	IceLightningMagicianIceStrike             Identity = 2211002
	IceLightningMagicianThunderSpear          Identity = 2211003
	IceLightningMagicianSeal                  Identity = 2211004
	IceLightningMagicianSpellBooster          Identity = 2211005
	IceLightningMagicianElementComposition    Identity = 2211006
	IceLightningArchMagicianMapleWarrior      Identity = 2221000
	IceLightningArchMagicianBigBang           Identity = 2221001
	IceLightningArchMagicianManaReflection    Identity = 2221002
	IceLightningArchMagicianIceDemon          Identity = 2221003
	IceLightningArchMagicianInfinity          Identity = 2221004
	IceLightningArchMagicianIfrit             Identity = 2221005
	IceLightningArchMagicianChainLightning    Identity = 2221006
	IceLightningArchMagicianBlizzard          Identity = 2221007
	IceLightningArchMagicianHerosWill         Identity = 2221008
	ClericMpEater                             Identity = 2300000
	ClericTeleport                            Identity = 2301001
	ClericHeal                                Identity = 2301002
	ClericInvincible                          Identity = 2301003
	ClericBless                               Identity = 2301004
	ClericHolyArrow                           Identity = 2301005
	PriestElementalResistance                 Identity = 2310000
	PriestDispel                              Identity = 2311001
	PriestMysticDoor                          Identity = 2311002
	PriestHolySymbol                          Identity = 2311003
	PriestShiningRay                          Identity = 2311004
	PriestDoom                                Identity = 2311005
	PriestSummonDragon                        Identity = 2311006
	BishopMapleWarrior                        Identity = 2321000
	BishopBigBang                             Identity = 2321001
	BishopManaReflection                      Identity = 2321002
	BishopBahamut                             Identity = 2321003
	BishopInfinity                            Identity = 2321004
	BishopHolyShield                          Identity = 2321005
	BishopResurrection                        Identity = 2321006
	BishopAngelRay                            Identity = 2321007
	BishopGenesis                             Identity = 2321008
	BishopHerosWill                           Identity = 2321009
	BowmanTheBlessingOfAmazon                 Identity = 3000000
	BowmanCriticalShot                        Identity = 3000001
	BowmanTheEyeOfAmazon                      Identity = 3000002
	BowmanFocus                               Identity = 3001003
	BowmanArrowBlow                           Identity = 3001004
	BowmanDoubleShot                          Identity = 3001005
	HunterBowMastery                          Identity = 3100000
	HunterFinalAttackBow                      Identity = 3100001
	HunterBowBooster                          Identity = 3101002
	HunterPowerKnockBack                      Identity = 3101003
	HunterSoulArrowBow                        Identity = 3101004
	HunterArrowBombBow                        Identity = 3101005
	RangerThrust                              Identity = 3110000
	RangerMortalBlow                          Identity = 3110001
	RangerPuppet                              Identity = 3111002
	RangerInferno                             Identity = 3111003
	RangerArrowRain                           Identity = 3111004
	RangerSilverHawk                          Identity = 3111005
	RangerStrafe                              Identity = 3111006
	BowmasterBowExpert                        Identity = 3120005
	BowmasterMapleWarrior                     Identity = 3121000
	BowmasterSharpEyes                        Identity = 3121002
	BowmasterDragonsBreath                    Identity = 3121003
	BowmasterHurricane                        Identity = 3121004
	BowmasterPhoenix                          Identity = 3121006
	BowmasterHamstring                        Identity = 3121007
	BowmasterConcentrate                      Identity = 3121008
	BowmasterHerosWill                        Identity = 3121009
	CrossbowmanCrossbowMastery                Identity = 3200000
	CrossbowmanFinalAttackCrossbow            Identity = 3200001
	CrossbowmanCrossbowBooster                Identity = 3201002
	CrossbowmanPowerKnockBack                 Identity = 3201003
	CrossbowmanSoulArrowCrossbow              Identity = 3201004
	CrossbowmanIronArrowCrossbow              Identity = 3201005
	SniperThrust                              Identity = 3210000
	SniperMortalBlow                          Identity = 3210001
	SniperPuppet                              Identity = 3211002
	SniperBlizzard                            Identity = 3211003
	SniperArrowEruption                       Identity = 3211004
	SniperGoldenEagle                         Identity = 3211005
	SniperStrafe                              Identity = 3211006
	MarksmanMarksmanBoost                     Identity = 3220004
	MarksmanMapleWarrior                      Identity = 3221000
	MarksmanPiercingArrow                     Identity = 3221001
	MarksmanSharpEyes                         Identity = 3221002
	MarksmanDragonsBreath                     Identity = 3221003
	MarksmanFrostprey                         Identity = 3221005
	MarksmanBlind                             Identity = 3221006
	MarksmanSnipe                             Identity = 3221007
	MarksmanHerosWill                         Identity = 3221008
	RogueNimbleBody                           Identity = 4000000
	RogueKeenEyes                             Identity = 4000001
	RogueDisorder                             Identity = 4001002
	RogueDarkSight                            Identity = 4001003
	RogueDoubleStab                           Identity = 4001334
	RogueLuckySeven                           Identity = 4001344
	AssassinClawMastery                       Identity = 4100000
	AssassinCriticalThrow                     Identity = 4100001
	AssassinEndure                            Identity = 4100002
	AssassinShadowResistance                  Identity = 4100006
	AssassinClawBooster                       Identity = 4101003
	AssassinHaste                             Identity = 4101004
	AssassinDrain                             Identity = 4101005
	HermitAlchemist                           Identity = 4110000
	HermitMesoUp                              Identity = 4111001
	HermitShadowPartner                       Identity = 4111002
	HermitShadowWeb                           Identity = 4111003
	HermitShadowMeso                          Identity = 4111004
	HermitAvenger                             Identity = 4111005
	HermitFlashJump                           Identity = 4111006
	NightLordShadowShifter                    Identity = 4120002
	NightLordVenomousStar                     Identity = 4120005
	NightLordMapleWarrior                     Identity = 4121000
	NightLordTaunt                            Identity = 4121003
	NightLordNinjaAmbush                      Identity = 4121004
	NightLordShadowStars                      Identity = 4121006
	NightLordTripleThrow                      Identity = 4121007
	NightLordNinjaStorm                       Identity = 4121008
	NightLordHerosWill                        Identity = 4121009
	BanditDaggerMastery                       Identity = 4200000
	BanditEndure                              Identity = 4200001
	BanditShadowResistance                    Identity = 4200006
	BanditDaggerBooster                       Identity = 4201002
	BanditHaste                               Identity = 4201003
	BanditSteal                               Identity = 4201004
	BanditSavageBlow                          Identity = 4201005
	ChiefBanditShieldMastery                  Identity = 4210000
	ChiefBanditChakra                         Identity = 4211001
	ChiefBanditAssaulter                      Identity = 4211002
	ChiefBanditPickpocket                     Identity = 4211003
	ChiefBanditBandOfThieves                  Identity = 4211004
	ChiefBanditMesoGuard                      Identity = 4211005
	ChiefBanditMesoExplosion                  Identity = 4211006
	ShadowerShadowShifter                     Identity = 4220002
	ShadowerVenomousStab                      Identity = 4220005
	ShadowerMapleWarrior                      Identity = 4221000
	ShadowerAssassinate                       Identity = 4221001
	ShadowerTaunt                             Identity = 4221003
	ShadowerNinjaAmbush                       Identity = 4221004
	ShadowerSmokescreen                       Identity = 4221006
	ShadowerBoomerangStep                     Identity = 4221007
	ShadowerHerosWill                         Identity = 4221008
	BladeRecruitKataraMastery                 Identity = 4300000
	BladeRecruitTripleStab                    Identity = 4301001
	BladeRecruitKataraBooster                 Identity = 4301002
	BladeAcolyteEndure                        Identity = 4310000
	BladeAcolyteShadowResistance              Identity = 4310004
	BladeAcolyteSelfHaste                     Identity = 4311001
	BladeAcolyteFatalBlow                     Identity = 4311002
	BladeAcolyteSlashStorm                    Identity = 4311003
	BladeSpecialistTornadoSpin                Identity = 4321000
	BladeSpecialistTornadoSpinAttack          Identity = 4321001
	BladeSpecialistFlashbang                  Identity = 4321002
	BladeSpecialistFlashJump                  Identity = 4321003
	BladeLordAdvancedDarkSight                Identity = 4330001
	BladeLordBloodyStorm                      Identity = 4331000
	BladeLordMirrorImage                      Identity = 4331002
	BladeLordOwlSpirit                        Identity = 4331003
	BladeLordUpperStab                        Identity = 4331004
	BladeLordFlyingAssaulter                  Identity = 4331005
	BladeMasterVenom                          Identity = 4340001
	BladeMasterMapleWarrior                   Identity = 4341000
	BladeMasterFinalCut                       Identity = 4341002
	BladeMasterMonsterBomb                    Identity = 4341003
	BladeMasterSuddenRaid                     Identity = 4341004
	BladeMasterChainsOfHell                   Identity = 4341005
	BladeMasterMirroredTarget                 Identity = 4341006
	BladeMasterThorns                         Identity = 4341007
	BladeMasterHerosWill                      Identity = 4341008
	PirateBulletTime                          Identity = 5000000
	PirateFlashFist                           Identity = 5001001
	PirateSommersaultKick                     Identity = 5001002
	PirateDoubleShot                          Identity = 5001003
	PirateDash                                Identity = 5001005
	BrawlerImproveMaxHp                       Identity = 5100000
	BrawlerKnucklerMastery                    Identity = 5100001
	BrawlerCriticalPunch                      Identity = 5100008
	BrawlerHpBoost                            Identity = 5100009
	BrawlerBackspinBlow                       Identity = 5101002
	BrawlerDoubleUppercut                     Identity = 5101003
	BrawlerCorkscrewBlow                      Identity = 5101004
	BrawlerMPRecovery                         Identity = 5101005
	BrawlerKnucklerBooster                    Identity = 5101006
	BrawlerOakBarrel                          Identity = 5101007
	MarauderStunMastery                       Identity = 5110000
	MarauderEnergyCharge                      Identity = 5110001
	MarauderEnergyBlast                       Identity = 5111002
	MarauderEnergyDrain                       Identity = 5111004
	MarauderTransformation                    Identity = 5111005
	MarauderShockwave                         Identity = 5111006
	BuccaneerMapleWarrior                     Identity = 5121000
	BuccaneerDragonStrike                     Identity = 5121001
	BuccaneerEnergyOrb                        Identity = 5121002
	BuccaneerSuperTransformation              Identity = 5121003
	BuccaneerDemolition                       Identity = 5121004
	BuccaneerSnatch                           Identity = 5121005
	BuccaneerBarrage                          Identity = 5121007
	BuccaneerPiratesRage                      Identity = 5121008
	BuccaneerSpeedInfusion                    Identity = 5121009
	BuccaneerTimeLeap                         Identity = 5121010
	GunslingerGunMastery                      Identity = 5200000
	GunslingerInvisibleShot                   Identity = 5201001
	GunslingerGrenade                         Identity = 5201002
	GunslingerGunBooster                      Identity = 5201003
	GunslingerBlankShot                       Identity = 5201004
	GunslingerWings                           Identity = 5201005
	GunslingerRecoilShot                      Identity = 5201006
	OutlawBurstFire                           Identity = 5210000
	OutlawOctopus                             Identity = 5211001
	OutlawGaviota                             Identity = 5211002
	OutlawFlamethrower                        Identity = 5211004
	OutlawIceSplitter                         Identity = 5211005
	OutlawHomingBeacon                        Identity = 5211006
	CorsairElementalBoost                     Identity = 5220001
	CorsairWrathOfTheOctopi                   Identity = 5220002
	CorsairBullseye                           Identity = 5220011
	CorsairMapleWarrior                       Identity = 5221000
	CorsairAerialStrike                       Identity = 5221003
	CorsairRapidFire                          Identity = 5221004
	CorsairBattleship                         Identity = 5221006
	CorsairBattleshipCannon                   Identity = 5221007
	CorsairBattleshipTorpedo                  Identity = 5221008
	CorsairHypnotize                          Identity = 5221009
	CorsairSpeedInfusion                      Identity = 5221010
	MapleLeafBrigadierAntiMacro               Identity = 8001000
	MapleLeafBrigadierTeleport                Identity = 8001001
	GmHaste                                   Identity = 9001000
	GmSuperDragonRoar                         Identity = 9001001
	GmTeleport                                Identity = 9001002
	GmHide                                    Identity = 9001004
	GmResurrection                            Identity = 9001005
	SuperGmHealDispel                         Identity = 9101000
	SuperGmHaste                              Identity = 9101001
	SuperGmHolySymbol                         Identity = 9101002
	SuperGmBless                              Identity = 9101003
	SuperGmHide                               Identity = 9101004
	SuperGmResurrection                       Identity = 9101005
	SuperGmDragonRoar                         Identity = 9101006
	SuperGmTeleport                           Identity = 9101007
	SuperGmHyperBody                          Identity = 9101008
	NoblesseThreeSnails                       Identity = 10001000
	NoblesseRecovery                          Identity = 10001001
	NoblesseNimbleFeet                        Identity = 10001002
	NoblesseSoulOfCraftsman                   Identity = 10001003
	NoblesseMonsterRiding                     Identity = 10001004
	NoblesseEchoOfHero                        Identity = 10001005
	NoblesseJumpDown                          Identity = 10001006
	NoblesseMaker                             Identity = 10001007
	NoblesseMultiPet                          Identity = 10001008
	NoblesseBamboo                            Identity = 10001009
	NoblesseInvincible                        Identity = 10001010
	NoblesseBerserk                           Identity = 10001011
	NoblesseBlessOfNymph                      Identity = 10001012
	NoblesseYetiMount1                        Identity = 10001019
	NoblesseYetiMount2                        Identity = 10001022
	NoblesseBroomstick                        Identity = 10001023
	NoblesseBalrogMount                       Identity = 10001031
	DawnWarriorStage1MaxHpEnhancement         Identity = 11000000
	DawnWarriorStage1ImprovedMaxHpIncrease    Identity = 11000005
	DawnWarriorStage1IronBody                 Identity = 11001001
	DawnWarriorStage1PowerStrike              Identity = 11001002
	DawnWarriorStage1SlashBlast               Identity = 11001003
	DawnWarriorStage1Soul                     Identity = 11001004
	DawnWarriorStage2SwordMastery             Identity = 11100000
	DawnWarriorStage2SwordBooster             Identity = 11101001
	DawnWarriorStage2FinalAttackSword         Identity = 11101002
	DawnWarriorStage2Rage                     Identity = 11101003
	DawnWarriorStage2SoulBlade                Identity = 11101004
	DawnWarriorStage2SoulRush                 Identity = 11101005
	DawnWarriorStage3ImprovedMpRecovery       Identity = 11110000
	DawnWarriorStage3AdvancedCombo            Identity = 11110005
	DawnWarriorStage3ComboAttack              Identity = 11111001
	DawnWarriorStage3Panic                    Identity = 11111002
	DawnWarriorStage3Coma                     Identity = 11111003
	DawnWarriorStage3Brandish                 Identity = 11111004
	DawnWarriorStage3SoulDriver               Identity = 11111006
	DawnWarriorStage3SoulCharge               Identity = 11111007
	BlazeWizardStage1IncreasingMaxMp          Identity = 12000000
	BlazeWizardStage1ImprovedMaxMpIncrease    Identity = 12000005
	BlazeWizardStage1MagicGuard               Identity = 12001001
	BlazeWizardStage1MagicArmor               Identity = 12001002
	BlazeWizardStage1MagicClaw                Identity = 12001003
	BlazeWizardStage1Flame                    Identity = 12001004
	BlazeWizardStage3SpellMastery             Identity = 12100007
	BlazeWizardStage2Meditation               Identity = 12101000
	BlazeWizardStage2Slow                     Identity = 12101001
	BlazeWizardStage2FireArrow                Identity = 12101002
	BlazeWizardStage2Teleport                 Identity = 12101003
	BlazeWizardStage2SpellBooster             Identity = 12101004
	BlazeWizardStage2ElementalReset           Identity = 12101005
	BlazeWizardStage2FirePillar               Identity = 12101006
	BlazeWizardStage3ElementResistance        Identity = 12110000
	BlazeWizardStage3ElementAmplification     Identity = 12110001
	BlazeWizardStage3Seal                     Identity = 12111002
	BlazeWizardStage3MeteorShower             Identity = 12111003
	BlazeWizardStage3Ifrit                    Identity = 12111004
	BlazeWizardStage3FlameGear                Identity = 12111005
	BlazeWizardStage3FireStrike               Identity = 12111006
	WindArcherStage1CriticalShot              Identity = 13000000
	WindArcherStage1TheEyeOfAmazon            Identity = 13000001
	WindArcherStage1Focus                     Identity = 13001002
	WindArcherStage1DoubleShot                Identity = 13001003
	WindArcherStage1Storm                     Identity = 13001004
	WindArcherStage2BowMastery                Identity = 13100000
	WindArcherStage2Thrust                    Identity = 13100004
	WindArcherStage2BowBooster                Identity = 13101001
	WindArcherStage2FinalAttackBow            Identity = 13101002
	WindArcherStage2SoulArrow                 Identity = 13101003
	WindArcherStage2StormBreak                Identity = 13101005
	WindArcherStage2WindWalk                  Identity = 13101006
	WindArcherStage3BowExpert                 Identity = 13110003
	WindArcherStage3ArrowRain                 Identity = 13111000
	WindArcherStage3Strafe                    Identity = 13111001
	WindArcherStage3Hurricane                 Identity = 13111002
	WindArcherStage3Puppet                    Identity = 13111004
	WindArcherStage3EagleEye                  Identity = 13111005
	WindArcherStage3WindPiercing              Identity = 13111006
	WindArcherStage3WindShot                  Identity = 13111007
	NightWalkerStage1NimbleBody               Identity = 14000000
	NightWalkerStage1KeenEyes                 Identity = 14000001
	NightWalkerStage1Disorder                 Identity = 14001002
	NightWalkerStage1DarkSight                Identity = 14001003
	NightWalkerStage1LuckySeven               Identity = 14001004
	NightWalkerStage1Darkness                 Identity = 14001005
	NightWalkerStage2ClawMastery              Identity = 14100000
	NightWalkerStage2CriticalThrow            Identity = 14100001
	NightWalkerStage2Vanish                   Identity = 14100005
	NightWalkerStage2ClawBooster              Identity = 14101002
	NightWalkerStage2Haste                    Identity = 14101003
	NightWalkerStage2FlashJump                Identity = 14101004
	NightWalkerStage2Vampire                  Identity = 14101006
	NightWalkerStage3Alchemist                Identity = 14110003
	NightWalkerStage3Venom                    Identity = 14110004
	NightWalkerStage3ShadowPartner            Identity = 14111000
	NightWalkerStage3ShadowWeb                Identity = 14111001
	NightWalkerStage3Avenger                  Identity = 14111002
	NightWalkerStage3TripleThrow              Identity = 14111005
	NightWalkerStage3PoisonBomb               Identity = 14111006
	ThunderBreakerStage1QuickMotion           Identity = 15000000
	ThunderBreakerStage1FirstStrike           Identity = 15001001
	ThunderBreakerStage1SomersaultKick        Identity = 15001002
	ThunderBreakerStage1Dash                  Identity = 15001003
	ThunderBreakerStage1LightningSprite       Identity = 15001004
	ThunderBreakerStage2KnuckleMastery        Identity = 15100001
	ThunderBreakerStage2EnergyCharge          Identity = 15100004
	ThunderBreakerStage2ImprovedMaxHpIncrease Identity = 15100007
	ThunderBreakerStage2KnuckleBooster        Identity = 15101002
	ThunderBreakerStage2CorkscrewBlow         Identity = 15101003
	ThunderBreakerStage2EnergyBlast           Identity = 15101005
	ThunderBreakerStage2LightningCharge       Identity = 15101006
	ThunderBreakerStage3CriticalPunch         Identity = 15110000
	ThunderBreakerStage3EnergyDrain           Identity = 15111001
	ThunderBreakerStage3Transformation        Identity = 15111002
	ThunderBreakerStage3ShockWave             Identity = 15111003
	ThunderBreakerStage3Barrage               Identity = 15111004
	ThunderBreakerStage3SpeedInfusion         Identity = 15111005
	ThunderBreakerStage3Spark                 Identity = 15111006
	ThunderBreakerStage3SharkWave             Identity = 15111007
	LegendBlessOfNymph                        Identity = 20000012
	LegendComboAbility                        Identity = 20000017
	LegendThreeSnails                         Identity = 20001000
	LegendRecovery                            Identity = 20001001
	LegendNimbleFeet                          Identity = 20001002
	LegendSoulOfCraftsman                     Identity = 20001003
	LegendMonsterRiding                       Identity = 20001004
	LegendEchoOfHero                          Identity = 20001005
	LegendDamageMeter                         Identity = 20001006
	LegendMaker                               Identity = 20001007
	LegendBamboo                              Identity = 20001009
	LegendInvincible                          Identity = 20001010
	LegendBerserk                             Identity = 20001011
	LegendYetiMount1                          Identity = 20001019
	LegendYetiMount2                          Identity = 20001022
	LegendBroomstick                          Identity = 20001023
	LegendBalrogMount                         Identity = 20001031
	EvanBlessOfNymph                          Identity = 20010012
	EvanThreeSnails                           Identity = 20011000
	EvanRecovery                              Identity = 20011001
	EvanNimbleFeet                            Identity = 20011002
	EvanSoulOfCraftsman                       Identity = 20011003
	EvanMonsterRiding                         Identity = 20011004
	EvanEchoOfHero                            Identity = 20011005
	EvanDamageMeter                           Identity = 20011006
	EvanMaker                                 Identity = 20011007
	EvanBamboo                                Identity = 20011009
	EvanInvincible                            Identity = 20011010
	EvanBerserk                               Identity = 20011011
	AranStage1ComboAbility                    Identity = 21000000
	AranStage1DoubleSwing                     Identity = 21000002
	AranStage1CombatStep                      Identity = 21001001
	AranStage1PolearmBooster                  Identity = 21001003
	AranStage2PolearmMastery                  Identity = 21100000
	AranStage2TripleSwing                     Identity = 21100001
	AranStage2FinalCharge                     Identity = 21100002
	AranStage2ComboSmash                      Identity = 21100004
	AranStage2ComboDrain                      Identity = 21100005
	AranStage2BodyPressure                    Identity = 21101003
	AranStage3ComboCritical                   Identity = 21110000
	AranStage3FullSwing                       Identity = 21110002
	AranStage3FinalToss                       Identity = 21110003
	AranStage3ComboFenrir                     Identity = 21110004
	AranStage3RollingSpin                     Identity = 21110006
	AranStage3FullSwingDoubleSwing            Identity = 21110007
	AranStage3FullSwingTripleSwing            Identity = 21110008
	AranStage3SmartKnockback                  Identity = 21111001
	AranStage3SnowCharge                      Identity = 21111005
	AranStage4HighMastery                     Identity = 21120001
	AranStage4OverSwing                       Identity = 21120002
	AranStage4HighDefense                     Identity = 21120004
	AranStage4FinalBlow                       Identity = 21120005
	AranStage4ComboTempest                    Identity = 21120006
	AranStage4ComboBarrier                    Identity = 21120007
	AranStage4OverswingDoubleSwing            Identity = 21120009
	AranStage4OverswingTripleSwing            Identity = 21120010
	AranStage4MapleWarrior                    Identity = 21121000
	AranStage4FreezeStanding                  Identity = 21121003
	AranStage4HerosWill                       Identity = 21121008
	EvanStage1DragonSoul                      Identity = 22000000
	EvanStage1MagicMissile                    Identity = 22001001
	EvanStage2FireCircle                      Identity = 22101000
	EvanStage2Teleport                        Identity = 22101001
	EvanStage3LightningBolt                   Identity = 22111000
	EvanStage3MagicGuard                      Identity = 22111001
	EvanStage4IceBreath                       Identity = 22121000
	EvanStage4ElementalReset                  Identity = 22121001
	EvanStage5MagicFlare                      Identity = 22131000
	EvanStage5MagicShield                     Identity = 22131001
	EvanStage6CriticalMagic                   Identity = 22140000
	EvanStage6DragonThrust                    Identity = 22141001
	EvanStage6MagicBooster                    Identity = 22141002
	EvanStage6Slow                            Identity = 22141003
	EvanStage7MagicAmplification              Identity = 22150000
	EvanStage7FireBreath                      Identity = 22151001
	EvanStage7KillerWings                     Identity = 22151002
	EvanStage7MagicResistance                 Identity = 22151003
	EvanStage8DragonFury                      Identity = 22160000
	EvanStage8Earthquake                      Identity = 22161001
	EvanStage8PhantomImprint                  Identity = 22161002
	EvanStage8RecoveryAura                    Identity = 22161003
	EvanStage9MagicMastery                    Identity = 22170001
	EvanStage9MapleWarrior                    Identity = 22171000
	EvanStage9Illusion                        Identity = 22171002
	EvanStage9FlameWheel                      Identity = 22171003
	EvanStage9HerosWill                       Identity = 22171004
	EvanStage10BlessingOfTheOnyx              Identity = 22181000
	EvanStage10Blaze                          Identity = 22181001
	EvanStage10DarkFog                        Identity = 22181002
	EvanStage10SoulStone                      Identity = 22181003
)

var identityNames = map[Identity]string{
	BeginnerThreeSnails:                       "Beginner Three Snails",
	BeginnerRecovery:                          "Beginner Recovery",
	BeginnerNimbleFeet:                        "Beginner Nimble Feet",
	BeginnerSoulOfCraftsman:                   "Beginner Soul Of Craftsman",
	BeginnerMonsterRiding:                     "Beginner Monster Riding",
	BeginnerEchoOfHero:                        "Beginner Echo Of Hero",
	BeginnerJumpDown:                          "Beginner Jump Down",
	BeginnerMaker:                             "Beginner Maker",
	BeginnerMultiPet:                          "Beginner Multi Pet",
	BeginnerBamboo:                            "Beginner Bamboo",
	BeginnerInvincible:                        "Beginner Invincible",
	BeginnerBerserk:                           "Beginner Berserk",
	BeginnerBlessOfNymph:                      "Beginner Bless Of Nymph",
	BeginnerSpaceShip:                         "Beginner Space Ship",
	BeginnerYetiMount1:                        "Beginner Yeti Mount1",
	BeginnerYetiMount2:                        "Beginner Yeti Mount2",
	BeginnerBroomstick:                        "Beginner Broomstick",
	BeginnerBalrogMount:                       "Beginner Balrog Mount",
	WarriorImprovedHpRecovery:                 "Warrior Improved Hp Recovery",
	WarriorImprovedMaxHpIncrease:              "Warrior Improved Max Hp Increase",
	WarriorEndure:                             "Warrior Endure",
	WarriorHpBoost:                            "HP Boost",
	WarriorIronBody:                           "Warrior Iron Body",
	WarriorPowerStrike:                        "Warrior Power Strike",
	WarriorSlashBlast:                         "Warrior Slash Blast",
	NoblesseSpaceShip:                         "Noblesse Space Ship",
	FighterSwordMastery:                       "Fighter Sword Mastery",
	FighterAxeMastery:                         "Fighter Axe Mastery",
	FighterFinalAttackSword:                   "Fighter Final Attack Sword",
	FighterFinalAttackAxe:                     "Fighter Final Attack Axe",
	FighterEnhancedBasics:                     "Enhanced Basics",
	FighterSwordBooster:                       "Fighter Sword Booster",
	FighterAxeBooster:                         "Fighter Axe Booster",
	FighterRage:                               "Fighter Rage",
	FighterPowerGuard:                         "Fighter Power Guard",
	FighterGroundSmash:                        "Ground Smash",
	CrusaderImprovingMpRecovery:               "Crusader Improving Mp Recovery",
	CrusaderShieldMastery:                     "Crusader Shield Mastery",
	CrusaderComboAttack:                       "Crusader Combo Attack",
	CrusaderPanicSword:                        "Crusader Panic Sword",
	CrusaderPanicAxe:                          "Crusader Panic Axe",
	CrusaderComaSword:                         "Crusader Coma Sword",
	CrusaderComaAxe:                           "Crusader Coma Axe",
	CrusaderArmorCrash:                        "Crusader Armor Crash",
	CrusaderShout:                             "Crusader Shout",
	HeroAdvancedComboAttack:                   "Hero Advanced Combo Attack",
	HeroAchilles:                              "Hero Achilles",
	HeroGuardian:                              "Hero Guardian",
	HeroCombatMastery:                         "Combat Mastery",
	HeroMapleWarrior:                          "Hero Maple Warrior",
	HeroMonsterMagnet:                         "Hero Monster Magnet",
	HeroPowerStance:                           "Hero Power Stance",
	HeroRush:                                  "Hero Rush",
	HeroBrandish:                              "Hero Brandish",
	HeroEnrage:                                "Hero Enrage",
	HeroHerosWill:                             "Hero Heros Will",
	PageSwordMastery:                          "Page Sword Mastery",
	PageBluntWeaponMastery:                    "Page Blunt Weapon Mastery",
	PageSwordFinalAttack:                      "Page Sword Final Attack",
	PageBluntFinalAttack:                      "Page Blunt Final Attack",
	PageSwordBooster:                          "Page Sword Booster",
	PageBluntWeaponBooster:                    "Page Blunt Weapon Booster",
	PageThreaten:                              "Page Threaten",
	PagePowerGuard:                            "Page Power Guard",
	WhiteKnightImprovingMpRecovery:            "White Knight Improving Mp Recovery",
	WhiteKnightShieldMastery:                  "White Knight Shield Mastery",
	WhiteKnightChargedBlow:                    "White Knight Charged Blow",
	WhiteKnightFireChargeSword:                "White Knight Fire Charge Sword",
	WhiteKnightFlameChargeBluntWeapon:         "White Knight Flame Charge Blunt Weapon",
	WhiteKnightIceChargeSword:                 "White Knight Ice Charge Sword",
	WhiteKnightBlizzardChargeBluntWeapon:      "White Knight Blizzard Charge Blunt Weapon",
	WhiteKnightThunderChargeSword:             "White Knight Thunder Charge Sword",
	WhiteKnightLightningChargeBluntWeapon:     "White Knight Lightning Charge Blunt Weapon",
	WhiteKnightMagicCrash:                     "White Knight Magic Crash",
	PaladinAchilles:                           "Paladin Achilles",
	PaladinGuardian:                           "Paladin Guardian",
	PaladinAdvancedCharge:                     "Paladin Advanced Charge",
	PaladinMapleWarrior:                       "Paladin Maple Warrior",
	PaladinMonsterMagnet:                      "Paladin Monster Magnet",
	PaladinPowerStance:                        "Paladin Power Stance",
	PaladinHolyChargeSword:                    "Paladin Holy Charge Sword",
	PaladinDivineChargeBluntWeapon:            "Paladin Divine Charge Blunt Weapon",
	PaladinRush:                               "Paladin Rush",
	PaladinBlast:                              "Paladin Blast",
	PaladinHeavensHammer:                      "Paladin Heavens Hammer",
	PaladinHerosWill:                          "Paladin Heros Will",
	SpearmanSpearMastery:                      "Spearman Spear Mastery",
	SpearmanPolearmMastery:                    "Spearman Polearm Mastery",
	SpearmanFinalAttackSpear:                  "Spearman Final Attack Spear",
	SpearmanFinalAttackPolearm:                "Spearman Final Attack Polearm",
	SpearmanSpearBooster:                      "Spearman Spear Booster",
	SpearmanPolearmBooster:                    "Spearman Polearm Booster",
	SpearmanIronWill:                          "Spearman Iron Will",
	SpearmanHyperBody:                         "Spearman Hyper Body",
	DragonKnightElementalResistance:           "Dragon Knight Elemental Resistance",
	DragonKnightSpearCrusher:                  "Dragon Knight Spear Crusher",
	DragonKnightPolearmCrusher:                "Dragon Knight Polearm Crusher",
	DragonKnightDragonFurySpear:               "Dragon Knight Dragon Fury Spear",
	DragonKnightDragonFuryPolearm:             "Dragon Knight Dragon Fury Polearm",
	DragonKnightSacrifice:                     "Dragon Knight Sacrifice",
	DragonKnightDragonRoar:                    "Dragon Knight Dragon Roar",
	DragonKnightPowerCrash:                    "Dragon Knight Power Crash",
	DragonKnightDragonBlood:                   "Dragon Knight Dragon Blood",
	DarkKnightAchilles:                        "Dark Knight Achilles",
	DarkKnightBerserk:                         "Dark Knight Berserk",
	DarkKnightAuraOfTheBeholder:               "Dark Knight Aura Of The Beholder",
	DarkKnightHexOfTheBeholder:                "Dark Knight Hex Of The Beholder",
	DarkKnightMapleWarrior:                    "Dark Knight Maple Warrior",
	DarkKnightMonsterMagnet:                   "Dark Knight Monster Magnet",
	DarkKnightPowerStance:                     "Dark Knight Power Stance",
	DarkKnightRush:                            "Dark Knight Rush",
	DarkKnightBeholder:                        "Dark Knight Beholder",
	DarkKnightHerosWill:                       "Dark Knight Heros Will",
	MagicianImprovedMpRecovery:                "Magician Improved Mp Recovery",
	MagicianImprovedMaxMpIncrease:             "Magician Improved Max Mp Increase",
	MagicianMpBoost:                           "MP Boost",
	MagicianMagicGuard:                        "Magician Magic Guard",
	MagicianMagicArmor:                        "Magician Magic Armor",
	MagicianEnergyBolt:                        "Magician Energy Bolt",
	MagicianMagicClaw:                         "Magician Magic Claw",
	FirePoisonWizardMpEater:                   "Fire Poison Wizard Mp Eater",
	FirePoisonWizardMeditation:                "Fire Poison Wizard Meditation",
	FirePoisonWizardTeleport:                  "Fire Poison Wizard Teleport",
	FirePoisonWizardSlow:                      "Fire Poison Wizard Slow",
	FirePoisonWizardFireArrow:                 "Fire Poison Wizard Fire Arrow",
	FirePoisonWizardPoisonBreath:              "Fire Poison Wizard Poison Breath",
	FirePoisonMagicianPartialResistance:       "Fire Poison Magician Partial Resistance",
	FirePoisonMagicianElementAmplification:    "Fire Poison Magician Element Amplification",
	FirePoisonMagicianExplosion:               "Fire Poison Magician Explosion",
	FirePoisonMagicianPoisonMist:              "Fire Poison Magician Poison Mist",
	FirePoisonMagicianSeal:                    "Fire Poison Magician Seal",
	FirePoisonMagicianSpellBooster:            "Fire Poison Magician Spell Booster",
	FirePoisonMagicianElementComposition:      "Fire Poison Magician Element Composition",
	FirePoisonArchMagicianMapleWarrior:        "Fire Poison Arch Magician Maple Warrior",
	FirePoisonArchMagicianBigBang:             "Fire Poison Arch Magician Big Bang",
	FirePoisonArchMagicianManaReflection:      "Fire Poison Arch Magician Mana Reflection",
	FirePoisonArchMagicianFireDemon:           "Fire Poison Arch Magician Fire Demon",
	FirePoisonArchMagicianInfinity:            "Fire Poison Arch Magician Infinity",
	FirePoisonArchMagicianElquines:            "Fire Poison Arch Magician Elquines",
	FirePoisonArchMagicianParalyze:            "Fire Poison Arch Magician Paralyze",
	FirePoisonArchMagicianMeteorShower:        "Fire Poison Arch Magician Meteor Shower",
	FirePoisonArchMagicianHerosWill:           "Fire Poison Arch Magician Heros Will",
	IceLightningWizardMpEater:                 "Ice Lightning Wizard Mp Eater",
	IceLightningWizardMeditation:              "Ice Lightning Wizard Meditation",
	IceLightningWizardTeleport:                "Ice Lightning Wizard Teleport",
	IceLightningWizardSlow:                    "Ice Lightning Wizard Slow",
	IceLightningWizardColdBeam:                "Ice Lightning Wizard Cold Beam",
	IceLightningWizardThunderBolt:             "Ice Lightning Wizard Thunder Bolt",
	IceLightningMagicianPartialResistance:     "Ice Lightning Magician Partial Resistance",
	IceLightningMagicianElementAmplification:  "Ice Lightning Magician Element Amplification",
	IceLightningMagicianIceStrike:             "Ice Lightning Magician Ice Strike",
	IceLightningMagicianThunderSpear:          "Ice Lightning Magician Thunder Spear",
	IceLightningMagicianSeal:                  "Ice Lightning Magician Seal",
	IceLightningMagicianSpellBooster:          "Ice Lightning Magician Spell Booster",
	IceLightningMagicianElementComposition:    "Ice Lightning Magician Element Composition",
	IceLightningArchMagicianMapleWarrior:      "Ice Lightning Arch Magician Maple Warrior",
	IceLightningArchMagicianBigBang:           "Ice Lightning Arch Magician Big Bang",
	IceLightningArchMagicianManaReflection:    "Ice Lightning Arch Magician Mana Reflection",
	IceLightningArchMagicianIceDemon:          "Ice Lightning Arch Magician Ice Demon",
	IceLightningArchMagicianInfinity:          "Ice Lightning Arch Magician Infinity",
	IceLightningArchMagicianIfrit:             "Ice Lightning Arch Magician Ifrit",
	IceLightningArchMagicianChainLightning:    "Ice Lightning Arch Magician Chain Lightning",
	IceLightningArchMagicianBlizzard:          "Ice Lightning Arch Magician Blizzard",
	IceLightningArchMagicianHerosWill:         "Ice Lightning Arch Magician Heros Will",
	ClericMpEater:                             "Cleric Mp Eater",
	ClericTeleport:                            "Cleric Teleport",
	ClericHeal:                                "Cleric Heal",
	ClericInvincible:                          "Cleric Invincible",
	ClericBless:                               "Cleric Bless",
	ClericHolyArrow:                           "Cleric Holy Arrow",
	PriestElementalResistance:                 "Priest Elemental Resistance",
	PriestDispel:                              "Priest Dispel",
	PriestMysticDoor:                          "Priest Mystic Door",
	PriestHolySymbol:                          "Priest Holy Symbol",
	PriestShiningRay:                          "Priest Shining Ray",
	PriestDoom:                                "Priest Doom",
	PriestSummonDragon:                        "Priest Summon Dragon",
	BishopMapleWarrior:                        "Bishop Maple Warrior",
	BishopBigBang:                             "Bishop Big Bang",
	BishopManaReflection:                      "Bishop Mana Reflection",
	BishopBahamut:                             "Bishop Bahamut",
	BishopInfinity:                            "Bishop Infinity",
	BishopHolyShield:                          "Bishop Holy Shield",
	BishopResurrection:                        "Bishop Resurrection",
	BishopAngelRay:                            "Bishop Angel Ray",
	BishopGenesis:                             "Bishop Genesis",
	BishopHerosWill:                           "Bishop Heros Will",
	BowmanTheBlessingOfAmazon:                 "Bowman The Blessing Of Amazon",
	BowmanCriticalShot:                        "Bowman Critical Shot",
	BowmanTheEyeOfAmazon:                      "Bowman The Eye Of Amazon",
	BowmanFocus:                               "Bowman Focus",
	BowmanArrowBlow:                           "Bowman Arrow Blow",
	BowmanDoubleShot:                          "Bowman Double Shot",
	HunterBowMastery:                          "Hunter Bow Mastery",
	HunterFinalAttackBow:                      "Hunter Final Attack Bow",
	HunterBowBooster:                          "Hunter Bow Booster",
	HunterPowerKnockBack:                      "Hunter Power Knock Back",
	HunterSoulArrowBow:                        "Hunter Soul Arrow Bow",
	HunterArrowBombBow:                        "Hunter Arrow Bomb Bow",
	RangerThrust:                              "Ranger Thrust",
	RangerMortalBlow:                          "Ranger Mortal Blow",
	RangerPuppet:                              "Ranger Puppet",
	RangerInferno:                             "Ranger Inferno",
	RangerArrowRain:                           "Ranger Arrow Rain",
	RangerSilverHawk:                          "Ranger Silver Hawk",
	RangerStrafe:                              "Ranger Strafe",
	BowmasterBowExpert:                        "Bowmaster Bow Expert",
	BowmasterMapleWarrior:                     "Bowmaster Maple Warrior",
	BowmasterSharpEyes:                        "Bowmaster Sharp Eyes",
	BowmasterDragonsBreath:                    "Bowmaster Dragons Breath",
	BowmasterHurricane:                        "Bowmaster Hurricane",
	BowmasterPhoenix:                          "Bowmaster Phoenix",
	BowmasterHamstring:                        "Bowmaster Hamstring",
	BowmasterConcentrate:                      "Bowmaster Concentrate",
	BowmasterHerosWill:                        "Bowmaster Heros Will",
	CrossbowmanCrossbowMastery:                "Crossbowman Crossbow Mastery",
	CrossbowmanFinalAttackCrossbow:            "Crossbowman Final Attack Crossbow",
	CrossbowmanCrossbowBooster:                "Crossbowman Crossbow Booster",
	CrossbowmanPowerKnockBack:                 "Crossbowman Power Knock Back",
	CrossbowmanSoulArrowCrossbow:              "Crossbowman Soul Arrow Crossbow",
	CrossbowmanIronArrowCrossbow:              "Crossbowman Iron Arrow Crossbow",
	SniperThrust:                              "Sniper Thrust",
	SniperMortalBlow:                          "Sniper Mortal Blow",
	SniperPuppet:                              "Sniper Puppet",
	SniperBlizzard:                            "Sniper Blizzard",
	SniperArrowEruption:                       "Sniper Arrow Eruption",
	SniperGoldenEagle:                         "Sniper Golden Eagle",
	SniperStrafe:                              "Sniper Strafe",
	MarksmanMarksmanBoost:                     "Marksman Marksman Boost",
	MarksmanMapleWarrior:                      "Marksman Maple Warrior",
	MarksmanPiercingArrow:                     "Marksman Piercing Arrow",
	MarksmanSharpEyes:                         "Marksman Sharp Eyes",
	MarksmanDragonsBreath:                     "Marksman Dragons Breath",
	MarksmanFrostprey:                         "Marksman Frostprey",
	MarksmanBlind:                             "Marksman Blind",
	MarksmanSnipe:                             "Marksman Snipe",
	MarksmanHerosWill:                         "Marksman Heros Will",
	RogueNimbleBody:                           "Rogue Nimble Body",
	RogueKeenEyes:                             "Rogue Keen Eyes",
	RogueDisorder:                             "Rogue Disorder",
	RogueDarkSight:                            "Rogue Dark Sight",
	RogueDoubleStab:                           "Rogue Double Stab",
	RogueLuckySeven:                           "Rogue Lucky Seven",
	AssassinClawMastery:                       "Assassin Claw Mastery",
	AssassinCriticalThrow:                     "Assassin Critical Throw",
	AssassinEndure:                            "Assassin Endure",
	AssassinShadowResistance:                  "Shadow Resistance",
	AssassinClawBooster:                       "Assassin Claw Booster",
	AssassinHaste:                             "Assassin Haste",
	AssassinDrain:                             "Assassin Drain",
	HermitAlchemist:                           "Hermit Alchemist",
	HermitMesoUp:                              "Hermit Meso Up",
	HermitShadowPartner:                       "Hermit Shadow Partner",
	HermitShadowWeb:                           "Hermit Shadow Web",
	HermitShadowMeso:                          "Hermit Shadow Meso",
	HermitAvenger:                             "Hermit Avenger",
	HermitFlashJump:                           "Hermit Flash Jump",
	NightLordShadowShifter:                    "Night Lord Shadow Shifter",
	NightLordVenomousStar:                     "Night Lord Venomous Star",
	NightLordMapleWarrior:                     "Night Lord Maple Warrior",
	NightLordTaunt:                            "Night Lord Taunt",
	NightLordNinjaAmbush:                      "Night Lord Ninja Ambush",
	NightLordShadowStars:                      "Night Lord Shadow Stars",
	NightLordTripleThrow:                      "Night Lord Triple Throw",
	NightLordNinjaStorm:                       "Night Lord Ninja Storm",
	NightLordHerosWill:                        "Night Lord Heros Will",
	BanditDaggerMastery:                       "Bandit Dagger Mastery",
	BanditEndure:                              "Bandit Endure",
	BanditShadowResistance:                    "Shadow Resistance",
	BanditDaggerBooster:                       "Bandit Dagger Booster",
	BanditHaste:                               "Bandit Haste",
	BanditSteal:                               "Bandit Steal",
	BanditSavageBlow:                          "Bandit Savage Blow",
	ChiefBanditShieldMastery:                  "Chief Bandit Shield Mastery",
	ChiefBanditChakra:                         "Chief Bandit Chakra",
	ChiefBanditAssaulter:                      "Chief Bandit Assaulter",
	ChiefBanditPickpocket:                     "Chief Bandit Pickpocket",
	ChiefBanditBandOfThieves:                  "Chief Bandit Band Of Thieves",
	ChiefBanditMesoGuard:                      "Chief Bandit Meso Guard",
	ChiefBanditMesoExplosion:                  "Chief Bandit Meso Explosion",
	ShadowerShadowShifter:                     "Shadower Shadow Shifter",
	ShadowerVenomousStab:                      "Shadower Venomous Stab",
	ShadowerMapleWarrior:                      "Shadower Maple Warrior",
	ShadowerAssassinate:                       "Shadower Assassinate",
	ShadowerTaunt:                             "Shadower Taunt",
	ShadowerNinjaAmbush:                       "Shadower Ninja Ambush",
	ShadowerSmokescreen:                       "Shadower Smokescreen",
	ShadowerBoomerangStep:                     "Shadower Boomerang Step",
	ShadowerHerosWill:                         "Shadower Heros Will",
	BladeRecruitKataraMastery:                 "Katara Mastery",
	BladeRecruitTripleStab:                    "Triple Stab",
	BladeRecruitKataraBooster:                 "Katara Booster",
	BladeAcolyteEndure:                        "Endure",
	BladeAcolyteShadowResistance:              "Shadow Resistance",
	BladeAcolyteSelfHaste:                     "Self Haste",
	BladeAcolyteFatalBlow:                     "Fatal Blow",
	BladeAcolyteSlashStorm:                    "Slash Storm",
	BladeSpecialistTornadoSpin:                "Tornado Spin",
	BladeSpecialistTornadoSpinAttack:          "Tornado Spin (Attack)",
	BladeSpecialistFlashbang:                  "Flashbang",
	BladeSpecialistFlashJump:                  "Flash Jump",
	BladeLordAdvancedDarkSight:                "Advanced Dark Sight",
	BladeLordBloodyStorm:                      "Bloody Storm",
	BladeLordMirrorImage:                      "Mirror Image",
	BladeLordOwlSpirit:                        "Owl Spirit",
	BladeLordUpperStab:                        "Upper Stab",
	BladeLordFlyingAssaulter:                  "Flying Assaulter",
	BladeMasterVenom:                          "Venom",
	BladeMasterMapleWarrior:                   "Maple Warrior",
	BladeMasterFinalCut:                       "Final Cut",
	BladeMasterMonsterBomb:                    "Monster Bomb",
	BladeMasterSuddenRaid:                     "Sudden Raid",
	BladeMasterChainsOfHell:                   "Chains of Hell",
	BladeMasterMirroredTarget:                 "Mirrored Target",
	BladeMasterThorns:                         "Thorns",
	BladeMasterHerosWill:                      "Hero's Will",
	PirateBulletTime:                          "Pirate Bullet Time",
	PirateFlashFist:                           "Pirate Flash Fist",
	PirateSommersaultKick:                     "Pirate Sommersault Kick",
	PirateDoubleShot:                          "Pirate Double Shot",
	PirateDash:                                "Pirate Dash",
	BrawlerImproveMaxHp:                       "Brawler Improve Max Hp",
	BrawlerKnucklerMastery:                    "Brawler Knuckler Mastery",
	BrawlerCriticalPunch:                      "Critical Punch",
	BrawlerHpBoost:                            "HP Boost",
	BrawlerBackspinBlow:                       "Brawler Backspin Blow",
	BrawlerDoubleUppercut:                     "Brawler Double Uppercut",
	BrawlerCorkscrewBlow:                      "Brawler Corkscrew Blow",
	BrawlerMPRecovery:                         "Brawler MP Recovery",
	BrawlerKnucklerBooster:                    "Brawler Knuckler Booster",
	BrawlerOakBarrel:                          "Brawler Oak Barrel",
	MarauderStunMastery:                       "Marauder Stun Mastery",
	MarauderEnergyCharge:                      "Marauder Energy Charge",
	MarauderEnergyBlast:                       "Marauder Energy Blast",
	MarauderEnergyDrain:                       "Marauder Energy Drain",
	MarauderTransformation:                    "Marauder Transformation",
	MarauderShockwave:                         "Marauder Shockwave",
	BuccaneerMapleWarrior:                     "Buccaneer Maple Warrior",
	BuccaneerDragonStrike:                     "Buccaneer Dragon Strike",
	BuccaneerEnergyOrb:                        "Buccaneer Energy Orb",
	BuccaneerSuperTransformation:              "Buccaneer Super Transformation",
	BuccaneerDemolition:                       "Buccaneer Demolition",
	BuccaneerSnatch:                           "Buccaneer Snatch",
	BuccaneerBarrage:                          "Buccaneer Barrage",
	BuccaneerPiratesRage:                      "Buccaneer Pirates Rage",
	BuccaneerSpeedInfusion:                    "Buccaneer Speed Infusion",
	BuccaneerTimeLeap:                         "Buccaneer Time Leap",
	GunslingerGunMastery:                      "Gunslinger Gun Mastery",
	GunslingerInvisibleShot:                   "Gunslinger Invisible Shot",
	GunslingerGrenade:                         "Gunslinger Grenade",
	GunslingerGunBooster:                      "Gunslinger Gun Booster",
	GunslingerBlankShot:                       "Gunslinger Blank Shot",
	GunslingerWings:                           "Gunslinger Wings",
	GunslingerRecoilShot:                      "Gunslinger Recoil Shot",
	OutlawBurstFire:                           "Outlaw Burst Fire",
	OutlawOctopus:                             "Outlaw Octopus",
	OutlawGaviota:                             "Outlaw Gaviota",
	OutlawFlamethrower:                        "Outlaw Flamethrower",
	OutlawIceSplitter:                         "Outlaw Ice Splitter",
	OutlawHomingBeacon:                        "Outlaw Homing Beacon",
	CorsairElementalBoost:                     "Corsair Elemental Boost",
	CorsairWrathOfTheOctopi:                   "Corsair Wrath Of The Octopi",
	CorsairBullseye:                           "Corsair Bullseye",
	CorsairMapleWarrior:                       "Corsair Maple Warrior",
	CorsairAerialStrike:                       "Corsair Aerial Strike",
	CorsairRapidFire:                          "Corsair Rapid Fire",
	CorsairBattleship:                         "Corsair Battleship",
	CorsairBattleshipCannon:                   "Corsair Battleship Cannon",
	CorsairBattleshipTorpedo:                  "Corsair Battleship Torpedo",
	CorsairHypnotize:                          "Corsair Hypnotize",
	CorsairSpeedInfusion:                      "Corsair Speed Infusion",
	MapleLeafBrigadierAntiMacro:               "Maple Leaf Brigadier Anti Macro",
	MapleLeafBrigadierTeleport:                "Maple Leaf Brigadier Teleport",
	GmHaste:                                   "Gm Haste",
	GmSuperDragonRoar:                         "Gm Super Dragon Roar",
	GmTeleport:                                "Gm Teleport",
	GmHide:                                    "Gm Hide",
	GmResurrection:                            "Gm Resurrection",
	SuperGmHealDispel:                         "Super Gm Heal Dispel",
	SuperGmHaste:                              "Super Gm Haste",
	SuperGmHolySymbol:                         "Super Gm Holy Symbol",
	SuperGmBless:                              "Super Gm Bless",
	SuperGmHide:                               "Super Gm Hide",
	SuperGmResurrection:                       "Super Gm Resurrection",
	SuperGmDragonRoar:                         "Super Gm Dragon Roar",
	SuperGmTeleport:                           "Super Gm Teleport",
	SuperGmHyperBody:                          "Super Gm Hyper Body",
	NoblesseThreeSnails:                       "Noblesse Three Snails",
	NoblesseRecovery:                          "Noblesse Recovery",
	NoblesseNimbleFeet:                        "Noblesse Nimble Feet",
	NoblesseSoulOfCraftsman:                   "Noblesse Soul Of Craftsman",
	NoblesseMonsterRiding:                     "Noblesse Monster Riding",
	NoblesseEchoOfHero:                        "Noblesse Echo Of Hero",
	NoblesseJumpDown:                          "Noblesse Jump Down",
	NoblesseMaker:                             "Noblesse Maker",
	NoblesseMultiPet:                          "Noblesse Multi Pet",
	NoblesseBamboo:                            "Noblesse Bamboo",
	NoblesseInvincible:                        "Noblesse Invincible",
	NoblesseBerserk:                           "Noblesse Berserk",
	NoblesseBlessOfNymph:                      "Noblesse Bless Of Nymph",
	NoblesseYetiMount1:                        "Noblesse Yeti Mount1",
	NoblesseYetiMount2:                        "Noblesse Yeti Mount2",
	NoblesseBroomstick:                        "Noblesse Broomstick",
	NoblesseBalrogMount:                       "Noblesse Balrog Mount",
	DawnWarriorStage1MaxHpEnhancement:         "Max HP Enhancement",
	DawnWarriorStage1ImprovedMaxHpIncrease:    "Dawn Warrior Stage1 Improved Max Hp Increase",
	DawnWarriorStage1IronBody:                 "Dawn Warrior Stage1 Iron Body",
	DawnWarriorStage1PowerStrike:              "Dawn Warrior Stage1 Power Strike",
	DawnWarriorStage1SlashBlast:               "Dawn Warrior Stage1 Slash Blast",
	DawnWarriorStage1Soul:                     "Dawn Warrior Stage1 Soul",
	DawnWarriorStage2SwordMastery:             "Dawn Warrior Stage2 Sword Mastery",
	DawnWarriorStage2SwordBooster:             "Dawn Warrior Stage2 Sword Booster",
	DawnWarriorStage2FinalAttackSword:         "Dawn Warrior Stage2 Final Attack Sword",
	DawnWarriorStage2Rage:                     "Dawn Warrior Stage2 Rage",
	DawnWarriorStage2SoulBlade:                "Dawn Warrior Stage2 Soul Blade",
	DawnWarriorStage2SoulRush:                 "Dawn Warrior Stage2 Soul Rush",
	DawnWarriorStage3ImprovedMpRecovery:       "Dawn Warrior Stage3 Improved Mp Recovery",
	DawnWarriorStage3AdvancedCombo:            "Dawn Warrior Stage3 Advanced Combo",
	DawnWarriorStage3ComboAttack:              "Dawn Warrior Stage3 Combo Attack",
	DawnWarriorStage3Panic:                    "Dawn Warrior Stage3 Panic",
	DawnWarriorStage3Coma:                     "Dawn Warrior Stage3 Coma",
	DawnWarriorStage3Brandish:                 "Dawn Warrior Stage3 Brandish",
	DawnWarriorStage3SoulDriver:               "Dawn Warrior Stage3 Soul Driver",
	DawnWarriorStage3SoulCharge:               "Dawn Warrior Stage3 Soul Charge",
	BlazeWizardStage1IncreasingMaxMp:          "Increasing Max MP",
	BlazeWizardStage1ImprovedMaxMpIncrease:    "Blaze Wizard Stage1 Improved Max Mp Increase",
	BlazeWizardStage1MagicGuard:               "Blaze Wizard Stage1 Magic Guard",
	BlazeWizardStage1MagicArmor:               "Blaze Wizard Stage1 Magic Armor",
	BlazeWizardStage1MagicClaw:                "Blaze Wizard Stage1 Magic Claw",
	BlazeWizardStage1Flame:                    "Blaze Wizard Stage1 Flame",
	BlazeWizardStage3SpellMastery:             "Blaze Wizard Stage3 Spell Mastery",
	BlazeWizardStage2Meditation:               "Blaze Wizard Stage2 Meditation",
	BlazeWizardStage2Slow:                     "Blaze Wizard Stage2 Slow",
	BlazeWizardStage2FireArrow:                "Blaze Wizard Stage2 Fire Arrow",
	BlazeWizardStage2Teleport:                 "Blaze Wizard Stage2 Teleport",
	BlazeWizardStage2SpellBooster:             "Blaze Wizard Stage2 Spell Booster",
	BlazeWizardStage2ElementalReset:           "Blaze Wizard Stage2 Elemental Reset",
	BlazeWizardStage2FirePillar:               "Blaze Wizard Stage2 Fire Pillar",
	BlazeWizardStage3ElementResistance:        "Blaze Wizard Stage3 Element Resistance",
	BlazeWizardStage3ElementAmplification:     "Blaze Wizard Stage3 Element Amplification",
	BlazeWizardStage3Seal:                     "Blaze Wizard Stage3 Seal",
	BlazeWizardStage3MeteorShower:             "Blaze Wizard Stage3 Meteor Shower",
	BlazeWizardStage3Ifrit:                    "Blaze Wizard Stage3 Ifrit",
	BlazeWizardStage3FlameGear:                "Blaze Wizard Stage3 Flame Gear",
	BlazeWizardStage3FireStrike:               "Blaze Wizard Stage3 Fire Strike",
	WindArcherStage1CriticalShot:              "Wind Archer Stage1 Critical Shot",
	WindArcherStage1TheEyeOfAmazon:            "Wind Archer Stage1 The Eye Of Amazon",
	WindArcherStage1Focus:                     "Wind Archer Stage1 Focus",
	WindArcherStage1DoubleShot:                "Wind Archer Stage1 Double Shot",
	WindArcherStage1Storm:                     "Wind Archer Stage1 Storm",
	WindArcherStage2BowMastery:                "Wind Archer Stage2 Bow Mastery",
	WindArcherStage2Thrust:                    "Wind Archer Stage2 Thrust",
	WindArcherStage2BowBooster:                "Wind Archer Stage2 Bow Booster",
	WindArcherStage2FinalAttackBow:            "Wind Archer Stage2 Final Attack Bow",
	WindArcherStage2SoulArrow:                 "Wind Archer Stage2 Soul Arrow",
	WindArcherStage2StormBreak:                "Wind Archer Stage2 Storm Break",
	WindArcherStage2WindWalk:                  "Wind Archer Stage2 Wind Walk",
	WindArcherStage3BowExpert:                 "Wind Archer Stage3 Bow Expert",
	WindArcherStage3ArrowRain:                 "Wind Archer Stage3 Arrow Rain",
	WindArcherStage3Strafe:                    "Wind Archer Stage3 Strafe",
	WindArcherStage3Hurricane:                 "Wind Archer Stage3 Hurricane",
	WindArcherStage3Puppet:                    "Wind Archer Stage3 Puppet",
	WindArcherStage3EagleEye:                  "Wind Archer Stage3 Eagle Eye",
	WindArcherStage3WindPiercing:              "Wind Archer Stage3 Wind Piercing",
	WindArcherStage3WindShot:                  "Wind Archer Stage3 Wind Shot",
	NightWalkerStage1NimbleBody:               "Night Walker Stage1 Nimble Body",
	NightWalkerStage1KeenEyes:                 "Night Walker Stage1 Keen Eyes",
	NightWalkerStage1Disorder:                 "Night Walker Stage1 Disorder",
	NightWalkerStage1DarkSight:                "Night Walker Stage1 Dark Sight",
	NightWalkerStage1LuckySeven:               "Night Walker Stage1 Lucky Seven",
	NightWalkerStage1Darkness:                 "Night Walker Stage1 Darkness",
	NightWalkerStage2ClawMastery:              "Night Walker Stage2 Claw Mastery",
	NightWalkerStage2CriticalThrow:            "Night Walker Stage2 Critical Throw",
	NightWalkerStage2Vanish:                   "Night Walker Stage2 Vanish",
	NightWalkerStage2ClawBooster:              "Night Walker Stage2 Claw Booster",
	NightWalkerStage2Haste:                    "Night Walker Stage2 Haste",
	NightWalkerStage2FlashJump:                "Night Walker Stage2 Flash Jump",
	NightWalkerStage2Vampire:                  "Night Walker Stage2 Vampire",
	NightWalkerStage3Alchemist:                "Night Walker Stage3 Alchemist",
	NightWalkerStage3Venom:                    "Night Walker Stage3 Venom",
	NightWalkerStage3ShadowPartner:            "Night Walker Stage3 Shadow Partner",
	NightWalkerStage3ShadowWeb:                "Night Walker Stage3 Shadow Web",
	NightWalkerStage3Avenger:                  "Night Walker Stage3 Avenger",
	NightWalkerStage3TripleThrow:              "Night Walker Stage3 Triple Throw",
	NightWalkerStage3PoisonBomb:               "Night Walker Stage3 Poison Bomb",
	ThunderBreakerStage1QuickMotion:           "Thunder Breaker Stage1 Quick Motion",
	ThunderBreakerStage1FirstStrike:           "Thunder Breaker Stage1 First Strike",
	ThunderBreakerStage1SomersaultKick:        "Thunder Breaker Stage1 Somersault Kick",
	ThunderBreakerStage1Dash:                  "Thunder Breaker Stage1 Dash",
	ThunderBreakerStage1LightningSprite:       "Thunder Breaker Stage1 Lightning Sprite",
	ThunderBreakerStage2KnuckleMastery:        "Thunder Breaker Stage2 Knuckle Mastery",
	ThunderBreakerStage2EnergyCharge:          "Thunder Breaker Stage2 Energy Charge",
	ThunderBreakerStage2ImprovedMaxHpIncrease: "Thunder Breaker Stage2 Improved Max Hp Increase",
	ThunderBreakerStage2KnuckleBooster:        "Thunder Breaker Stage2 Knuckle Booster",
	ThunderBreakerStage2CorkscrewBlow:         "Thunder Breaker Stage2 Corkscrew Blow",
	ThunderBreakerStage2EnergyBlast:           "Thunder Breaker Stage2 Energy Blast",
	ThunderBreakerStage2LightningCharge:       "Thunder Breaker Stage2 Lightning Charge",
	ThunderBreakerStage3CriticalPunch:         "Thunder Breaker Stage3 Critical Punch",
	ThunderBreakerStage3EnergyDrain:           "Thunder Breaker Stage3 Energy Drain",
	ThunderBreakerStage3Transformation:        "Thunder Breaker Stage3 Transformation",
	ThunderBreakerStage3ShockWave:             "Thunder Breaker Stage3 Shock Wave",
	ThunderBreakerStage3Barrage:               "Thunder Breaker Stage3 Barrage",
	ThunderBreakerStage3SpeedInfusion:         "Thunder Breaker Stage3 Speed Infusion",
	ThunderBreakerStage3Spark:                 "Thunder Breaker Stage3 Spark",
	ThunderBreakerStage3SharkWave:             "Thunder Breaker Stage3 Shark Wave",
	LegendBlessOfNymph:                        "Legend Bless Of Nymph",
	LegendComboAbility:                        "Legend Combo Ability",
	LegendThreeSnails:                         "Legend Three Snails",
	LegendRecovery:                            "Legend Recovery",
	LegendNimbleFeet:                          "Legend Nimble Feet",
	LegendSoulOfCraftsman:                     "Legend Soul Of Craftsman",
	LegendMonsterRiding:                       "Legend Monster Riding",
	LegendEchoOfHero:                          "Legend Echo Of Hero",
	LegendDamageMeter:                         "Legend Damage Meter",
	LegendMaker:                               "Legend Maker",
	LegendBamboo:                              "Legend Bamboo",
	LegendInvincible:                          "Legend Invincible",
	LegendBerserk:                             "Legend Berserk",
	LegendYetiMount1:                          "Legend Yeti Mount1",
	LegendYetiMount2:                          "Legend Yeti Mount2",
	LegendBroomstick:                          "Legend Broomstick",
	LegendBalrogMount:                         "Legend Balrog Mount",
	EvanBlessOfNymph:                          "Evan Bless Of Nymph",
	EvanThreeSnails:                           "Evan Three Snails",
	EvanRecovery:                              "Evan Recovery",
	EvanNimbleFeet:                            "Evan Nimble Feet",
	EvanSoulOfCraftsman:                       "Evan Soul Of Craftsman",
	EvanMonsterRiding:                         "Evan Monster Riding",
	EvanEchoOfHero:                            "Evan Echo Of Hero",
	EvanDamageMeter:                           "Evan Damage Meter",
	EvanMaker:                                 "Evan Maker",
	EvanBamboo:                                "Evan Bamboo",
	EvanInvincible:                            "Evan Invincible",
	EvanBerserk:                               "Evan Berserk",
	AranStage1ComboAbility:                    "Aran Stage1 Combo Ability",
	AranStage1DoubleSwing:                     "Aran Stage1 Double Swing",
	AranStage1CombatStep:                      "Aran Stage1 Combat Step",
	AranStage1PolearmBooster:                  "Aran Stage1 Polearm Booster",
	AranStage2PolearmMastery:                  "Aran Stage2 Polearm Mastery",
	AranStage2TripleSwing:                     "Aran Stage2 Triple Swing",
	AranStage2FinalCharge:                     "Aran Stage2 Final Charge",
	AranStage2ComboSmash:                      "Aran Stage2 Combo Smash",
	AranStage2ComboDrain:                      "Aran Stage2 Combo Drain",
	AranStage2BodyPressure:                    "Aran Stage2 Body Pressure",
	AranStage3ComboCritical:                   "Aran Stage3 Combo Critical",
	AranStage3FullSwing:                       "Aran Stage3 Full Swing",
	AranStage3FinalToss:                       "Aran Stage3 Final Toss",
	AranStage3ComboFenrir:                     "Aran Stage3 Combo Fenrir",
	AranStage3RollingSpin:                     "Aran Stage3 Rolling Spin",
	AranStage3FullSwingDoubleSwing:            "Aran Stage3 Full Swing Double Swing",
	AranStage3FullSwingTripleSwing:            "Aran Stage3 Full Swing Triple Swing",
	AranStage3SmartKnockback:                  "Aran Stage3 Smart Knockback",
	AranStage3SnowCharge:                      "Aran Stage3 Snow Charge",
	AranStage4HighMastery:                     "Aran Stage4 High Mastery",
	AranStage4OverSwing:                       "Aran Stage4 Over Swing",
	AranStage4HighDefense:                     "Aran Stage4 High Defense",
	AranStage4FinalBlow:                       "Aran Stage4 Final Blow",
	AranStage4ComboTempest:                    "Aran Stage4 Combo Tempest",
	AranStage4ComboBarrier:                    "Aran Stage4 Combo Barrier",
	AranStage4OverswingDoubleSwing:            "Aran Stage4 Overswing Double Swing",
	AranStage4OverswingTripleSwing:            "Aran Stage4 Overswing Triple Swing",
	AranStage4MapleWarrior:                    "Aran Stage4 Maple Warrior",
	AranStage4FreezeStanding:                  "Aran Stage4 Freeze Standing",
	AranStage4HerosWill:                       "Aran Stage4 Heros Will",
	EvanStage1DragonSoul:                      "Evan Stage1 Dragon Soul",
	EvanStage1MagicMissile:                    "Evan Stage1 Magic Missile",
	EvanStage2FireCircle:                      "Evan Stage2 Fire Circle",
	EvanStage2Teleport:                        "Evan Stage2 Teleport",
	EvanStage3LightningBolt:                   "Evan Stage3 Lightning Bolt",
	EvanStage3MagicGuard:                      "Evan Stage3 Magic Guard",
	EvanStage4IceBreath:                       "Evan Stage4 Ice Breath",
	EvanStage4ElementalReset:                  "Evan Stage4 Elemental Reset",
	EvanStage5MagicFlare:                      "Evan Stage5 Magic Flare",
	EvanStage5MagicShield:                     "Evan Stage5 Magic Shield",
	EvanStage6CriticalMagic:                   "Evan Stage6 Critical Magic",
	EvanStage6DragonThrust:                    "Evan Stage6 Dragon Thrust",
	EvanStage6MagicBooster:                    "Evan Stage6 Magic Booster",
	EvanStage6Slow:                            "Evan Stage6 Slow",
	EvanStage7MagicAmplification:              "Evan Stage7 Magic Amplification",
	EvanStage7FireBreath:                      "Evan Stage7 Fire Breath",
	EvanStage7KillerWings:                     "Evan Stage7 Killer Wings",
	EvanStage7MagicResistance:                 "Evan Stage7 Magic Resistance",
	EvanStage8DragonFury:                      "Evan Stage8 Dragon Fury",
	EvanStage8Earthquake:                      "Evan Stage8 Earthquake",
	EvanStage8PhantomImprint:                  "Evan Stage8 Phantom Imprint",
	EvanStage8RecoveryAura:                    "Evan Stage8 Recovery Aura",
	EvanStage9MagicMastery:                    "Evan Stage9 Magic Mastery",
	EvanStage9MapleWarrior:                    "Evan Stage9 Maple Warrior",
	EvanStage9Illusion:                        "Evan Stage9 Illusion",
	EvanStage9FlameWheel:                      "Evan Stage9 Flame Wheel",
	EvanStage9HerosWill:                       "Evan Stage9 Heros Will",
	EvanStage10BlessingOfTheOnyx:              "Evan Stage10 Blessing Of The Onyx",
	EvanStage10Blaze:                          "Evan Stage10 Blaze",
	EvanStage10DarkFog:                        "Evan Stage10 Dark Fog",
	EvanStage10SoulStone:                      "Evan Stage10 Soul Stone",
}
