---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-guilds
  namespace: atlas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlas-guilds
  template:
    metadata:
      labels:
        app: atlas-guilds
    spec:
      containers:
      - name: guilds
        image: ghcr.io/chronicle20/atlas-guilds/atlas-guilds:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: atlas-env
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: DB_NAME
          value: "atlas-guilds"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: atlas-guilds
  namespace: atlas
spec:
  selector:
    app: atlas-guilds
  ports:
  - protocol: TCP
    port: 8080