#!/usr/bin/env bash
# Generates dev/cluster-infra-coordination/atlas-pr-cleanup-env.example.yaml
# from .github/config/services.json.
#
# Output: a ConfigMap manifest cluster-infra mirrors into the argocd
# namespace. NOT deployed from this repo; the file's purpose is
# review-time visibility plus a stable diff when services.json
# changes.
#
# ATLAS_SERVICES is the cleanup Job's image-cleanup target list,
# derived (sorted, joined by commas) from .github/config/services.json's
# services[*].name. All other ConfigMap fields are static (cluster
# infra hostnames, db-name list). Re-run after adding/removing
# services. CI fails the PR if the file is stale (see
# .github/workflows/pr-validation.yml).

set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
OUT="$ROOT/dev/cluster-infra-coordination/atlas-pr-cleanup-env.example.yaml"
SERVICES_JSON="$ROOT/.github/config/services.json"

mkdir -p "$(dirname "$OUT")"

# Sorted, comma-joined list of every service in services.json. We use
# every service entry regardless of type because the cleanup-Job's
# image-cleanup phase iterates ATLAS_SERVICES and 404s on
# non-published targets are tolerated by `|| true` semantics
# (see cleanup.sh do_drop_images).
ATLAS_SERVICES=$(jq -r '.services[].name' "$SERVICES_JSON" | sort | paste -sd, -)

# ATLAS_DB_NAMES is DERIVED from the single source of truth — the
# atlas-db-names configMapGenerator literal in
# deploy/k8s/overlays/pr/kustomization.yaml (the same list the
# wave0-create-dbs Job uses to CREATE the per-env databases). We extract
# it here rather than duplicate a hand-maintained literal, because that
# duplication silently drifted: atlas-mounts was never added to the
# cleanup list and atlas-mts was added here but never mirrored to the
# live cluster-infra ConfigMap, so both services' DBs leaked on every PR
# teardown (the DROP loop never named them). Deriving from the create
# list makes the teardown DROP set identical to the create set by
# construction; the existing CI staleness check on the generated example
# file catches any un-regenerated change.
KUSTOMIZATION="$ROOT/deploy/k8s/overlays/pr/kustomization.yaml"
# Parse defensively. The literal is conventionally unquoted
# (`- ATLAS_DB_NAMES=atlas-accounts ... atlas-tenants`), but strip a
# surrounding quote pair and any trailing inline comment so a future
# quoted/commented edit can't smuggle a corrupt token (e.g. a stray
# `atlas-tenants"`) into a DROP DATABASE statement and re-leak that DB.
raw="$(grep -m1 -E '^[[:space:]]*- ATLAS_DB_NAMES=' "$KUSTOMIZATION" \
    | sed -E 's/^[[:space:]]*- ATLAS_DB_NAMES=//; s/[[:space:]]*#.*$//; s/^["'\'']//; s/["'\'']$//')"
ATLAS_DB_NAMES="$(printf '%s' "$raw" | tr -s '[:space:]' ' ' | sed -E 's/^ //; s/ $//')"
: "${ATLAS_DB_NAMES:?failed to extract ATLAS_DB_NAMES from $KUSTOMIZATION}"
# Validate every token is a well-formed atlas-<svc> name. The `:?` guard
# above only rejects an EMPTY parse; a malformed-but-nonempty parse (wrong
# line, stray quote/comment) would otherwise emit a DROP list whose bad
# token no-ops at teardown and re-leaks its DB — the exact failure class
# this generator exists to prevent. Fail the generator (and thus CI) loudly.
for tok in $ATLAS_DB_NAMES; do
    printf '%s\n' "$tok" | grep -qE '^atlas-[a-z0-9-]+$' \
        || { echo "gen-cleanup-env.sh: refusing to emit malformed DB name '$tok' parsed from $KUSTOMIZATION" >&2; exit 1; }
done

cat > "$OUT" <<EOF
# Not deployed from this repo. Mirror into cluster-infra (argocd
# namespace). Generated by deploy/k8s/overlays/pr/scripts/gen-cleanup-env.sh
# from .github/config/services.json — do not edit by hand. Re-run the
# generator after adding/removing a service or a DB.
#
# The atlas-pr-cleanup PostDelete Job consumes this ConfigMap via
# envFrom in deploy/k8s/overlays/pr-cleanup/postdelete-cleanup.yaml.
apiVersion: v1
kind: ConfigMap
metadata:
  name: atlas-pr-cleanup-env
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: atlas-pr-cleanup
data:
  DB_HOST: postgres.home
  DB_PORT: "5432"
  BOOTSTRAP_SERVERS: kafka.home:9093
  REDIS_URL: redis.home:6379
  ATLAS_DB_NAMES: "${ATLAS_DB_NAMES}"
  ATLAS_SERVICES: "${ATLAS_SERVICES}"
  # Issue #596: per-tenant MinIO prefix cleanup. The cleanup Job's
  # drop-tenant-storage phase uses these to reach MinIO directly.
  # Credentials are read from a separate Secret (minio-root-creds,
  # reflected from the minio namespace).
  MINIO_ENDPOINT: minio.minio.svc.cluster.local:9000
EOF

echo "Wrote $OUT"
