#!/usr/bin/env bash
# Generates patches/consumer-group-env.yaml from the literal consumer-group
# strings declared in each service's main.go.
#
# Output: a list of strategic-merge patches, one per Deployment, each adding
# KAFKA_CONSUMER_GROUP="<literal> [PLACEHOLDER_ATLAS_ENV]" and
# ATLAS_ENV="PLACEHOLDER_ATLAS_ENV" to the container env. The
# PLACEHOLDER_ATLAS_ENV slot is rewritten by the Argo CD ApplicationSet
# at sync time.
#
# Re-run after adding/removing a service.

set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
OUT="$ROOT/deploy/k8s/overlays/pr/patches/consumer-group-env.yaml"
mkdir -p "$(dirname "$OUT")"

{
    echo '# Generated by deploy/k8s/overlays/pr/scripts/gen-consumer-group-patch.sh'
    echo '# Do not edit by hand. Re-run after adding/removing services.'
    echo ''

    while IFS= read -r f; do
        # Extract consumer-group literal. Two patterns are supported:
        #   1) consumerGroupId = consumergroup.Resolve("Account Service")
        #   2) const consumerGroupIdTemplate = "Channel Service - %s"
        # `|| true` keeps `set -e` happy when grep matches nothing.
        #
        # Note: pattern 2 services (atlas-channel, atlas-login) carry
        # the template at runtime. The emitted patch's
        # KAFKA_CONSUMER_GROUP value still contains a literal "%s" —
        # that "%s" is intentional and is now substituted at
        # consumer-registration time by libs/atlas-kafka/consumergroup
        # `Resolve(template, channelId)` (task-075). DO NOT strip the
        # "%s" here; the Go side needs it intact.
        literal=$(grep -E 'consumerGroupId.*=.*consumergroup\.Resolve\("[^"]+"\)' "$f" | head -1 | sed -E 's/.*consumergroup\.Resolve\("([^"]+)"\).*/\1/' || true)
        if [ -z "$literal" ]; then
            literal=$(grep -E 'consumerGroupId(Template)? *= *"' "$f" | head -1 | sed -E 's/.*"([^"]*)".*/\1/' || true)
        fi
        if [ -z "$literal" ]; then continue; fi

        # Derive deployment name from path:
        #   services/atlas-<svc>/atlas.com/<module>/main.go -> atlas-<svc>
        depname=$(echo "$f" | sed -E 's|^services/(atlas-[^/]+)/.*|\1|')

        # Skip when no base manifest exists (some services may not have one yet).
        if [ ! -f "$ROOT/deploy/k8s/base/$depname.yaml" ]; then continue; fi

        # Read the actual container[0].name from the base manifest. Container
        # names don't always match the service slug (e.g. atlas-account uses
        # 'account', atlas-asset-expiration uses 'asset-expiration').
        cname=$(yq eval-all 'select(.kind == "Deployment") | .spec.template.spec.containers[0].name' "$ROOT/deploy/k8s/base/$depname.yaml" | head -1)
        if [ -z "$cname" ] || [ "$cname" = "null" ]; then continue; fi

        cat <<EOF
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $depname
spec:
  template:
    spec:
      containers:
        - name: $cname
          env:
            - name: KAFKA_CONSUMER_GROUP
              value: "$literal [PLACEHOLDER_ATLAS_ENV]"
            - name: ATLAS_ENV
              value: "PLACEHOLDER_ATLAS_ENV"
EOF
    done < <(find services/atlas-*/atlas.com -maxdepth 2 -name 'main.go' | sort)
} > "$OUT"

echo "Wrote $(wc -l < "$OUT") lines to $OUT"
