#!/usr/bin/env bash
# Generates patches/db-name-suffix.yaml by reading each base Deployment's
# DB_NAME env var and emitting a strategic-merge patch suffixing it with
# -PLACEHOLDER_ATLAS_ENV. The PLACEHOLDER slot is rewritten by the Argo
# CD ApplicationSet at sync time.
#
# Services with no DB_NAME env var (e.g. atlas-assets, atlas-ui,
# atlas-ingress, atlas-query-aggregator, atlas-wz-extractor) are skipped.
#
# Re-run after adding/removing a service or changing its DB_NAME.

set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
OUT="$ROOT/deploy/k8s/overlays/pr/patches/db-name-suffix.yaml"
mkdir -p "$(dirname "$OUT")"

{
    echo '# Generated by deploy/k8s/overlays/pr/scripts/gen-db-name-suffix.sh'
    echo '# Do not edit by hand. Re-run after adding/removing services.'
    echo ''

    for f in "$ROOT"/deploy/k8s/base/atlas-*.yaml; do
        depname=$(basename "$f" .yaml)
        cname=$(yq eval-all 'select(.kind == "Deployment") | .spec.template.spec.containers[0].name' "$f" | head -1)
        db_name=$(yq eval-all 'select(.kind == "Deployment") | .spec.template.spec.containers[0].env[] | select(.name == "DB_NAME") | .value' "$f" | head -1)
        if [ -z "$cname" ] || [ "$cname" = "null" ] || [ -z "$db_name" ] || [ "$db_name" = "null" ]; then continue; fi

        cat <<EOF
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $depname
spec:
  template:
    spec:
      containers:
        - name: $cname
          env:
            - name: DB_NAME
              value: "${db_name}-PLACEHOLDER_ATLAS_ENV"
EOF
    done
} > "$OUT"

echo "Wrote $(wc -l < "$OUT") lines to $OUT"
