#!/usr/bin/env bash
# Generates dev/cluster-infra-coordination/atlas-pr-cleanup-env.example.yaml
# from .github/config/services.json.
#
# Output: a ConfigMap manifest cluster-infra mirrors into the argocd
# namespace. NOT deployed from this repo; the file's purpose is
# review-time visibility plus a stable diff when services.json
# changes.
#
# ATLAS_SERVICES is the cleanup Job's image-cleanup target list,
# derived (sorted, joined by commas) from .github/config/services.json's
# services[*].name. All other ConfigMap fields are static (cluster
# infra hostnames, db-name list). Re-run after adding/removing
# services. CI fails the PR if the file is stale (see
# .github/workflows/pr-validation.yml).

set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
OUT="$ROOT/dev/cluster-infra-coordination/atlas-pr-cleanup-env.example.yaml"
SERVICES_JSON="$ROOT/.github/config/services.json"

mkdir -p "$(dirname "$OUT")"

# Sorted, comma-joined list of every service in services.json. We use
# every service entry regardless of type because the cleanup-Job's
# image-cleanup phase iterates ATLAS_SERVICES and 404s on
# non-published targets are tolerated by `|| true` semantics
# (see cleanup.sh do_drop_images).
ATLAS_SERVICES=$(jq -r '.services[].name' "$SERVICES_JSON" | sort | paste -sd, -)

# ATLAS_DB_NAMES is a static literal duplicated from
# deploy/k8s/overlays/pr/kustomization.yaml's atlas-db-names
# configMapGenerator. It is NOT derivable from services.json today —
# DB-name ownership lives on the kustomize side. Keep in sync by
# review.
ATLAS_DB_NAMES="atlas-accounts atlas-bans atlas-buddies atlas-cashshop atlas-characters atlas-configurations atlas-data atlas-drops atlas-fame atlas-gachapons atlas-guilds atlas-inventory atlas-keys atlas-map-actions atlas-maps atlas-merchant atlas-monster-book atlas-notes atlas-npc-conversations atlas-npc-shops atlas-party-quests atlas-pets atlas-portal-actions atlas-quest atlas-reactor-actions atlas-saga-orchestrator atlas-skills atlas-storage atlas-tenants"

cat > "$OUT" <<EOF
# Not deployed from this repo. Mirror into cluster-infra (argocd
# namespace). Generated by deploy/k8s/overlays/pr/scripts/gen-cleanup-env.sh
# from .github/config/services.json — do not edit by hand. Re-run the
# generator after adding/removing a service or a DB.
#
# The atlas-pr-cleanup PostDelete Job consumes this ConfigMap via
# envFrom in deploy/k8s/overlays/pr-cleanup/postdelete-cleanup.yaml.
apiVersion: v1
kind: ConfigMap
metadata:
  name: atlas-pr-cleanup-env
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: atlas-pr-cleanup
data:
  DB_HOST: postgres.home
  DB_PORT: "5432"
  BOOTSTRAP_SERVERS: kafka.home:9093
  REDIS_URL: redis.home:6379
  ATLAS_DB_NAMES: "${ATLAS_DB_NAMES}"
  ATLAS_SERVICES: "${ATLAS_SERVICES}"
EOF

echo "Wrote $OUT"
