#!/usr/bin/env bash
# Generates an overlay's patches/db-name-suffix.yaml by reading each base
# Deployment's DB_NAME env var and emitting a strategic-merge patch
# suffixing it with a placeholder token. The PLACEHOLDER slot is rewritten
# at CI/sync time.
#
# Usage: gen-db-name-suffix.sh [OVERLAY] [SUFFIX_TOKEN]
#
#   pr / PLACEHOLDER_ATLAS_ENV (defaults)  — isolated mode: this env gets
#     its own databases, created by overlays/pr/wave0-create-dbs.yaml.
#   pr-sparse / PLACEHOLDER_BASELINE_ENVIRONMENT — sparse mode: this env
#     shares the BASELINE's databases (D1) and must therefore name them
#     the way the baseline names them. Leaving base's unsuffixed DB_NAME
#     to stand does NOT do that: every Atlas database in the cluster is
#     suffixed with its environment id (`atlas-characters-main`, …), and
#     there is no unsuffixed one to connect to. See
#     docs/tasks/task-232-sparse-ephemeral-environments/
#     bug-sparse-baseline-scoping.md.
#
# Services with no DB_NAME env var (e.g. atlas-ui, atlas-ingress,
# atlas-query-aggregator, atlas-renders) are skipped.
#
# Re-run after adding/removing a service or changing its DB_NAME.

set -euo pipefail

OVERLAY="${1:-pr}"
SUFFIX_TOKEN="${2:-PLACEHOLDER_ATLAS_ENV}"

ROOT="$(git rev-parse --show-toplevel)"
OUT="$ROOT/deploy/k8s/overlays/$OVERLAY/patches/db-name-suffix.yaml"
mkdir -p "$(dirname "$OUT")"

{
    echo "# Generated by deploy/k8s/overlays/pr/scripts/gen-db-name-suffix.sh $OVERLAY $SUFFIX_TOKEN"
    echo '# Do not edit by hand. Re-run after adding/removing services.'
    echo ''

    for f in "$ROOT"/deploy/k8s/base/atlas-*.yaml; do
        depname=$(basename "$f" .yaml)
        cname=$(yq eval-all 'select(.kind == "Deployment") | .spec.template.spec.containers[0].name' "$f" | head -1)
        db_name=$(yq eval-all 'select(.kind == "Deployment") | .spec.template.spec.containers[0].env[] | select(.name == "DB_NAME") | .value' "$f" | head -1)
        if [ -z "$cname" ] || [ "$cname" = "null" ] || [ -z "$db_name" ] || [ "$db_name" = "null" ]; then continue; fi

        cat <<EOF
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $depname
spec:
  template:
    spec:
      containers:
        - name: $cname
          env:
            - name: DB_NAME
              value: "${db_name}-${SUFFIX_TOKEN}"
EOF
    done
} > "$OUT"

echo "Wrote $(wc -l < "$OUT") lines to $OUT"
