package model

import (
	packetmodel "github.com/Chronicle20/atlas-packet/model"
)

// Type aliases re-exporting from atlas-packet/model
type CharacterTemporaryStatType = packetmodel.CharacterTemporaryStatType
type ForeignValueWriter = packetmodel.ForeignValueWriter
type CharacterTemporaryStatValue = packetmodel.CharacterTemporaryStatValue
type CharacterTemporaryStatBase = packetmodel.CharacterTemporaryStatBase
type SpeedInfusionTemporaryStat = packetmodel.SpeedInfusionTemporaryStat
type GuidedBulletTemporaryStat = packetmodel.GuidedBulletTemporaryStat
type CharacterTemporaryStat = packetmodel.CharacterTemporaryStat

// Function aliases
var NewCharacterTemporaryStatType = packetmodel.NewCharacterTemporaryStatType
var CharacterTemporaryStatTypeByName = packetmodel.CharacterTemporaryStatTypeByName
var NoOpForeignValueWriter = packetmodel.NoOpForeignValueWriter
var ValueAsByteForeignValueWriter = packetmodel.ValueAsByteForeignValueWriter
var ValueAsShortForeignValueWriter = packetmodel.ValueAsShortForeignValueWriter
var ValueAsIntForeignValueWriter = packetmodel.ValueAsIntForeignValueWriter
var LevelSourceForeignValueWriter = packetmodel.LevelSourceForeignValueWriter
var ValueSourceLevelForeignValueWriter = packetmodel.ValueSourceLevelForeignValueWriter
var NewCharacterTemporaryStatBase = packetmodel.NewCharacterTemporaryStatBase
var NewSpeedInfusionTemporaryStat = packetmodel.NewSpeedInfusionTemporaryStat
var NewGuidedBulletTemporaryStat = packetmodel.NewGuidedBulletTemporaryStat
var NewCharacterTemporaryStat = packetmodel.NewCharacterTemporaryStat
