package cmd

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/Chronicle20/atlas/tools/packet-audit/internal/discover"
	"github.com/Chronicle20/atlas/tools/packet-audit/internal/idasrc"
	"github.com/Chronicle20/atlas/tools/packet-audit/internal/opregistry"
)

type discoverOpsOpts struct {
	Version     string
	RegistryDir string
	Dispatchers []string // one or more dispatcher names/addresses
	IDAURL      string
	IDAPort     int
	Out         string // worklist markdown path
	Apply       bool
}

// runDiscoverOps is the discover-ops subcommand entry point. It accepts an
// injectable MCPClient so tests can supply a fake; when client is nil the real
// HTTP client is constructed from the flag values.
func runDiscoverOps(args []string, stderr io.Writer) int {
	fs := flag.NewFlagSet("packet-audit discover-ops", flag.ContinueOnError)
	fs.SetOutput(stderr)
	var opts discoverOpsOpts
	var dispatcherFlag string
	fs.StringVar(&opts.Version, "version", "", "target version key, e.g. gms_v83 (required)")
	fs.StringVar(&opts.RegistryDir, "registry-dir", "docs/packets/registry", "directory containing <version>.yaml registry files")
	fs.StringVar(&dispatcherFlag, "dispatcher", "CClientSocket::ProcessPacket", "comma-separated list of dispatcher function names and/or hex addresses")
	fs.StringVar(&opts.IDAURL, "ida-url", "http://192.168.20.3:13337/mcp", "IDA-MCP HTTP endpoint")
	fs.IntVar(&opts.IDAPort, "ida-port", 0, "IDA-MCP instance port to select (0 = default active instance)")
	fs.StringVar(&opts.Out, "out", "", "worklist markdown output path (default: docs/packets/registry/discover_<version>.md)")
	fs.BoolVar(&opts.Apply, "apply", false, "when true, append discovered ops to the registry YAML")

	if err := fs.Parse(args); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return 0
		}
		fmt.Fprintln(stderr, "packet-audit discover-ops: flag parse error:", err)
		return 3
	}
	if opts.Version == "" {
		fmt.Fprintln(stderr, "packet-audit discover-ops: missing required flag --version")
		return 3
	}
	if opts.Out == "" {
		opts.Out = filepath.Join(opts.RegistryDir, "discover_"+opts.Version+".md")
	}

	// Parse comma-separated dispatcher list, trimming whitespace and dropping empties.
	for _, d := range strings.Split(dispatcherFlag, ",") {
		d = strings.TrimSpace(d)
		if d != "" {
			opts.Dispatchers = append(opts.Dispatchers, d)
		}
	}
	if len(opts.Dispatchers) == 0 {
		fmt.Fprintln(stderr, "packet-audit discover-ops: --dispatcher produced an empty list")
		return 3
	}

	var client idasrc.MCPClient
	hc := &http.Client{Timeout: 60 * time.Second}
	if opts.IDAPort != 0 {
		client = idasrc.NewMCPHTTPClientWithInstance(opts.IDAURL, hc, opts.IDAPort)
	} else {
		client = idasrc.NewMCPHTTPClient(opts.IDAURL, hc)
	}
	return discoverOpsRun(opts, client, stderr)
}

// D7 deferral note: the serverbound registry-FName verification pass (design
// §D7, Task 5.4) is deliberately deferred to the operator-gated live run.
// It requires live decompiles of send-site functions in the IDB and cannot be
// exercised in offline/fixture tests. The worklist generated by this command
// covers clientbound ops only (dispatcher switch analysis); serverbound is out
// of scope until Task 5.4.

// discoverOpsRun is the pure (injectable) core of discover-ops.
func discoverOpsRun(opts discoverOpsOpts, client idasrc.MCPClient, stderr io.Writer) int {
	ctx := context.Background()

	dispResults := make([]discover.DispatcherResult, 0, len(opts.Dispatchers))

	multiDisp := len(opts.Dispatchers) > 1

	for _, dispName := range opts.Dispatchers {
		// Step 1: resolve dispatcher address.
		// If the name is already a hex address (starts with "0x"), pass it directly
		// to DecompileFunction without a name lookup.
		var addr string
		if strings.HasPrefix(strings.ToLower(dispName), "0x") {
			addr = dispName
		} else {
			var ok bool
			var err error
			addr, ok, err = client.GetFunctionByName(ctx, dispName)
			if err != nil {
				if multiDisp {
					failMsg := fmt.Sprintf("FAILED: GetFunctionByName: %v", err)
					fmt.Fprintf(stderr, "packet-audit discover-ops: warning: dispatcher %q lookup failed: %v — continuing\n", dispName, err)
					dispResults = append(dispResults, discover.DispatcherResult{Name: dispName, Addr: failMsg, Cases: nil})
					continue
				}
				fmt.Fprintf(stderr, "packet-audit discover-ops: GetFunctionByName(%q): %v\n", dispName, err)
				return 3
			}
			if !ok {
				if multiDisp {
					failMsg := "FAILED: not found in IDA"
					fmt.Fprintf(stderr, "packet-audit discover-ops: warning: dispatcher %q not found in IDA — continuing\n", dispName)
					dispResults = append(dispResults, discover.DispatcherResult{Name: dispName, Addr: failMsg, Cases: nil})
					continue
				}
				fmt.Fprintf(stderr, "packet-audit discover-ops: dispatcher %q not found in IDA\n", dispName)
				return 3
			}
		}

		// Step 2: decompile dispatcher.
		text, err := client.DecompileFunction(ctx, addr)
		if err != nil {
			if multiDisp {
				failMsg := fmt.Sprintf("FAILED: DecompileFunction: %v", err)
				fmt.Fprintf(stderr, "packet-audit discover-ops: warning: dispatcher %q decompile failed: %v — continuing\n", dispName, err)
				dispResults = append(dispResults, discover.DispatcherResult{Name: dispName, Addr: failMsg, Cases: nil})
				continue
			}
			fmt.Fprintf(stderr, "packet-audit discover-ops: DecompileFunction(%q): %v\n", addr, err)
			return 3
		}

		// Step 3: parse dispatch switch.
		cases, err := discover.ParseDispatch(text)
		if err != nil {
			fmt.Fprintf(stderr, "packet-audit discover-ops: ParseDispatch(%q): %v\n", dispName, err)
			return 3
		}
		if len(cases) == 0 {
			// Warn but continue — if-range routers legitimately parse to 0.
			fmt.Fprintf(stderr, "packet-audit discover-ops: warning: dispatcher %q@%s yielded 0 cases — may be if-based dispatch; continuing\n", dispName, addr)
			dispResults = append(dispResults, discover.DispatcherResult{Name: dispName, Addr: addr, Cases: nil})
			continue
		}

		// Step 4: resolve sub_ callees via GetCallees on the dispatcher.
		callees, err := client.GetCallees(ctx, addr)
		if err != nil {
			// Non-fatal: proceed without sub_ resolution.
			fmt.Fprintf(stderr, "packet-audit discover-ops: GetCallees warning (%q): %v\n", dispName, err)
		}
		calleeByAddr := map[string]string{} // hex-addr (lower) -> demangled name
		for _, c := range callees {
			if c.Name != "" {
				calleeByAddr[strings.ToLower(c.Addr)] = c.Name
			}
		}

		// Resolve sub_ handlers to demangled names when GetCallees provides a match.
		discovered := make([]discover.Discovered, 0, len(cases))
		for _, dc := range cases {
			handler := dc.Handler
			handlerAddr := addr // fallback: dispatcher address
			if strings.HasPrefix(handler, "sub_") {
				// IDA callee addresses are in the same hex format as the sub_ suffix.
				suffix := strings.ToLower(handler[4:]) // strip "sub_"
				lookupKey := "0x" + suffix
				if dm, ok := calleeByAddr[lookupKey]; ok && dm != "" {
					handler = dm
					handlerAddr = lookupKey
				} else {
					// Keep the sub_ name; use the address embedded in the name.
					handlerAddr = lookupKey
				}
			} else {
				// Named handler: find its address from the callee map by reverse lookup.
				for callAddr, callName := range calleeByAddr {
					if callName == handler {
						handlerAddr = callAddr
						break
					}
				}
			}
			discovered = append(discovered, discover.Discovered{
				Opcode:  dc.Opcode,
				Handler: handler,
				Address: handlerAddr,
			})
		}

		dispResults = append(dispResults, discover.DispatcherResult{
			Name:  dispName,
			Addr:  addr,
			Cases: discovered,
		})
	}

	// Step 5: union across all dispatchers.
	unified, internalCollisions := discover.Union(dispResults)

	// Count how many dispatchers actually failed (FAILED: prefix in Addr).
	failedCount := 0
	for _, dr := range dispResults {
		if strings.HasPrefix(dr.Addr, "FAILED:") {
			failedCount++
		}
	}
	if failedCount == len(dispResults) {
		fmt.Fprintf(stderr, "packet-audit discover-ops: all %d dispatcher(s) failed — cannot continue\n", len(dispResults))
		return 3
	}

	if len(unified) == 0 && len(internalCollisions) == 0 {
		// All dispatchers returned 0 cases — no useful discovery.
		fmt.Fprintf(stderr, "packet-audit discover-ops: total discovered cases across all dispatchers is 0 — check dispatcher names/addresses\n")
		return 3
	}

	// Step 6: load existing registry for this version.
	regPath := filepath.Join(opts.RegistryDir, opts.Version+".yaml")
	vf, err := loadRegistryOrEmpty(regPath)
	if err != nil {
		fmt.Fprintf(stderr, "packet-audit discover-ops: load registry %q: %v\n", regPath, err)
		return 3
	}

	// Step 7: reconcile clientbound.
	res := discover.Reconcile(vf, unified, opregistry.DirClientbound)

	// Step 8: write worklist markdown.
	md := buildWorklist(opts.Version, dispResults, internalCollisions, res)
	if err := os.MkdirAll(filepath.Dir(opts.Out), 0o755); err != nil {
		fmt.Fprintf(stderr, "packet-audit discover-ops: mkdir %q: %v\n", filepath.Dir(opts.Out), err)
		return 3
	}
	if err := os.WriteFile(opts.Out, []byte(md), 0o644); err != nil {
		fmt.Fprintf(stderr, "packet-audit discover-ops: write worklist: %v\n", err)
		return 3
	}

	// Step 9: --apply logic.
	if opts.Apply {
		// Internal collisions block --apply just like registry collisions do.
		if len(internalCollisions) > 0 {
			fmt.Fprintf(stderr, "packet-audit discover-ops: --apply refused: %d discovery-internal collision(s) must be resolved manually (see %s)\n", len(internalCollisions), opts.Out)
			return 1
		}
		if len(res.Collisions) > 0 {
			fmt.Fprintf(stderr, "packet-audit discover-ops: --apply refused: %d collision(s) must be resolved manually (see %s)\n", len(res.Collisions), opts.Out)
			return 1
		}
		if len(res.Append) > 0 {
			if err := applyAppend(regPath, vf, res.Append, opts.Version); err != nil {
				fmt.Fprintf(stderr, "packet-audit discover-ops: --apply failed: %v\n", err)
				return 3
			}
		}
	}

	return 0
}

// loadRegistryOrEmpty loads the registry YAML for a version; if the file does
// not exist it returns an empty VersionFile (first-run / v84 case).
func loadRegistryOrEmpty(path string) (*opregistry.VersionFile, error) {
	if _, err := os.Stat(path); os.IsNotExist(err) {
		return opregistry.NewVersionFile(nil), nil
	}
	return opregistry.LoadVersion(path)
}

// applyAppend merges the new entries into the existing registry YAML and
// self-validates via LoadVersion.
func applyAppend(path string, existing *opregistry.VersionFile, toAppend []opregistry.Entry, version string) error {
	entries := append(append([]opregistry.Entry(nil), existing.Entries...), toAppend...)
	// Stable sort: clientbound first, then by opcode, then by op name.
	sort.SliceStable(entries, func(i, j int) bool {
		if entries[i].Direction != entries[j].Direction {
			return entries[i].Direction == opregistry.DirClientbound
		}
		if entries[i].Opcode != entries[j].Opcode {
			return entries[i].Opcode < entries[j].Opcode
		}
		return entries[i].Op < entries[j].Op
	})

	raw, err := yaml.Marshal(entries)
	if err != nil {
		return err
	}
	header := "# Generated by `packet-audit discover-ops` — clientbound operation universe for " + version + ".\n" +
		"# Corrections/additions are hand-edited here (provenance: manual|ida-discovered);\n" +
		"# the source CSVs are frozen historical reference (design task-085 §5.1).\n"
	if err := os.WriteFile(path, []byte(header+string(raw)), 0o644); err != nil {
		return err
	}
	// Self-validate to catch any schema/uniqueness violation.
	if _, err := opregistry.LoadVersion(path); err != nil {
		return fmt.Errorf("self-validation after apply failed: %w", err)
	}
	return nil
}

// buildWorklist renders the reconciliation result as a markdown worklist.
// The header lists the dispatcher set used (name@address with case counts).
func buildWorklist(version string, dispResults []discover.DispatcherResult, internalCollisions []discover.InternalCollision, res discover.ReconcileResult) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "# discover-ops worklist — %s (clientbound only)\n\n", version)
	fmt.Fprintf(&sb, "Generated by `packet-audit discover-ops --version %s`.\n", version)
	fmt.Fprintln(&sb, "Covers clientbound ops (dispatcher switch analysis). Serverbound FName verification is deferred to Task 5.4 (operator-gated live run).")
	fmt.Fprintln(&sb)

	// Dispatcher set header.
	fmt.Fprintln(&sb, "## Dispatchers")
	fmt.Fprintln(&sb)
	fmt.Fprintln(&sb, "| Name | Address | Cases |")
	fmt.Fprintln(&sb, "|---|---|---|")
	for _, dr := range dispResults {
		if strings.HasPrefix(dr.Addr, "FAILED:") {
			fmt.Fprintf(&sb, "| `%s` | %s | — |\n", dr.Name, dr.Addr)
		} else {
			fmt.Fprintf(&sb, "| `%s` | `%s` | %d |\n", dr.Name, dr.Addr, len(dr.Cases))
		}
	}
	fmt.Fprintln(&sb)

	fmt.Fprintln(&sb, "## Append")
	fmt.Fprintln(&sb)
	if len(res.Append) == 0 {
		fmt.Fprintln(&sb, "_No new ops discovered._")
	} else {
		fmt.Fprintln(&sb, "New ops discovered by IDA that are not yet in the registry.")
		fmt.Fprintln(&sb, "Apply with `--apply` after reviewing.")
		fmt.Fprintln(&sb)
		fmt.Fprintln(&sb, "| Op | Opcode | FName | Provenance |")
		fmt.Fprintln(&sb, "|---|---|---|---|")
		for _, e := range res.Append {
			fmt.Fprintf(&sb, "| `%s` | `0x%03X` | `%s` | %s |\n", e.Op, e.Opcode, e.FName, e.Provenance)
		}
	}
	fmt.Fprintln(&sb)

	fmt.Fprintln(&sb, "## Review")
	fmt.Fprintln(&sb)

	hasReviewContent := len(internalCollisions) > 0 || len(res.Collisions) > 0 || len(res.MissingAtDiscovery) > 0
	if !hasReviewContent {
		fmt.Fprintln(&sb, "_No collisions, internal collisions, or missing ops._")
	} else {
		// Discovery-internal collisions.
		if len(internalCollisions) > 0 {
			fmt.Fprintln(&sb, "### Discovery-internal collisions")
			fmt.Fprintln(&sb)
			fmt.Fprintln(&sb, "Two dispatchers claim the same opcode with different handlers. These are excluded from the union. `--apply` is refused until these are resolved.")
			fmt.Fprintln(&sb)
			fmt.Fprintln(&sb, "| Opcode | Dispatcher A | Handler A | Dispatcher B | Handler B |")
			fmt.Fprintln(&sb, "|---|---|---|---|---|")
			for _, ic := range internalCollisions {
				fmt.Fprintf(&sb, "| `0x%03X` | `%s` | `%s` | `%s` | `%s` |\n",
					ic.Opcode, ic.DispA, ic.HandlerA.Handler, ic.DispB, ic.HandlerB.Handler)
			}
			fmt.Fprintln(&sb)
		}

		// Registry collisions.
		if len(res.Collisions) > 0 {
			fmt.Fprintln(&sb, "### Collisions")
			fmt.Fprintln(&sb)
			fmt.Fprintln(&sb, "Same opcode, different handler. `--apply` is refused until these are resolved.")
			fmt.Fprintln(&sb)
			fmt.Fprintln(&sb, "| Op | Opcode | Registry FName | IDA FName |")
			fmt.Fprintln(&sb, "|---|---|---|---|")
			for _, c := range res.Collisions {
				fmt.Fprintf(&sb, "| `%s` | `0x%03X` | `%s` | `%s` |\n",
					c.Entry.Op, c.Entry.Opcode, c.Entry.FName, c.Discovered.Handler)
			}
			fmt.Fprintln(&sb)
		}

		if len(res.MissingAtDiscovery) > 0 {
			fmt.Fprintln(&sb, "### Missing at discovery")
			fmt.Fprintln(&sb)
			fmt.Fprintln(&sb, "Registry entries whose opcode IDA did not discover. They are NOT auto-deleted.")
			fmt.Fprintln(&sb)
			fmt.Fprintln(&sb, "| Op | Opcode | FName |")
			fmt.Fprintln(&sb, "|---|---|---|")
			for _, e := range res.MissingAtDiscovery {
				fmt.Fprintf(&sb, "| `%s` | `0x%03X` | `%s` |\n", e.Op, e.Opcode, e.FName)
			}
			fmt.Fprintln(&sb)
		}
	}

	return sb.String()
}
