package cmd

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Chronicle20/atlas/tools/packet-audit/internal/opregistry"
	"github.com/Chronicle20/atlas/tools/packet-audit/internal/seedcsv"
	"gopkg.in/yaml.v3"
)

// seedVersions maps registry version keys to CSV column keys. gms_v84 has no
// CSV column (task-083: v84 ≡ v83 byte-identical); it copies GMS:83 with a note.
var seedVersions = []struct {
	Key    string
	CSVKey string
	Note   string
}{
	{"gms_v83", "GMS:83", ""},
	{"gms_v84", "GMS:83", "seeded from the v83 CSV column — the CSVs have no v84 column; task-083 found v84 byte-identical to v83. Corrected by discover-ops against the v84 IDB."},
	{"gms_v87", "GMS:87", ""},
	{"gms_v95", "GMS:95", ""},
	{"jms_v185", "JMS:185", ""},
}

func runRegistry(args []string, stderr io.Writer) int {
	if len(args) == 0 || args[0] != "seed" {
		fmt.Fprintln(stderr, "packet-audit registry: unknown subcommand (expected: seed)")
		return 3
	}
	fs := flag.NewFlagSet("packet-audit registry seed", flag.ContinueOnError)
	fs.SetOutput(stderr)
	cb := fs.String("clientbound", "docs/packets/MapleStory Ops - ClientBound.csv", "clientbound ops CSV")
	sb := fs.String("serverbound", "docs/packets/MapleStory Ops - ServerBound.csv", "serverbound ops CSV")
	out := fs.String("out", "docs/packets/registry", "output directory for registry YAMLs")
	if err := fs.Parse(args[1:]); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return 0
		}
		return 3
	}

	cbRows, err := seedcsv.Load(*cb)
	if err != nil {
		fmt.Fprintf(stderr, "packet-audit registry seed: %v\n", err)
		return 3
	}
	sbRows, err := seedcsv.Load(*sb)
	if err != nil {
		fmt.Fprintf(stderr, "packet-audit registry seed: %v\n", err)
		return 3
	}
	if err := os.MkdirAll(*out, 0o755); err != nil {
		fmt.Fprintf(stderr, "packet-audit registry seed: %v\n", err)
		return 3
	}
	for _, sv := range seedVersions {
		cbEntries := seedEntries(cbRows, opregistry.DirClientbound, sv.CSVKey, sv.Note)
		sbEntries := seedEntries(sbRows, opregistry.DirServerbound, sv.CSVKey, sv.Note)
		entries := append(cbEntries, sbEntries...)
		if len(entries) == 0 {
			fmt.Fprintf(stderr, "packet-audit registry seed: %s produced zero entries\n", sv.Key)
			return 3
		}
		sort.Slice(entries, func(i, j int) bool {
			if entries[i].Direction != entries[j].Direction {
				return entries[i].Direction == opregistry.DirClientbound
			}
			if entries[i].Opcode != entries[j].Opcode {
				return entries[i].Opcode < entries[j].Opcode
			}
			return entries[i].Op < entries[j].Op
		})
		raw, err := yaml.Marshal(entries)
		if err != nil {
			fmt.Fprintf(stderr, "packet-audit registry seed: %v\n", err)
			return 3
		}
		header := "# Generated by `packet-audit registry seed` — operation universe for " + sv.Key + ".\n" +
			"# Corrections/additions are hand-edited here (provenance: manual|ida-discovered);\n" +
			"# the source CSVs are frozen historical reference (design task-085 §5.1).\n"
		p := filepath.Join(*out, sv.Key+".yaml")
		if err := os.WriteFile(p, []byte(header+string(raw)), 0o644); err != nil {
			fmt.Fprintf(stderr, "packet-audit registry seed: %v\n", err)
			return 3
		}
		// Self-validation: round-trip through LoadVersion to guarantee the written
		// YAML is accepted by the registry loader (no duplicate keys, valid schema).
		if _, err := opregistry.LoadVersion(p); err != nil {
			fmt.Fprintf(stderr, "packet-audit registry seed: self-validation failed for %s: %v\n", sv.Key, err)
			return 3
		}
		fmt.Fprintf(os.Stdout, "seeded %s: %d entries (cb %d, sb %d)\n", sv.Key, len(entries), len(cbEntries), len(sbEntries))
	}
	return 0
}

func seedEntries(rows []seedcsv.Row, dir opregistry.Direction, csvKey, note string) []opregistry.Entry {
	dirStr := string(dir)
	var out []opregistry.Entry
	for _, r := range rows {
		cell, ok := r.Versions[csvKey]
		if !ok || !cell.Present {
			continue
		}
		op := r.Op
		fname := r.FName
		var fnameAlts []string

		// n/a placeholder rows: Op and/or FName are "n/a" (case-insensitive).
		// Emit a stable synthetic op name UNNAMED_R<line> with blank fname so the
		// registry has no duplicate (op, direction) keys and Phase-5 discovery can
		// flag these for human renaming.
		naOp := strings.EqualFold(op, "n/a")
		naFName := strings.EqualFold(fname, "n/a")
		if naOp {
			op = fmt.Sprintf("UNNAMED_R%d", r.Line)
		}
		if naOp || naFName {
			fname = ""
			fnameAlts = nil
		} else {
			fnameAlts = append([]string(nil), r.FNameAlts...)
		}

		entryNote := note
		if naOp {
			naNote := fmt.Sprintf("CSV %s row %d: op name unknown — rename via discover-ops adjudication (provenance: manual)", dirStr, r.Line)
			if entryNote != "" {
				entryNote = entryNote + " " + naNote
			} else {
				entryNote = naNote
			}
		}

		e := opregistry.Entry{
			Op:         op,
			Direction:  dir,
			Opcode:     cell.Opcode,
			FName:      fname,
			FNameAlts:  fnameAlts,
			Provenance: "csv-import",
			Note:       entryNote,
		}
		out = append(out, e)
	}
	return out
}
