package cmd

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"

	"github.com/Chronicle20/atlas/tools/packet-audit/internal/opregistry"
	"github.com/Chronicle20/atlas/tools/packet-audit/internal/seedcsv"
	"gopkg.in/yaml.v3"
)

// seedVersions maps registry version keys to CSV column keys. gms_v84 has no
// CSV column (task-083: v84 ≡ v83 byte-identical); it copies GMS:83 with a note.
var seedVersions = []struct {
	Key    string
	CSVKey string
	Note   string
}{
	{"gms_v83", "GMS:83", ""},
	{"gms_v84", "GMS:83", "seeded from the v83 CSV column — the CSVs have no v84 column; task-083 found v84 byte-identical to v83. Corrected by discover-ops against the v84 IDB."},
	{"gms_v87", "GMS:87", ""},
	{"gms_v95", "GMS:95", ""},
	{"jms_v185", "JMS:185", ""},
}

func runRegistry(args []string, stderr io.Writer) int {
	if len(args) == 0 || args[0] != "seed" {
		fmt.Fprintln(stderr, "packet-audit registry: unknown subcommand (expected: seed)")
		return 3
	}
	fs := flag.NewFlagSet("packet-audit registry seed", flag.ContinueOnError)
	fs.SetOutput(stderr)
	cb := fs.String("clientbound", "docs/packets/MapleStory Ops - ClientBound.csv", "clientbound ops CSV")
	sb := fs.String("serverbound", "docs/packets/MapleStory Ops - ServerBound.csv", "serverbound ops CSV")
	out := fs.String("out", "docs/packets/registry", "output directory for registry YAMLs")
	if err := fs.Parse(args[1:]); err != nil {
		return 3
	}

	cbRows, err := seedcsv.Load(*cb)
	if err != nil {
		fmt.Fprintf(stderr, "packet-audit registry seed: %v\n", err)
		return 1
	}
	sbRows, err := seedcsv.Load(*sb)
	if err != nil {
		fmt.Fprintf(stderr, "packet-audit registry seed: %v\n", err)
		return 1
	}
	if err := os.MkdirAll(*out, 0o755); err != nil {
		fmt.Fprintf(stderr, "packet-audit registry seed: %v\n", err)
		return 1
	}
	for _, sv := range seedVersions {
		entries := seedEntries(cbRows, opregistry.DirClientbound, sv.CSVKey, sv.Note)
		entries = append(entries, seedEntries(sbRows, opregistry.DirServerbound, sv.CSVKey, sv.Note)...)
		sort.Slice(entries, func(i, j int) bool {
			if entries[i].Direction != entries[j].Direction {
				return entries[i].Direction == opregistry.DirClientbound
			}
			if entries[i].Opcode != entries[j].Opcode {
				return entries[i].Opcode < entries[j].Opcode
			}
			return entries[i].Op < entries[j].Op
		})
		raw, err := yaml.Marshal(entries)
		if err != nil {
			fmt.Fprintf(stderr, "packet-audit registry seed: %v\n", err)
			return 1
		}
		header := "# Generated by `packet-audit registry seed` — operation universe for " + sv.Key + ".\n" +
			"# Corrections/additions are hand-edited here (provenance: manual|ida-discovered);\n" +
			"# the source CSVs are frozen historical reference (design task-085 §5.1).\n"
		p := filepath.Join(*out, sv.Key+".yaml")
		if err := os.WriteFile(p, []byte(header+string(raw)), 0o644); err != nil {
			fmt.Fprintf(stderr, "packet-audit registry seed: %v\n", err)
			return 1
		}
	}
	return 0
}

func seedEntries(rows []seedcsv.Row, dir opregistry.Direction, csvKey, note string) []opregistry.Entry {
	var out []opregistry.Entry
	for _, r := range rows {
		cell, ok := r.Versions[csvKey]
		if !ok || !cell.Present {
			continue
		}
		e := opregistry.Entry{
			Op:         r.Op,
			Direction:  dir,
			Opcode:     cell.Opcode,
			FName:      r.FName,
			FNameAlts:  append([]string(nil), r.FNameAlts...),
			Provenance: "csv-import",
			Note:       note,
		}
		out = append(out, e)
	}
	return out
}
