package matrix

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/Chronicle20/atlas/tools/packet-audit/internal/opregistry"
)

var shortLabels = map[string]string{
	"gms_v48": "v48",
	"gms_v61": "v61",
	"gms_v72": "v72",
	"gms_v79": "v79",
	"gms_v83": "v83", "gms_v84": "v84", "gms_v87": "v87",
	"gms_v95": "v95", "jms_v185": "JMS185",
}

func colLabel(vk string) string {
	return shortLabels[vk]
}

// RenderMarkdown produces STATUS.md (design §9): per direction one table,
// totals per version, conflicts section, generation stamp (tool SHA + export
// hashes; deliberately NO date — context.md D2, determinism).
func RenderMarkdown(m Matrix, versionKeys []string) string {
	var b strings.Builder
	b.WriteString("# Packet coverage matrix\n\n")
	b.WriteString("> Generated by `packet-audit matrix` — never hand-edit. Cell states (design task-085 §5):\n")
	b.WriteString("> ✅ verified · 🧩 family (mode-prefix dispatcher; sub-arms unverified) · 🟡 partial · ❌ incomplete · ⬜ n-a · 🟥 conflict\n\n")
	fmt.Fprintf(&b, "Tool: `%s`\n\n", m.ToolSHA)
	var hk []string
	for k := range m.ExportHashes {
		hk = append(hk, k)
	}
	sort.Strings(hk)
	for _, k := range hk {
		fmt.Fprintf(&b, "- export %s: `%s`\n", k, m.ExportHashes[k])
	}
	b.WriteString("\n")

	renderDirection(&b, m, versionKeys, opregistry.DirClientbound, "## Clientbound")
	renderDirection(&b, m, versionKeys, opregistry.DirServerbound, "## Serverbound")
	renderSubStructs(&b, m, versionKeys)
	renderTotals(&b, m, versionKeys)
	renderConflicts(&b, m, versionKeys)
	return b.String()
}

// opcodeCell renders the opcode column value for a given row+version.
// Returns "0x%03X" when the cell has a non-negative opcode, else blank.
func opcodeCell(row MatrixRow, vk string) string {
	if c, ok := row.Cells[vk]; ok && c.Opcode >= 0 {
		return fmt.Sprintf("0x%03X", c.Opcode)
	}
	return ""
}

func renderDirection(b *strings.Builder, m Matrix, versionKeys []string, dir opregistry.Direction, title string) {
	// Header: | Op | FName | Packet | v83 # | v83 | v84 # | v84 | ...
	fmt.Fprintf(b, "%s\n\n| Op | FName | Packet |", title)
	for _, vk := range versionKeys {
		lbl := colLabel(vk)
		fmt.Fprintf(b, " %s # | %s |", lbl, lbl)
	}
	b.WriteString("\n|----|-------|--------|")
	for range versionKeys {
		b.WriteString("-------|-----|")
	}
	b.WriteString("\n")
	for _, r := range m.Rows {
		if r.Kind != RowOp || r.Direction != dir {
			continue
		}
		pkt := r.Packet
		if r.Tier1 && pkt != "" {
			pkt += " (T1)"
		}
		fname := strings.Join(r.FNames, "; ")
		fmt.Fprintf(b, "| %s | %s | %s |", r.Op, fname, pkt)
		for _, vk := range versionKeys {
			fmt.Fprintf(b, " %s | %s |", opcodeCell(r, vk), r.Cells[vk].State.Symbol())
		}
		b.WriteString("\n")
	}
	b.WriteString("\n")
}

func renderSubStructs(b *strings.Builder, m Matrix, versionKeys []string) {
	// Header: | Packet | FName | v83 # | v83 | ...  (op# columns always blank for sub-structs)
	b.WriteString("## Sub-structs & shared types\n\n| Packet | FName |")
	for _, vk := range versionKeys {
		lbl := colLabel(vk)
		fmt.Fprintf(b, " %s # | %s |", lbl, lbl)
	}
	b.WriteString("\n|--------|-------|")
	for range versionKeys {
		b.WriteString("-------|-----|")
	}
	b.WriteString("\n")
	for _, r := range m.Rows {
		if r.Kind != RowSubStruct {
			continue
		}
		pkt := r.Packet
		if r.Tier1 {
			pkt += " (T1)"
		}
		// FName for sub-struct is the baseFName of the report IDAName; FNames
		// field is nil for sub-struct rows so we use the packet's base name from
		// Packet (last segment after the final "/") as a fallback display.
		fname := strings.Join(r.FNames, "; ")
		fmt.Fprintf(b, "| %s | %s |", pkt, fname)
		for _, vk := range versionKeys {
			// op# is always blank for sub-structs (Opcode = -1)
			fmt.Fprintf(b, " %s | %s |", opcodeCell(r, vk), r.Cells[vk].State.Symbol())
		}
		b.WriteString("\n")
	}
	b.WriteString("\n")
}

func renderTotals(b *strings.Builder, m Matrix, versionKeys []string) {
	b.WriteString("## Totals\n\n| Version | ✅ | 🧩 | 🟡 | ❌ | ⬜ | 🟥 | verified% |\n|---------|----|----|----|----|----|----|-----------|\n")
	for _, vk := range versionKeys {
		// Indexed by State value; sized to the number of states so an appended
		// state never indexes out of range.
		var counts [6]int
		total := 0
		for _, r := range m.Rows {
			c := r.Cells[vk]
			counts[c.State]++
			if c.State != StateNA {
				total++
			}
		}
		pct := 0.0
		if total > 0 {
			pct = 100 * float64(counts[StateVerified]) / float64(total)
		}
		fmt.Fprintf(b, "| %s | %d | %d | %d | %d | %d | %d | %.1f%% |\n",
			colLabel(vk), counts[StateVerified], counts[StateFamily], counts[StatePartial],
			counts[StateIncomplete], counts[StateNA], counts[StateConflict], pct)
	}
	b.WriteString("\n")
}

func renderConflicts(b *strings.Builder, m Matrix, versionKeys []string) {
	b.WriteString("## Conflicts\n\n")
	any := false
	for _, r := range m.Rows {
		for _, vk := range versionKeys {
			if c := r.Cells[vk]; c.State == StateConflict {
				any = true
				name := r.Op
				if name == "" {
					name = r.Packet
				}
				fmt.Fprintf(b, "- 🟥 **%s** × %s — %s\n", name, colLabel(vk), c.Note)
			}
		}
	}
	if !any {
		b.WriteString("None.\n")
	}
	b.WriteString("\n")
}

// RenderJSON produces status.json with the identical data (design §9).
func RenderJSON(m Matrix) ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}
