package matrix

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

// LoadMatrix reads a committed status.json back into a Matrix (the inverse of
// RenderJSON). Used by the support-summary and status commands, which report
// off the already-built matrix rather than rebuilding it.
func LoadMatrix(path string) (Matrix, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return Matrix{}, err
	}
	var m Matrix
	if err := json.Unmarshal(b, &m); err != nil {
		return Matrix{}, fmt.Errorf("%s: %w", path, err)
	}
	return m, nil
}

// GapRow is one cell surfaced in a summary gap table.
type GapRow struct {
	Kind      string // "op" | "sub-struct"
	Op        string
	Packet    string
	Direction string
	Opcode    int
	State     string
	Note      string
}

// name returns the row's display identity (op name, else packet path).
func (g GapRow) name() string {
	if g.Op != "" {
		return g.Op
	}
	return g.Packet
}

// Summary is the per-version aggregation shared by the support-summary (file)
// and status (stdout) commands (FR-4.3 / FR-4.4, task-169). Gap rows are split
// into deliberate n-a, open unverified, and conflict; stale-evidence rows are a
// flagged subset of the unverified gaps.
type Summary struct {
	Version     string
	Verified    int
	Family      int
	Partial     int
	Incomplete  int
	NACount     int
	Conflict    int
	Total       int // non-n-a denominator
	VerifiedPct float64

	NA         []GapRow // deliberate (⬜)
	Unverified []GapRow // open gaps (❌ incomplete + 🟡 partial + 🧩 family)
	Conflicts  []GapRow // 🟥
	Stale      []GapRow // subset of Unverified whose note signals stale/drifted evidence
}

// isStaleNote reports whether a cell note signals stale or unresolvable evidence.
func isStaleNote(note string) bool {
	n := strings.ToLower(note)
	return strings.Contains(n, "stale") || strings.Contains(n, "drift") || strings.Contains(n, "unresolvable")
}

// Summarize aggregates one version's cells across all rows of a built matrix.
func Summarize(m Matrix, version string) Summary {
	s := Summary{Version: version}
	for _, r := range m.Rows {
		c, ok := r.Cells[version]
		if !ok {
			continue
		}
		row := GapRow{
			Kind: r.Kind.kindName(), Op: r.Op, Packet: r.Packet,
			Direction: string(r.Direction), Opcode: c.Opcode,
			State: c.State.Name(), Note: c.Note,
		}
		switch c.State {
		case StateVerified:
			s.Verified++
		case StateFamily:
			s.Family++
			s.Unverified = append(s.Unverified, row)
		case StatePartial:
			s.Partial++
			s.Unverified = append(s.Unverified, row)
		case StateIncomplete:
			s.Incomplete++
			s.Unverified = append(s.Unverified, row)
			if isStaleNote(c.Note) {
				s.Stale = append(s.Stale, row)
			}
		case StateNA:
			s.NACount++
			s.NA = append(s.NA, row)
		case StateConflict:
			s.Conflict++
			s.Conflicts = append(s.Conflicts, row)
		}
	}
	s.Total = s.Verified + s.Family + s.Partial + s.Incomplete + s.Conflict
	if s.Total > 0 {
		s.VerifiedPct = 100 * float64(s.Verified) / float64(s.Total)
	}
	sortGaps(s.NA)
	sortGaps(s.Unverified)
	sortGaps(s.Conflicts)
	sortGaps(s.Stale)
	return s
}

// sortGaps orders rows deterministically: direction, then opcode, then name.
func sortGaps(rows []GapRow) {
	sort.SliceStable(rows, func(i, j int) bool {
		if rows[i].Direction != rows[j].Direction {
			return rows[i].Direction < rows[j].Direction
		}
		if rows[i].Opcode != rows[j].Opcode {
			return rows[i].Opcode < rows[j].Opcode
		}
		return rows[i].name() < rows[j].name()
	})
}

// RenderSupportMarkdown renders a per-version support summary document
// (FR-4.3). Deterministic — no wall-clock date (context.md D2).
func RenderSupportMarkdown(s Summary) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Packet support summary — %s\n\n", s.Version)
	b.WriteString("> Generated by `packet-audit support-summary` from status.json — never hand-edit.\n\n")

	b.WriteString("## Totals\n\n")
	b.WriteString("| ✅ verified | 🧩 family | 🟡 partial | ❌ incomplete | ⬜ n-a | 🟥 conflict | verified% |\n")
	b.WriteString("|-----------|----------|-----------|--------------|-------|------------|-----------|\n")
	fmt.Fprintf(&b, "| %d | %d | %d | %d | %d | %d | %.1f%% |\n\n",
		s.Verified, s.Family, s.Partial, s.Incomplete, s.NACount, s.Conflict, s.VerifiedPct)
	fmt.Fprintf(&b, "Verified %d of %d applicable (non-n-a) cells.\n\n", s.Verified, s.Total)

	renderGapTable(&b, "## Conflicts (🟥)", s.Conflicts)
	renderGapTable(&b, "## Unverified (open gaps)", s.Unverified)
	renderGapTable(&b, "## n-a (deliberate)", s.NA)
	return b.String()
}

func renderGapTable(b *strings.Builder, title string, rows []GapRow) {
	fmt.Fprintf(b, "%s\n\n", title)
	if len(rows) == 0 {
		b.WriteString("None.\n\n")
		return
	}
	b.WriteString("| Kind | Name | Dir | Opcode | State | Note |\n")
	b.WriteString("|------|------|-----|--------|-------|------|\n")
	for _, r := range rows {
		op := ""
		if r.Opcode >= 0 {
			op = fmt.Sprintf("0x%03X", r.Opcode)
		}
		fmt.Fprintf(b, "| %s | %s | %s | %s | %s | %s |\n",
			r.Kind, r.name(), r.Direction, op, r.State, r.Note)
	}
	b.WriteString("\n")
}
