FROM golang:1.25.5-alpine3.21 AS build-env

RUN apk add --no-cache git

ADD ./atlas.com/merchant/go.mod ./atlas.com/merchant/go.sum /atlas.com/merchant/
WORKDIR /atlas.com/merchant
RUN go mod download

ADD ./atlas.com/merchant /atlas.com/merchant
RUN go build -o /server

FROM alpine:3.23

EXPOSE 8080

RUN apk add --no-cache libc6-compat

WORKDIR /

COPY --from=build-env /server /

CMD ["/server"]
