package topicguard

import (
	"os"
	"testing"

	"golang.org/x/tools/go/analysis/analysistest"
)

// TestAnalyzer exercises diagnostics 1 and 2 against fixtures in a
// synthetic GOPATH with no go.work above it, so diagnostic 3 (manifest
// membership) is a silent no-op here by design — see loadManifestForPass.
func TestAnalyzer(t *testing.T) {
	testdata := analysistest.TestData()
	analysistest.Run(t, testdata, Analyzer,
		"atlas-example/bareliteral", // diagnostic 1: bare literal and untyped-const-ref args
		"atlas-example/rawenv",      // diagnostic 2: raw os.Getenv/LookupEnv of a topic-shaped name
		"atlas-example/declared",    // the passing shape — no diagnostics anywhere
	)
}

// TestTokenNotInManifest exercises diagnostic 3's manifest-membership
// helper directly, per the brief: analysistest's fixture GOPATH has no repo
// root to walk to, so this diagnostic cannot be exercised through
// analysistest.Run the way 1 and 2 are.
func TestTokenNotInManifest(t *testing.T) {
	tests := []struct {
		name     string
		manifest map[string]bool
		token    string
		want     string
	}{
		{
			name:     "present",
			manifest: map[string]bool{"COMMAND_TOPIC_A": true},
			token:    "COMMAND_TOPIC_A",
			want:     "",
		},
		{
			name:     "absent",
			manifest: map[string]bool{"COMMAND_TOPIC_A": true},
			token:    "EVENT_TOPIC_B",
			want:     `topic token "EVENT_TOPIC_B" is not in libs/atlas-kafka/gen/topics.yaml; run tools/gen-topics.sh`,
		},
		{
			name:     "manifest unreadable",
			manifest: nil,
			token:    "EVENT_TOPIC_B",
			want:     "",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := manifestDiagnostic(tt.manifest, tt.token)
			if got != tt.want {
				t.Errorf("manifestDiagnostic(%v, %q) = %q, want %q", tt.manifest, tt.token, got, tt.want)
			}
		})
	}
}

// TestLoadManifest pins loadManifest's line-oriented scan against the real
// checked-in topics.yaml shape (Task 5's header plus a `- token:` list),
// including the COMMAND_TOPIC_/EVENT_TOPIC_ prefix-constant entries that a
// prior implementer misread as stray data (topics.yaml:5,468) — they must
// load as ordinary tokens, not be filtered out.
func TestLoadManifest(t *testing.T) {
	dir := t.TempDir()
	path := dir + "/topics.yaml"
	writeFile(t, path, `# GENERATED by libs/atlas-kafka/gen -- do not edit.
# Source of truth: topic.Token constants in services/ and libs/.
# Regenerate: tools/gen-topics.sh    Drift check: tools/gen-topics.sh --check
topics:
  - token: COMMAND_TOPIC_
    cleanup: delete
    packages:
      - atlas.com/kafka-precreate/internal/discover
  - token: COMMAND_TOPIC_ACCOUNT
    cleanup: delete
    packages:
      - atlas-account/kafka/message/account
  - token: EVENT_TOPIC_
    cleanup: delete
    packages:
      - atlas.com/kafka-precreate/internal/discover
`)

	got, err := loadManifest(path)
	if err != nil {
		t.Fatalf("loadManifest: %v", err)
	}
	want := map[string]bool{
		"COMMAND_TOPIC_":        true,
		"COMMAND_TOPIC_ACCOUNT": true,
		"EVENT_TOPIC_":          true,
	}
	if len(got) != len(want) {
		t.Fatalf("loadManifest() = %v, want %v", got, want)
	}
	for k := range want {
		if !got[k] {
			t.Errorf("loadManifest() missing %q", k)
		}
	}

	if _, err := loadManifest(dir + "/does-not-exist.yaml"); err == nil {
		t.Fatal("loadManifest(missing file) = nil error, want an error")
	}
}

// TestParseAllowlistRequiresReason pins parseAllowlist's own contract,
// mirroring tools/scopeguard/allowlist.go's identically-shaped parser.
func TestParseAllowlistRequiresReason(t *testing.T) {
	cases := []struct {
		name    string
		raw     string
		wantErr bool
	}{
		{"empty file", "", false},
		{"comment only", "# just a comment\n", false},
		{"valid entry", "SOME_TOPIC_VAR # a real reason\n", false},
		{"no hash at all", "SOME_TOPIC_VAR\n", true},
		{"hash but empty reason", "SOME_TOPIC_VAR #\n", true},
		{"hash but whitespace reason", "SOME_TOPIC_VAR #   \n", true},
		{"duplicate key", "a # r1\na # r2\n", true},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			_, err := parseAllowlist(c.raw)
			if (err != nil) != c.wantErr {
				t.Errorf("parseAllowlist(%q) error = %v, wantErr %v", c.raw, err, c.wantErr)
			}
		})
	}
}

// TestAllowlistEntriesHaveReasons re-parses the real, checked-in
// allowlist.txt directly (rather than relying on package init having
// already succeeded) so a future malformed entry fails this test with a
// clear message instead of a cryptic init panic during `go test`.
func TestAllowlistEntriesHaveReasons(t *testing.T) {
	if _, err := parseAllowlist(allowlistRaw); err != nil {
		t.Fatalf("allowlist.txt: %v", err)
	}
}

func writeFile(t *testing.T, path, contents string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		t.Fatalf("writing %s: %v", path, err)
	}
}
