#!/usr/bin/env bash
# Generates deploy/k8s/base/routes.conf.template.generated and
# deploy/k8s/base/ns-vars.generated.yaml from deploy/shared/routes.conf by
# rewriting bare service hostnames to FQDNs templated on a per-service
# ${NS_<SERVICE>} variable. See task-232 Phase D Task 43 (design §5.3, P3).
#
# The routing table is static for an environment's entire life — the
# override set is fixed when the environment is created — so a sparse
# overlay only needs to override the NS_* value for the services it does
# not deploy, pointing them at the baseline namespace. In `main` and in
# isolated mode every NS_* variable defaults to $(POD_NAMESPACE), which
# reproduces the pre-task-232 routing table byte-for-byte (NFR-7).
#
#   gen-routes.sh           regenerate both output files
#   gen-routes.sh --check   generate to temp, diff vs checked-in; exit 1 on
#                           drift. No files are modified.
#
# Portability note: this uses bash's built-in `[[ =~ ]]` regex match (with
# BASH_REMATCH) rather than gawk's three-argument `match()`, which is not
# POSIX and is not available under the mawk/busybox awk this repo's CI and
# container images ship (verified: `awk --version` -> mawk 1.3.4).
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
SRC="$REPO_ROOT/deploy/shared/routes.conf"
OUT="$REPO_ROOT/deploy/k8s/base/routes.conf.template.generated"
NSVARS="$REPO_ROOT/deploy/k8s/base/ns-vars.generated.yaml"
INGRESS="$REPO_ROOT/deploy/k8s/base/atlas-ingress.yaml"

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

if [[ ! -f "$SRC" ]]; then
  echo "missing $SRC" >&2
  exit 1
fi

# Derive the NS_<SERVICE> variable name for a service hostname
# (atlas-party-quests -> NS_ATLAS_PARTY_QUESTS).
nsvar() {
  printf 'NS_%s' "$(printf '%s' "$1" | tr '[:lower:]-' '[:upper:]_')"
}

gen_routes() {
  local out="$1" line svc var
  : > "$out"
  while IFS= read -r line || [ -n "$line" ]; do
    if [[ "$line" =~ ^(.*set\ \$u\ \")(atlas-[a-z-]+)(:8080\".*)$ ]]; then
      svc="${BASH_REMATCH[2]}"
      var="$(nsvar "$svc")"
      printf '%s%s.${%s}.svc.cluster.local%s\n' \
        "${BASH_REMATCH[1]}" "$svc" "$var" "${BASH_REMATCH[3]}" >> "$out"
    elif [[ "$line" =~ ^(.*set\ \$u\ \")(atlas-ui)(:80\".*)$ ]]; then
      svc="${BASH_REMATCH[2]}"
      var="$(nsvar "$svc")"
      printf '%s%s.${%s}.svc.cluster.local%s\n' \
        "${BASH_REMATCH[1]}" "$svc" "$var" "${BASH_REMATCH[3]}" >> "$out"
    else
      printf '%s\n' "$line" >> "$out"
    fi
  done < "$SRC"
}

gen_nsvars() {
  local out="$1" svc var
  {
    echo "# GENERATED by tools/gen-routes.sh — do not edit."
    echo "# One variable per routed service. In main and in isolated mode every value"
    echo "# is \$(POD_NAMESPACE), which reproduces the pre-task-232 routing table"
    echo "# byte-for-byte (NFR-7). A sparse overlay overrides only the services it"
    echo "# does not deploy, pointing them at the baseline's namespace."
  } > "$out"
  {
    grep -oE 'set \$u "atlas-[a-z-]+:8080"' "$SRC" \
      | sed -E 's/.*"(atlas-[a-z-]+):8080".*/\1/'
    grep -oE 'set \$u "atlas-ui:80"' "$SRC" \
      | sed -E 's/.*"(atlas-ui):80".*/\1/'
  } | sort -u | while IFS= read -r svc; do
    var="$(nsvar "$svc")"
    {
      printf -- '- name: %s\n' "$var"
      printf '  value: $(POD_NAMESPACE)\n'
    } >> "$out"
  done
}

# The NS_* env block in atlas-ingress.yaml is the only place these variables
# are actually DEFINED for nginx. It is maintained by hand (overlays patch
# individual entries by name, and each value must stay in k8s $(POD_NAMESPACE)
# form), so nothing regenerates it — but a routed service missing from it is a
# hard outage, not a cosmetic drift: NGINX_ENVSUBST_FILTER only substitutes
# variables that are DEFINED, so an undefined ${NS_ATLAS_FOO} survives envsubst
# literally and nginx rejects the config at startup with
# `unknown "ns_atlas_foo" variable`, taking the whole ingress down. Verified
# against atlas-families, which reached main routed-but-undefined.
check_ingress() {
  local nsvars="$1" want have
  want="$(grep -oE 'NS_ATLAS_[A-Z_]+' "$nsvars" | sort -u)"
  have="$(grep -oE 'NS_ATLAS_[A-Z_]+' "$INGRESS" | sort -u)"
  if [ "$want" = "$have" ]; then
    return 0
  fi
  echo "gen-routes: deploy/k8s/base/atlas-ingress.yaml NS_* env block is out of sync." >&2
  comm -23 <(printf '%s\n' "$want") <(printf '%s\n' "$have") | while IFS= read -r v; do
    [ -n "$v" ] && echo "  routed but NOT DEFINED in the ingress (nginx will fail to start): $v" >&2
  done
  comm -13 <(printf '%s\n' "$want") <(printf '%s\n' "$have") | while IFS= read -r v; do
    [ -n "$v" ] && echo "  defined in the ingress but no longer routed (remove it): $v" >&2
  done
  echo "  Add/remove the matching '- name: <VAR>' / 'value: \$(POD_NAMESPACE)' pair(s)." >&2
  return 1
}

if [ "$CHECK" = 1 ]; then
  tmp_routes="$(mktemp)"
  tmp_nsvars="$(mktemp)"
  trap 'rm -f "$tmp_routes" "$tmp_nsvars"' EXIT
  gen_routes "$tmp_routes"
  gen_nsvars "$tmp_nsvars"
  status=0
  diff -u "$OUT" "$tmp_routes" || status=1
  diff -u "$NSVARS" "$tmp_nsvars" || status=1
  check_ingress "$tmp_nsvars" || status=1
  if [ "$status" -ne 0 ]; then
    echo "gen-routes: output is stale; run tools/gen-routes.sh and commit" >&2
    exit 1
  fi
  echo "gen-routes: up to date"
else
  gen_routes "$OUT"
  gen_nsvars "$NSVARS"
  echo "wrote $OUT ($(wc -l <"$OUT") lines)"
  echo "wrote $NSVARS ($(wc -l <"$NSVARS") lines)"
  # Regenerating can newly route a service whose NS_* variable the ingress
  # never defined; fail here rather than let it reach a cluster.
  check_ingress "$NSVARS"
fi
