---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-redis
  namespace: atlas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlas-redis
  template:
    metadata:
      labels:
        app: atlas-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        args: ["--save", "60", "1", "--loglevel", "warning"]
---
apiVersion: v1
kind: Service
metadata:
  name: atlas-redis
  namespace: atlas
spec:
  selector:
    app: atlas-redis
  ports:
  - protocol: TCP
    port: 6379
