name: 'Node.js Test'
description: 'Install, test, and build Node.js projects'

inputs:
  working-directory:
    description: 'Working directory containing package.json'
    required: true
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22'
  skip-tests:
    description: 'Skip running tests'
    required: false
    default: 'false'
  skip-build:
    description: 'Skip running build'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm ci

    - name: Run linter
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if npm run lint --if-present 2>/dev/null; then
          echo "Linting passed"
        else
          echo "No lint script found or linting skipped"
        fi
      continue-on-error: true

    - name: Run tests
      if: inputs.skip-tests != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if npm run test --if-present 2>/dev/null; then
          echo "Tests passed"
        else
          echo "No test script found"
        fi

    - name: Build
      if: inputs.skip-build != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm run build
